/*
 * WARNING: do not edit!
 * Generated by Makefile from include/openssl/cmp.h.in
 *
 * Copyright 2007-2024 The OpenSSL Project Authors. All Rights Reserved.
 * Copyright Nokia 2007-2019
 * Copyright Siemens AG 2015-2019
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

/* clang-format off */

/* clang-format on */

#ifndef OPENSSL_CMP_H
#define OPENSSL_CMP_H

#include <openssl/opensslconf.h>
#ifndef OPENSSL_NO_CMP

#include <openssl/crmf.h>
#include <openssl/cmperr.h>
#include <openssl/cmp_util.h>
#include <openssl/http.h>

/* explicit #includes not strictly needed since implied by the above: */
#include <openssl/types.h>
#include <openssl/safestack.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>

#ifdef __cplusplus
extern "C" {
#endif

#define OSSL_CMP_PVNO_2 2
#define OSSL_CMP_PVNO_3 3
#define OSSL_CMP_PVNO OSSL_CMP_PVNO_2 /* v2 is the default */

/*-
 *   PKIFailureInfo ::= BIT STRING {
 *   -- since we can fail in more than one way!
 *   -- More codes may be added in the future if/when required.
 *       badAlg              (0),
 *       -- unrecognized or unsupported Algorithm Identifier
 *       badMessageCheck     (1),
 *       -- integrity check failed (e.g., signature did not verify)
 *       badRequest          (2),
 *       -- transaction not permitted or supported
 *       badTime             (3),
 *       -- messageTime was not sufficiently close to the system time,
 *       -- as defined by local policy
 *       badCertId           (4),
 *       -- no certificate could be found matching the provided criteria
 *       badDataFormat       (5),
 *       -- the data submitted has the wrong format
 *       wrongAuthority      (6),
 *       -- the authority indicated in the request is different from the
 *       -- one creating the response token
 *       incorrectData       (7),
 *       -- the requester's data is incorrect (for notary services)
 *       missingTimeStamp    (8),
 *       -- when the timestamp is missing but should be there
 *       -- (by policy)
 *       badPOP              (9),
 *       -- the proof-of-possession failed
 *       certRevoked         (10),
 *          -- the certificate has already been revoked
 *       certConfirmed       (11),
 *          -- the certificate has already been confirmed
 *       wrongIntegrity      (12),
 *          -- invalid integrity, password based instead of signature or
 *          -- vice versa
 *       badRecipientNonce   (13),
 *          -- invalid recipient nonce, either missing or wrong value
 *       timeNotAvailable    (14),
 *          -- the TSA's time source is not available
 *       unacceptedPolicy    (15),
 *          -- the requested TSA policy is not supported by the TSA.
 *       unacceptedExtension (16),
 *          -- the requested extension is not supported by the TSA.
 *       addInfoNotAvailable (17),
 *          -- the additional information requested could not be
 *          -- understood or is not available
 *       badSenderNonce      (18),
 *          -- invalid sender nonce, either missing or wrong size
 *       badCertTemplate     (19),
 *          -- invalid cert. template or missing mandatory information
 *       signerNotTrusted    (20),
 *          -- signer of the message unknown or not trusted
 *       transactionIdInUse  (21),
 *          -- the transaction identifier is already in use
 *       unsupportedVersion  (22),
 *          -- the version of the message is not supported
 *       notAuthorized       (23),
 *          -- the sender was not authorized to make the preceding
 *          -- request or perform the preceding action
 *       systemUnavail       (24),
 *       -- the request cannot be handled due to system unavailability
 *       systemFailure       (25),
 *       -- the request cannot be handled due to system failure
 *       duplicateCertReq    (26)
 *       -- certificate cannot be issued because a duplicate
 *       -- certificate already exists
 *   }
 */
#define OSSL_CMP_PKIFAILUREINFO_badAlg 0
#define OSSL_CMP_PKIFAILUREINFO_badMessageCheck 1
#define OSSL_CMP_PKIFAILUREINFO_badRequest 2
#define OSSL_CMP_PKIFAILUREINFO_badTime 3
#define OSSL_CMP_PKIFAILUREINFO_badCertId 4
#define OSSL_CMP_PKIFAILUREINFO_badDataFormat 5
#define OSSL_CMP_PKIFAILUREINFO_wrongAuthority 6
#define OSSL_CMP_PKIFAILUREINFO_incorrectData 7
#define OSSL_CMP_PKIFAILUREINFO_missingTimeStamp 8
#define OSSL_CMP_PKIFAILUREINFO_badPOP 9
#define OSSL_CMP_PKIFAILUREINFO_certRevoked 10
#define OSSL_CMP_PKIFAILUREINFO_certConfirmed 11
#define OSSL_CMP_PKIFAILUREINFO_wrongIntegrity 12
#define OSSL_CMP_PKIFAILUREINFO_badRecipientNonce 13
#define OSSL_CMP_PKIFAILUREINFO_timeNotAvailable 14
#define OSSL_CMP_PKIFAILUREINFO_unacceptedPolicy 15
#define OSSL_CMP_PKIFAILUREINFO_unacceptedExtension 16
#define OSSL_CMP_PKIFAILUREINFO_addInfoNotAvailable 17
#define OSSL_CMP_PKIFAILUREINFO_badSenderNonce 18
#define OSSL_CMP_PKIFAILUREINFO_badCertTemplate 19
#define OSSL_CMP_PKIFAILUREINFO_signerNotTrusted 20
#define OSSL_CMP_PKIFAILUREINFO_transactionIdInUse 21
#define OSSL_CMP_PKIFAILUREINFO_unsupportedVersion 22
#define OSSL_CMP_PKIFAILUREINFO_notAuthorized 23
#define OSSL_CMP_PKIFAILUREINFO_systemUnavail 24
#define OSSL_CMP_PKIFAILUREINFO_systemFailure 25
#define OSSL_CMP_PKIFAILUREINFO_duplicateCertReq 26
#define OSSL_CMP_PKIFAILUREINFO_MAX 26
#define OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN \
    ((1 << (OSSL_CMP_PKIFAILUREINFO_MAX + 1)) - 1)
#if OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN > INT_MAX
#error CMP_PKIFAILUREINFO_MAX bit pattern does not fit in type int
#endif
/**
 * @brief ASN.1 BIT STRING encoding PKIFailureInfo failure flags (RFC 4210).
 */
typedef ASN1_BIT_STRING OSSL_CMP_PKIFAILUREINFO;

#define OSSL_CMP_CTX_FAILINFO_badAlg (1 << 0)
#define OSSL_CMP_CTX_FAILINFO_badMessageCheck (1 << 1)
#define OSSL_CMP_CTX_FAILINFO_badRequest (1 << 2)
#define OSSL_CMP_CTX_FAILINFO_badTime (1 << 3)
#define OSSL_CMP_CTX_FAILINFO_badCertId (1 << 4)
#define OSSL_CMP_CTX_FAILINFO_badDataFormat (1 << 5)
#define OSSL_CMP_CTX_FAILINFO_wrongAuthority (1 << 6)
#define OSSL_CMP_CTX_FAILINFO_incorrectData (1 << 7)
#define OSSL_CMP_CTX_FAILINFO_missingTimeStamp (1 << 8)
#define OSSL_CMP_CTX_FAILINFO_badPOP (1 << 9)
#define OSSL_CMP_CTX_FAILINFO_certRevoked (1 << 10)
#define OSSL_CMP_CTX_FAILINFO_certConfirmed (1 << 11)
#define OSSL_CMP_CTX_FAILINFO_wrongIntegrity (1 << 12)
#define OSSL_CMP_CTX_FAILINFO_badRecipientNonce (1 << 13)
#define OSSL_CMP_CTX_FAILINFO_timeNotAvailable (1 << 14)
#define OSSL_CMP_CTX_FAILINFO_unacceptedPolicy (1 << 15)
#define OSSL_CMP_CTX_FAILINFO_unacceptedExtension (1 << 16)
#define OSSL_CMP_CTX_FAILINFO_addInfoNotAvailable (1 << 17)
#define OSSL_CMP_CTX_FAILINFO_badSenderNonce (1 << 18)
#define OSSL_CMP_CTX_FAILINFO_badCertTemplate (1 << 19)
#define OSSL_CMP_CTX_FAILINFO_signerNotTrusted (1 << 20)
#define OSSL_CMP_CTX_FAILINFO_transactionIdInUse (1 << 21)
#define OSSL_CMP_CTX_FAILINFO_unsupportedVersion (1 << 22)
#define OSSL_CMP_CTX_FAILINFO_notAuthorized (1 << 23)
#define OSSL_CMP_CTX_FAILINFO_systemUnavail (1 << 24)
#define OSSL_CMP_CTX_FAILINFO_systemFailure (1 << 25)
#define OSSL_CMP_CTX_FAILINFO_duplicateCertReq (1 << 26)

/*-
 *   PKIStatus ::= INTEGER {
 *       accepted                (0),
 *       -- you got exactly what you asked for
 *       grantedWithMods        (1),
 *       -- you got something like what you asked for; the
 *       -- requester is responsible for ascertaining the differences
 *       rejection              (2),
 *       -- you don't get it, more information elsewhere in the message
 *       waiting                (3),
 *       -- the request body part has not yet been processed; expect to
 *       -- hear more later (note: proper handling of this status
 *       -- response MAY use the polling req/rep PKIMessages specified
 *       -- in Section 5.3.22; alternatively, polling in the underlying
 *       -- transport layer MAY have some utility in this regard)
 *       revocationWarning      (4),
 *       -- this message contains a warning that a revocation is
 *       -- imminent
 *       revocationNotification (5),
 *       -- notification that a revocation has occurred
 *       keyUpdateWarning       (6)
 *       -- update already done for the oldCertId specified in
 *       -- CertReqMsg
 *   }
 */
#define OSSL_CMP_PKISTATUS_request -3
#define OSSL_CMP_PKISTATUS_trans -2
#define OSSL_CMP_PKISTATUS_unspecified -1
#define OSSL_CMP_PKISTATUS_accepted 0
#define OSSL_CMP_PKISTATUS_grantedWithMods 1
#define OSSL_CMP_PKISTATUS_rejection 2
#define OSSL_CMP_PKISTATUS_waiting 3
#define OSSL_CMP_PKISTATUS_revocationWarning 4
#define OSSL_CMP_PKISTATUS_revocationNotification 5
#define OSSL_CMP_PKISTATUS_keyUpdateWarning 6
/**
 * @brief ASN.1 INTEGER encoding a PKIStatus value (RFC 4210).
 */
typedef ASN1_INTEGER OSSL_CMP_PKISTATUS;

/**
 * @brief Return the ASN.1 item descriptor for OSSL_CMP_PKISTATUS.
 * @return Pointer to the static ASN1_ITEM for OSSL_CMP_PKISTATUS.
 */
const ASN1_ITEM *OSSL_CMP_PKISTATUS_it(void);

#define OSSL_CMP_CERTORENCCERT_CERTIFICATE 0
#define OSSL_CMP_CERTORENCCERT_ENCRYPTEDCERT 1

/* data type declarations */
/**
 * @brief Opaque CMP client or server context holding transaction state and options.
 */
typedef struct ossl_cmp_ctx_st OSSL_CMP_CTX;
/**
 * @brief Opaque PKIHeader structure for a CMP PKIMessage (RFC 4210 section 5.2).
 */
typedef struct ossl_cmp_pkiheader_st OSSL_CMP_PKIHEADER;
/**
 * @brief Allocate an empty OSSL_CMP_PKIHEADER structure.
 * @return New OSSL_CMP_PKIHEADER, or NULL on allocation failure.
 */
OSSL_CMP_PKIHEADER *OSSL_CMP_PKIHEADER_new(void);
/**
 * @brief Free an OSSL_CMP_PKIHEADER structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CMP_PKIHEADER_free(OSSL_CMP_PKIHEADER *a);
/**
 * @brief Decode an OSSL_CMP_PKIHEADER from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CMP_PKIHEADER, or NULL on error.
 */
OSSL_CMP_PKIHEADER *d2i_OSSL_CMP_PKIHEADER(OSSL_CMP_PKIHEADER **a, const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CMP_PKIHEADER to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CMP_PKIHEADER(const OSSL_CMP_PKIHEADER *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CMP_PKIHEADER.
 * @return Pointer to the static ASN1_ITEM for OSSL_CMP_PKIHEADER.
 */
const ASN1_ITEM *OSSL_CMP_PKIHEADER_it(void);
/**
 * @brief Opaque PKIMessage structure (PKIHeader and body) from RFC 4210.
 */
typedef struct ossl_cmp_msg_st OSSL_CMP_MSG;
/**
 * @brief Allocate an empty OSSL_CMP_MSG structure.
 * @return New OSSL_CMP_MSG, or NULL on allocation failure.
 */
OSSL_CMP_MSG *OSSL_CMP_MSG_new(void);
/**
 * @brief Free an OSSL_CMP_MSG structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CMP_MSG_free(OSSL_CMP_MSG *a);
/**
 * @brief Decode an OSSL_CMP_MSG from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CMP_MSG, or NULL on error.
 */
OSSL_CMP_MSG *d2i_OSSL_CMP_MSG(OSSL_CMP_MSG **a, const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CMP_MSG to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CMP_MSG(const OSSL_CMP_MSG *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CMP_MSG.
 * @return Pointer to the static ASN1_ITEM for OSSL_CMP_MSG.
 */
const ASN1_ITEM *OSSL_CMP_MSG_it(void);
/**
 * @brief Duplicate an OSSL_CMP_MSG structure.
 * @param a Value to duplicate.
 * @return Copy of @p a, or NULL on error.
 */
OSSL_CMP_MSG *OSSL_CMP_MSG_dup(const OSSL_CMP_MSG *a);
/**
 * @brief CertStatus from RFC 4210 section 5.3.18: certHash and certReqId for certConf.
 */
typedef struct ossl_cmp_certstatus_st OSSL_CMP_CERTSTATUS;
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CMP_CERTSTATUS, OSSL_CMP_CERTSTATUS, OSSL_CMP_CERTSTATUS)
#define sk_OSSL_CMP_CERTSTATUS_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CMP_CERTSTATUS_sk_type(sk))
#define sk_OSSL_CMP_CERTSTATUS_value(sk, idx) ((OSSL_CMP_CERTSTATUS *)OPENSSL_sk_value(ossl_check_const_OSSL_CMP_CERTSTATUS_sk_type(sk), (idx)))
#define sk_OSSL_CMP_CERTSTATUS_new(cmp) ((STACK_OF(OSSL_CMP_CERTSTATUS) *)OPENSSL_sk_new(ossl_check_OSSL_CMP_CERTSTATUS_compfunc_type(cmp)))
#define sk_OSSL_CMP_CERTSTATUS_new_null() ((STACK_OF(OSSL_CMP_CERTSTATUS) *)OPENSSL_sk_new_null())
#define sk_OSSL_CMP_CERTSTATUS_new_reserve(cmp, n) ((STACK_OF(OSSL_CMP_CERTSTATUS) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CMP_CERTSTATUS_compfunc_type(cmp), (n)))
#define sk_OSSL_CMP_CERTSTATUS_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), (n))
#define sk_OSSL_CMP_CERTSTATUS_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk))
#define sk_OSSL_CMP_CERTSTATUS_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk))
#define sk_OSSL_CMP_CERTSTATUS_delete(sk, i) ((OSSL_CMP_CERTSTATUS *)OPENSSL_sk_delete(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), (i)))
#define sk_OSSL_CMP_CERTSTATUS_delete_ptr(sk, ptr) ((OSSL_CMP_CERTSTATUS *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr)))
#define sk_OSSL_CMP_CERTSTATUS_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr))
#define sk_OSSL_CMP_CERTSTATUS_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr))
#define sk_OSSL_CMP_CERTSTATUS_pop(sk) ((OSSL_CMP_CERTSTATUS *)OPENSSL_sk_pop(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk)))
#define sk_OSSL_CMP_CERTSTATUS_shift(sk) ((OSSL_CMP_CERTSTATUS *)OPENSSL_sk_shift(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk)))
#define sk_OSSL_CMP_CERTSTATUS_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk),ossl_check_OSSL_CMP_CERTSTATUS_freefunc_type(freefunc))
#define sk_OSSL_CMP_CERTSTATUS_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr), (idx))
#define sk_OSSL_CMP_CERTSTATUS_set(sk, idx, ptr) ((OSSL_CMP_CERTSTATUS *)OPENSSL_sk_set(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), (idx), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr)))
#define sk_OSSL_CMP_CERTSTATUS_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr))
#define sk_OSSL_CMP_CERTSTATUS_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr))
#define sk_OSSL_CMP_CERTSTATUS_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_type(ptr), pnum)
#define sk_OSSL_CMP_CERTSTATUS_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk))
#define sk_OSSL_CMP_CERTSTATUS_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CMP_CERTSTATUS_sk_type(sk))
#define sk_OSSL_CMP_CERTSTATUS_dup(sk) ((STACK_OF(OSSL_CMP_CERTSTATUS) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CMP_CERTSTATUS_sk_type(sk)))
#define sk_OSSL_CMP_CERTSTATUS_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CMP_CERTSTATUS) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_copyfunc_type(copyfunc), ossl_check_OSSL_CMP_CERTSTATUS_freefunc_type(freefunc)))
#define sk_OSSL_CMP_CERTSTATUS_set_cmp_func(sk, cmp) ((sk_OSSL_CMP_CERTSTATUS_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CMP_CERTSTATUS_sk_type(sk), ossl_check_OSSL_CMP_CERTSTATUS_compfunc_type(cmp)))

/* clang-format on */
/**
 * @brief Opaque InfoTypeAndValue (ITAV) key-value pair used in CMP messages (RFC 4210 section 5.3.19).
 */
typedef struct ossl_cmp_itav_st OSSL_CMP_ITAV;
/**
 * @brief Duplicate an OSSL_CMP_ITAV structure.
 * @param a Value to duplicate.
 * @return Copy of @p a, or NULL on error.
 */
OSSL_CMP_ITAV *OSSL_CMP_ITAV_dup(const OSSL_CMP_ITAV *a);
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CMP_ITAV, OSSL_CMP_ITAV, OSSL_CMP_ITAV)
#define sk_OSSL_CMP_ITAV_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CMP_ITAV_sk_type(sk))
#define sk_OSSL_CMP_ITAV_value(sk, idx) ((OSSL_CMP_ITAV *)OPENSSL_sk_value(ossl_check_const_OSSL_CMP_ITAV_sk_type(sk), (idx)))
#define sk_OSSL_CMP_ITAV_new(cmp) ((STACK_OF(OSSL_CMP_ITAV) *)OPENSSL_sk_new(ossl_check_OSSL_CMP_ITAV_compfunc_type(cmp)))
#define sk_OSSL_CMP_ITAV_new_null() ((STACK_OF(OSSL_CMP_ITAV) *)OPENSSL_sk_new_null())
#define sk_OSSL_CMP_ITAV_new_reserve(cmp, n) ((STACK_OF(OSSL_CMP_ITAV) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CMP_ITAV_compfunc_type(cmp), (n)))
#define sk_OSSL_CMP_ITAV_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CMP_ITAV_sk_type(sk), (n))
#define sk_OSSL_CMP_ITAV_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CMP_ITAV_sk_type(sk))
#define sk_OSSL_CMP_ITAV_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CMP_ITAV_sk_type(sk))
#define sk_OSSL_CMP_ITAV_delete(sk, i) ((OSSL_CMP_ITAV *)OPENSSL_sk_delete(ossl_check_OSSL_CMP_ITAV_sk_type(sk), (i)))
#define sk_OSSL_CMP_ITAV_delete_ptr(sk, ptr) ((OSSL_CMP_ITAV *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr)))
#define sk_OSSL_CMP_ITAV_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr))
#define sk_OSSL_CMP_ITAV_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr))
#define sk_OSSL_CMP_ITAV_pop(sk) ((OSSL_CMP_ITAV *)OPENSSL_sk_pop(ossl_check_OSSL_CMP_ITAV_sk_type(sk)))
#define sk_OSSL_CMP_ITAV_shift(sk) ((OSSL_CMP_ITAV *)OPENSSL_sk_shift(ossl_check_OSSL_CMP_ITAV_sk_type(sk)))
#define sk_OSSL_CMP_ITAV_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CMP_ITAV_sk_type(sk),ossl_check_OSSL_CMP_ITAV_freefunc_type(freefunc))
#define sk_OSSL_CMP_ITAV_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr), (idx))
#define sk_OSSL_CMP_ITAV_set(sk, idx, ptr) ((OSSL_CMP_ITAV *)OPENSSL_sk_set(ossl_check_OSSL_CMP_ITAV_sk_type(sk), (idx), ossl_check_OSSL_CMP_ITAV_type(ptr)))
#define sk_OSSL_CMP_ITAV_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr))
#define sk_OSSL_CMP_ITAV_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr))
#define sk_OSSL_CMP_ITAV_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_type(ptr), pnum)
#define sk_OSSL_CMP_ITAV_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CMP_ITAV_sk_type(sk))
#define sk_OSSL_CMP_ITAV_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CMP_ITAV_sk_type(sk))
#define sk_OSSL_CMP_ITAV_dup(sk) ((STACK_OF(OSSL_CMP_ITAV) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CMP_ITAV_sk_type(sk)))
#define sk_OSSL_CMP_ITAV_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CMP_ITAV) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_copyfunc_type(copyfunc), ossl_check_OSSL_CMP_ITAV_freefunc_type(freefunc)))
#define sk_OSSL_CMP_ITAV_set_cmp_func(sk, cmp) ((sk_OSSL_CMP_ITAV_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CMP_ITAV_sk_type(sk), ossl_check_OSSL_CMP_ITAV_compfunc_type(cmp)))

/* clang-format on */
/**
 * @brief RevRepContent from RFC 4210 section 5.3.4: status for each certReqId in an RR.
 */
typedef struct ossl_cmp_revrepcontent_st OSSL_CMP_REVREPCONTENT;
/**
 * @brief Opaque PKIStatusInfo structure with status, statusString, and failInfo (RFC 4210 section 5.3.14).
 */
typedef struct ossl_cmp_pkisi_st OSSL_CMP_PKISI;
/**
 * @brief Allocate an empty OSSL_CMP_PKISI structure.
 * @return New OSSL_CMP_PKISI, or NULL on allocation failure.
 */
OSSL_CMP_PKISI *OSSL_CMP_PKISI_new(void);
/**
 * @brief Free an OSSL_CMP_PKISI structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CMP_PKISI_free(OSSL_CMP_PKISI *a);
/**
 * @brief Decode an OSSL_CMP_PKISI from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CMP_PKISI, or NULL on error.
 */
OSSL_CMP_PKISI *d2i_OSSL_CMP_PKISI(OSSL_CMP_PKISI **a, const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CMP_PKISI to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CMP_PKISI(const OSSL_CMP_PKISI *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CMP_PKISI.
 * @return Pointer to the static ASN1_ITEM for OSSL_CMP_PKISI.
 */
const ASN1_ITEM *OSSL_CMP_PKISI_it(void);
/**
 * @brief Duplicate an OSSL_CMP_PKISI structure.
 * @param a Value to duplicate.
 * @return Copy of @p a, or NULL on error.
 */
OSSL_CMP_PKISI *OSSL_CMP_PKISI_dup(const OSSL_CMP_PKISI *a);
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CMP_PKISI, OSSL_CMP_PKISI, OSSL_CMP_PKISI)
#define sk_OSSL_CMP_PKISI_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CMP_PKISI_sk_type(sk))
#define sk_OSSL_CMP_PKISI_value(sk, idx) ((OSSL_CMP_PKISI *)OPENSSL_sk_value(ossl_check_const_OSSL_CMP_PKISI_sk_type(sk), (idx)))
#define sk_OSSL_CMP_PKISI_new(cmp) ((STACK_OF(OSSL_CMP_PKISI) *)OPENSSL_sk_new(ossl_check_OSSL_CMP_PKISI_compfunc_type(cmp)))
#define sk_OSSL_CMP_PKISI_new_null() ((STACK_OF(OSSL_CMP_PKISI) *)OPENSSL_sk_new_null())
#define sk_OSSL_CMP_PKISI_new_reserve(cmp, n) ((STACK_OF(OSSL_CMP_PKISI) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CMP_PKISI_compfunc_type(cmp), (n)))
#define sk_OSSL_CMP_PKISI_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CMP_PKISI_sk_type(sk), (n))
#define sk_OSSL_CMP_PKISI_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CMP_PKISI_sk_type(sk))
#define sk_OSSL_CMP_PKISI_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CMP_PKISI_sk_type(sk))
#define sk_OSSL_CMP_PKISI_delete(sk, i) ((OSSL_CMP_PKISI *)OPENSSL_sk_delete(ossl_check_OSSL_CMP_PKISI_sk_type(sk), (i)))
#define sk_OSSL_CMP_PKISI_delete_ptr(sk, ptr) ((OSSL_CMP_PKISI *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr)))
#define sk_OSSL_CMP_PKISI_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr))
#define sk_OSSL_CMP_PKISI_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr))
#define sk_OSSL_CMP_PKISI_pop(sk) ((OSSL_CMP_PKISI *)OPENSSL_sk_pop(ossl_check_OSSL_CMP_PKISI_sk_type(sk)))
#define sk_OSSL_CMP_PKISI_shift(sk) ((OSSL_CMP_PKISI *)OPENSSL_sk_shift(ossl_check_OSSL_CMP_PKISI_sk_type(sk)))
#define sk_OSSL_CMP_PKISI_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CMP_PKISI_sk_type(sk),ossl_check_OSSL_CMP_PKISI_freefunc_type(freefunc))
#define sk_OSSL_CMP_PKISI_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr), (idx))
#define sk_OSSL_CMP_PKISI_set(sk, idx, ptr) ((OSSL_CMP_PKISI *)OPENSSL_sk_set(ossl_check_OSSL_CMP_PKISI_sk_type(sk), (idx), ossl_check_OSSL_CMP_PKISI_type(ptr)))
#define sk_OSSL_CMP_PKISI_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr))
#define sk_OSSL_CMP_PKISI_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr))
#define sk_OSSL_CMP_PKISI_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_type(ptr), pnum)
#define sk_OSSL_CMP_PKISI_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CMP_PKISI_sk_type(sk))
#define sk_OSSL_CMP_PKISI_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CMP_PKISI_sk_type(sk))
#define sk_OSSL_CMP_PKISI_dup(sk) ((STACK_OF(OSSL_CMP_PKISI) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CMP_PKISI_sk_type(sk)))
#define sk_OSSL_CMP_PKISI_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CMP_PKISI) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_copyfunc_type(copyfunc), ossl_check_OSSL_CMP_PKISI_freefunc_type(freefunc)))
#define sk_OSSL_CMP_PKISI_set_cmp_func(sk, cmp) ((sk_OSSL_CMP_PKISI_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CMP_PKISI_sk_type(sk), ossl_check_OSSL_CMP_PKISI_compfunc_type(cmp)))

/* clang-format on */
/**
 * @brief CertRepMessage from RFC 4210 section 5.3.3: CA Pubs and certResponse sequence.
 */
typedef struct ossl_cmp_certrepmessage_st OSSL_CMP_CERTREPMESSAGE;
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CMP_CERTREPMESSAGE, OSSL_CMP_CERTREPMESSAGE, OSSL_CMP_CERTREPMESSAGE)
#define sk_OSSL_CMP_CERTREPMESSAGE_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CMP_CERTREPMESSAGE_sk_type(sk))
#define sk_OSSL_CMP_CERTREPMESSAGE_value(sk, idx) ((OSSL_CMP_CERTREPMESSAGE *)OPENSSL_sk_value(ossl_check_const_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), (idx)))
#define sk_OSSL_CMP_CERTREPMESSAGE_new(cmp) ((STACK_OF(OSSL_CMP_CERTREPMESSAGE) *)OPENSSL_sk_new(ossl_check_OSSL_CMP_CERTREPMESSAGE_compfunc_type(cmp)))
#define sk_OSSL_CMP_CERTREPMESSAGE_new_null() ((STACK_OF(OSSL_CMP_CERTREPMESSAGE) *)OPENSSL_sk_new_null())
#define sk_OSSL_CMP_CERTREPMESSAGE_new_reserve(cmp, n) ((STACK_OF(OSSL_CMP_CERTREPMESSAGE) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CMP_CERTREPMESSAGE_compfunc_type(cmp), (n)))
#define sk_OSSL_CMP_CERTREPMESSAGE_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), (n))
#define sk_OSSL_CMP_CERTREPMESSAGE_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk))
#define sk_OSSL_CMP_CERTREPMESSAGE_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk))
#define sk_OSSL_CMP_CERTREPMESSAGE_delete(sk, i) ((OSSL_CMP_CERTREPMESSAGE *)OPENSSL_sk_delete(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), (i)))
#define sk_OSSL_CMP_CERTREPMESSAGE_delete_ptr(sk, ptr) ((OSSL_CMP_CERTREPMESSAGE *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr)))
#define sk_OSSL_CMP_CERTREPMESSAGE_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr))
#define sk_OSSL_CMP_CERTREPMESSAGE_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr))
#define sk_OSSL_CMP_CERTREPMESSAGE_pop(sk) ((OSSL_CMP_CERTREPMESSAGE *)OPENSSL_sk_pop(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk)))
#define sk_OSSL_CMP_CERTREPMESSAGE_shift(sk) ((OSSL_CMP_CERTREPMESSAGE *)OPENSSL_sk_shift(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk)))
#define sk_OSSL_CMP_CERTREPMESSAGE_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk),ossl_check_OSSL_CMP_CERTREPMESSAGE_freefunc_type(freefunc))
#define sk_OSSL_CMP_CERTREPMESSAGE_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr), (idx))
#define sk_OSSL_CMP_CERTREPMESSAGE_set(sk, idx, ptr) ((OSSL_CMP_CERTREPMESSAGE *)OPENSSL_sk_set(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), (idx), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr)))
#define sk_OSSL_CMP_CERTREPMESSAGE_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr))
#define sk_OSSL_CMP_CERTREPMESSAGE_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr))
#define sk_OSSL_CMP_CERTREPMESSAGE_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_type(ptr), pnum)
#define sk_OSSL_CMP_CERTREPMESSAGE_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk))
#define sk_OSSL_CMP_CERTREPMESSAGE_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CMP_CERTREPMESSAGE_sk_type(sk))
#define sk_OSSL_CMP_CERTREPMESSAGE_dup(sk) ((STACK_OF(OSSL_CMP_CERTREPMESSAGE) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CMP_CERTREPMESSAGE_sk_type(sk)))
#define sk_OSSL_CMP_CERTREPMESSAGE_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CMP_CERTREPMESSAGE) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_copyfunc_type(copyfunc), ossl_check_OSSL_CMP_CERTREPMESSAGE_freefunc_type(freefunc)))
#define sk_OSSL_CMP_CERTREPMESSAGE_set_cmp_func(sk, cmp) ((sk_OSSL_CMP_CERTREPMESSAGE_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CMP_CERTREPMESSAGE_sk_type(sk), ossl_check_OSSL_CMP_CERTREPMESSAGE_compfunc_type(cmp)))

/* clang-format on */
/**
 * @brief Opaque PollRepContent entry with certReqId, checkAfter, and optional reason (RFC 4210 section 5.3.22).
 */
typedef struct ossl_cmp_pollrep_st OSSL_CMP_POLLREP;
/**
 * @brief STACK_OF(OSSL_CMP_POLLREP) representing a PollRepContent sequence.
 */
typedef STACK_OF(OSSL_CMP_POLLREP) OSSL_CMP_POLLREPCONTENT;
/**
 * @brief CertResponse from RFC 4210 section 5.3.3: certReqId, status, and optional cert/key.
 */
typedef struct ossl_cmp_certresponse_st OSSL_CMP_CERTRESPONSE;
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CMP_CERTRESPONSE, OSSL_CMP_CERTRESPONSE, OSSL_CMP_CERTRESPONSE)
#define sk_OSSL_CMP_CERTRESPONSE_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CMP_CERTRESPONSE_sk_type(sk))
#define sk_OSSL_CMP_CERTRESPONSE_value(sk, idx) ((OSSL_CMP_CERTRESPONSE *)OPENSSL_sk_value(ossl_check_const_OSSL_CMP_CERTRESPONSE_sk_type(sk), (idx)))
#define sk_OSSL_CMP_CERTRESPONSE_new(cmp) ((STACK_OF(OSSL_CMP_CERTRESPONSE) *)OPENSSL_sk_new(ossl_check_OSSL_CMP_CERTRESPONSE_compfunc_type(cmp)))
#define sk_OSSL_CMP_CERTRESPONSE_new_null() ((STACK_OF(OSSL_CMP_CERTRESPONSE) *)OPENSSL_sk_new_null())
#define sk_OSSL_CMP_CERTRESPONSE_new_reserve(cmp, n) ((STACK_OF(OSSL_CMP_CERTRESPONSE) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CMP_CERTRESPONSE_compfunc_type(cmp), (n)))
#define sk_OSSL_CMP_CERTRESPONSE_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), (n))
#define sk_OSSL_CMP_CERTRESPONSE_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk))
#define sk_OSSL_CMP_CERTRESPONSE_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk))
#define sk_OSSL_CMP_CERTRESPONSE_delete(sk, i) ((OSSL_CMP_CERTRESPONSE *)OPENSSL_sk_delete(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), (i)))
#define sk_OSSL_CMP_CERTRESPONSE_delete_ptr(sk, ptr) ((OSSL_CMP_CERTRESPONSE *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr)))
#define sk_OSSL_CMP_CERTRESPONSE_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr))
#define sk_OSSL_CMP_CERTRESPONSE_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr))
#define sk_OSSL_CMP_CERTRESPONSE_pop(sk) ((OSSL_CMP_CERTRESPONSE *)OPENSSL_sk_pop(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk)))
#define sk_OSSL_CMP_CERTRESPONSE_shift(sk) ((OSSL_CMP_CERTRESPONSE *)OPENSSL_sk_shift(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk)))
#define sk_OSSL_CMP_CERTRESPONSE_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk),ossl_check_OSSL_CMP_CERTRESPONSE_freefunc_type(freefunc))
#define sk_OSSL_CMP_CERTRESPONSE_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr), (idx))
#define sk_OSSL_CMP_CERTRESPONSE_set(sk, idx, ptr) ((OSSL_CMP_CERTRESPONSE *)OPENSSL_sk_set(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), (idx), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr)))
#define sk_OSSL_CMP_CERTRESPONSE_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr))
#define sk_OSSL_CMP_CERTRESPONSE_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr))
#define sk_OSSL_CMP_CERTRESPONSE_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_type(ptr), pnum)
#define sk_OSSL_CMP_CERTRESPONSE_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk))
#define sk_OSSL_CMP_CERTRESPONSE_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CMP_CERTRESPONSE_sk_type(sk))
#define sk_OSSL_CMP_CERTRESPONSE_dup(sk) ((STACK_OF(OSSL_CMP_CERTRESPONSE) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CMP_CERTRESPONSE_sk_type(sk)))
#define sk_OSSL_CMP_CERTRESPONSE_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CMP_CERTRESPONSE) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_copyfunc_type(copyfunc), ossl_check_OSSL_CMP_CERTRESPONSE_freefunc_type(freefunc)))
#define sk_OSSL_CMP_CERTRESPONSE_set_cmp_func(sk, cmp) ((sk_OSSL_CMP_CERTRESPONSE_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CMP_CERTRESPONSE_sk_type(sk), ossl_check_OSSL_CMP_CERTRESPONSE_compfunc_type(cmp)))

/* clang-format on */
/**
 * @brief Sequence of UTF8String status or error detail text in PKIStatusInfo (RFC 4210).
 */
typedef STACK_OF(ASN1_UTF8STRING) OSSL_CMP_PKIFREETEXT;

/*
 * function DECLARATIONS
 */

/* from cmp_asn.c */
/**
 * @brief Allocate an ITAV with the given infoType and infoValue, taking ownership of both.
 * @param type infoType OID; ownership transfers to the ITAV.
 * @param value infoValue as a generic ASN1_TYPE; ownership transfers to the ITAV.
 * @return New ITAV on success, or NULL on error.
 */
OSSL_CMP_ITAV *OSSL_CMP_ITAV_create(ASN1_OBJECT *type, ASN1_TYPE *value);
/**
 * @brief Set the infoType and infoValue of an ITAV, taking ownership of both pointers.
 * @param itav ITAV to update.
 * @param type infoType OID; ownership transfers to @p itav.
 * @param value infoValue as a generic ASN1_TYPE; ownership transfers to @p itav.
 */
void OSSL_CMP_ITAV_set0(OSSL_CMP_ITAV *itav, ASN1_OBJECT *type,
    ASN1_TYPE *value);
/**
 * @brief Return the infoType OID from an ITAV.
 * @param itav ITAV to query.
 * @return Internal infoType pointer, or NULL if unavailable.
 */
ASN1_OBJECT *OSSL_CMP_ITAV_get0_type(const OSSL_CMP_ITAV *itav);
/**
 * @brief Return the infoValue from an ITAV.
 * @param itav ITAV to query.
 * @return Internal infoValue pointer, or NULL if unavailable.
 */
ASN1_TYPE *OSSL_CMP_ITAV_get0_value(const OSSL_CMP_ITAV *itav);
/**
 * @brief Push an ITAV onto a stack, creating the stack if *@p itav_sk_p is NULL.
 * @param itav_sk_p Address of the destination stack pointer.
 * @param itav ITAV to push; ownership transfers to the stack.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_ITAV_push0_stack_item(STACK_OF(OSSL_CMP_ITAV) **itav_sk_p,
    OSSL_CMP_ITAV *itav);
/**
 * @brief Free an OSSL_CMP_ITAV structure and its infoType and infoValue contents.
 * @param itav Value to free, or NULL.
 */
void OSSL_CMP_ITAV_free(OSSL_CMP_ITAV *itav);

/**
 * @brief Create a certProfile ITAV from a stack of profile name strings.
 * @param certProfile Profile names to include; ownership transfers to the ITAV.
 * @return New ITAV on success, or NULL on error.
 */
OSSL_CMP_ITAV *OSSL_CMP_ITAV_new0_certProfile(STACK_OF(ASN1_UTF8STRING)
        *certProfile);
/**
 * @brief Extract the certProfile name list from a certProfile ITAV.
 * @param itav ITAV with infoType certProfile.
 * @param out Address of a pointer set to the internal profile-name stack, or NULL if none.
 * @return 1 on success, 0 if @p itav is not a certProfile ITAV or on error.
 */
int OSSL_CMP_ITAV_get0_certProfile(const OSSL_CMP_ITAV *itav,
    STACK_OF(ASN1_UTF8STRING) **out);
/**
 * @brief Create a caCerts ITAV containing a copy of the given CA certificate stack.
 * @param caCerts CA certificates to embed in the ITAV.
 * @return New ITAV on success, or NULL on error.
 */
OSSL_CMP_ITAV *OSSL_CMP_ITAV_new_caCerts(const STACK_OF(X509) *caCerts);
/**
 * @brief Extract the CA certificate stack from a caCerts ITAV.
 * @param itav ITAV with infoType caCerts.
 * @param out Address of a pointer set to the internal certificate stack, or NULL if none.
 * @return 1 on success, 0 if @p itav is not a caCerts ITAV or on error.
 */
int OSSL_CMP_ITAV_get0_caCerts(const OSSL_CMP_ITAV *itav, STACK_OF(X509) **out);

/**
 * @brief Create a rootCaCert ITAV optionally containing a root CA certificate.
 * @param rootCaCert Root CA certificate to include, or NULL for an empty ITAV.
 * @return New ITAV on success, or NULL on error.
 */
OSSL_CMP_ITAV *OSSL_CMP_ITAV_new_rootCaCert(const X509 *rootCaCert);
/**
 * @brief Extract the root CA certificate from a rootCaCert ITAV.
 * @param itav ITAV with infoType rootCaCert.
 * @param out Receives the internal certificate pointer, or NULL if absent.
 * @return 1 on success, 0 if @p itav is not a rootCaCert ITAV or on error.
 */
int OSSL_CMP_ITAV_get0_rootCaCert(const OSSL_CMP_ITAV *itav, X509 **out);
/**
 * @brief Create a rootCaKeyUpdate ITAV with optional transition certificates.
 * @param newWithNew New root CA certificate signed with the new key, or NULL.
 * @param newWithOld New root CA certificate signed with the old key, or NULL.
 * @param oldWithNew Old root CA certificate signed with the new key, or NULL.
 * @return New ITAV on success, or NULL on error.
 */
OSSL_CMP_ITAV *OSSL_CMP_ITAV_new_rootCaKeyUpdate(const X509 *newWithNew,
    const X509 *newWithOld,
    const X509 *oldWithNew);
/**
 * @brief Extract root CA key-update certificates from a rootCaKeyUpdate ITAV.
 * @param itav ITAV with infoType rootCaKeyUpdate.
 * @param newWithNew Receives the newWithNew certificate pointer, or NULL if absent.
 * @param newWithOld Receives the newWithOld certificate pointer if non-NULL, or NULL if absent.
 * @param oldWithNew Receives the oldWithNew certificate pointer if non-NULL, or NULL if absent.
 * @return 1 on success, 0 if @p itav is not a rootCaKeyUpdate ITAV or on error.
 */
int OSSL_CMP_ITAV_get0_rootCaKeyUpdate(const OSSL_CMP_ITAV *itav,
    X509 **newWithNew,
    X509 **newWithOld,
    X509 **oldWithNew);

/**
 * @brief Free an OSSL_CMP_MSG structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CMP_MSG_free(OSSL_CMP_MSG *a);

/* from cmp_ctx.c */
/**
 * @brief Allocate a CMP context with default options for client or server use.
 * @param libctx Library context, or NULL for the default.
 * @param propq Property query string for algorithm fetching, or NULL.
 * @return New OSSL_CMP_CTX, or NULL on allocation failure.
 */
OSSL_CMP_CTX *OSSL_CMP_CTX_new(OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Free a CMP context and all resources it owns.
 * @param ctx Context to free, or NULL.
 */
void OSSL_CMP_CTX_free(OSSL_CMP_CTX *ctx);
/**
 * @brief Reset a CMP context to its initial state while retaining configuration.
 * @param ctx CMP context to reinitialize.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_reinit(OSSL_CMP_CTX *ctx);
/**
 * @brief Return the library context associated with a CMP context.
 * @param ctx CMP context.
 * @return Library context pointer, or NULL if unset.
 */
OSSL_LIB_CTX *OSSL_CMP_CTX_get0_libctx(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return the property query string used for algorithm fetching.
 * @param ctx CMP context.
 * @return Property query string, or NULL if unset.
 */
const char *OSSL_CMP_CTX_get0_propq(const OSSL_CMP_CTX *ctx);
/* CMP general options: */
#define OSSL_CMP_OPT_LOG_VERBOSITY 0
/* CMP transfer options: */
#define OSSL_CMP_OPT_KEEP_ALIVE 10
#define OSSL_CMP_OPT_MSG_TIMEOUT 11
#define OSSL_CMP_OPT_TOTAL_TIMEOUT 12
#define OSSL_CMP_OPT_USE_TLS 13
/* CMP request options: */
#define OSSL_CMP_OPT_VALIDITY_DAYS 20
#define OSSL_CMP_OPT_SUBJECTALTNAME_NODEFAULT 21
#define OSSL_CMP_OPT_SUBJECTALTNAME_CRITICAL 22
#define OSSL_CMP_OPT_POLICIES_CRITICAL 23
#define OSSL_CMP_OPT_POPO_METHOD 24
#define OSSL_CMP_OPT_IMPLICIT_CONFIRM 25
#define OSSL_CMP_OPT_DISABLE_CONFIRM 26
#define OSSL_CMP_OPT_REVOCATION_REASON 27
/* CMP protection options: */
#define OSSL_CMP_OPT_UNPROTECTED_SEND 30
#define OSSL_CMP_OPT_UNPROTECTED_ERRORS 31
#define OSSL_CMP_OPT_OWF_ALGNID 32
#define OSSL_CMP_OPT_MAC_ALGNID 33
#define OSSL_CMP_OPT_DIGEST_ALGNID 34
#define OSSL_CMP_OPT_IGNORE_KEYUSAGE 35
#define OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR 36
#define OSSL_CMP_OPT_NO_CACHE_EXTRACERTS 37
/**
 * @brief Set a CMP context option (OSSL_CMP_OPT_*).
 * @param ctx CMP context.
 * @param opt Option identifier.
 * @param val Option value.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_option(OSSL_CMP_CTX *ctx, int opt, int val);
/**
 * @brief Read a CMP context option (OSSL_CMP_OPT_*).
 * @param ctx CMP context.
 * @param opt Option identifier.
 * @return Current option value, or -1 on error.
 */
int OSSL_CMP_CTX_get_option(const OSSL_CMP_CTX *ctx, int opt);
/* CMP-specific callback for logging and outputting the error queue: */
/**
 * @brief Register a CMP logging callback for this context.
 * @param ctx CMP context.
 * @param cb Callback invoked for CMP log messages, or NULL for the default logger.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_log_cb(OSSL_CMP_CTX *ctx, OSSL_CMP_log_cb_t cb);
#define OSSL_CMP_CTX_set_log_verbosity(ctx, level) \
    OSSL_CMP_CTX_set_option(ctx, OSSL_CMP_OPT_LOG_VERBOSITY, level)
/**
 * @brief Print the OpenSSL error queue using the context logging callback.
 * @param ctx CMP context whose log callback receives error-queue entries.
 */
void OSSL_CMP_CTX_print_errors(const OSSL_CMP_CTX *ctx);
/* message transfer: */
/**
 * @brief Set the HTTP path component for CMP server requests.
 * @param ctx CMP context.
 * @param path URL path (for example "/cmp"), or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_serverPath(OSSL_CMP_CTX *ctx, const char *path);
/**
 * @brief Set the CMP server hostname or IP address used for HTTP(S) transfer.
 * @param ctx CMP context.
 * @param address Server hostname, IP address, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_server(OSSL_CMP_CTX *ctx, const char *address);
/**
 * @brief Set the TCP port used for CMP HTTP(S) transfer.
 * @param ctx CMP context.
 * @param port Server port number.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_serverPort(OSSL_CMP_CTX *ctx, int port);
/**
 * @brief Set an HTTP proxy hostname for CMP transfer.
 * @param ctx CMP context.
 * @param name Proxy hostname or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_proxy(OSSL_CMP_CTX *ctx, const char *name);
/**
 * @brief Set a comma-separated list of hosts that bypass the HTTP proxy.
 * @param ctx CMP context.
 * @param names Host list in no-proxy format, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_no_proxy(OSSL_CMP_CTX *ctx, const char *names);
#ifndef OPENSSL_NO_HTTP
/**
 * @brief Set the HTTP BIO callback used for CMP message transfer.
 * @param ctx CMP context.
 * @param cb HTTP callback that performs the request/response exchange.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_http_cb(OSSL_CMP_CTX *ctx, OSSL_HTTP_bio_cb_t cb);
/**
 * @brief Set the opaque argument passed to the HTTP transfer callback.
 * @param ctx CMP context.
 * @param arg Callback argument pointer.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_http_cb_arg(OSSL_CMP_CTX *ctx, void *arg);
/**
 * @brief Return the argument previously set for the HTTP transfer callback.
 * @param ctx CMP context.
 * @return HTTP callback argument, or NULL if unset.
 */
void *OSSL_CMP_CTX_get_http_cb_arg(const OSSL_CMP_CTX *ctx);
#endif
/**
 * @brief Callback type for sending a CMP request and returning the response message.
 * @param ctx CMP context with transfer settings.
 * @param req Outgoing CMP request message.
 * @return Server response message on success, or NULL on error.
 */
typedef OSSL_CMP_MSG *(*OSSL_CMP_transfer_cb_t)(OSSL_CMP_CTX *ctx,
    const OSSL_CMP_MSG *req);
/**
 * @brief Replace the message transfer callback used by the CMP client.
 * @param ctx CMP context.
 * @param cb Transfer callback, or NULL to restore the default HTTP transfer.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_transfer_cb(OSSL_CMP_CTX *ctx, OSSL_CMP_transfer_cb_t cb);
/**
 * @brief Set the opaque argument passed to the message transfer callback.
 * @param ctx CMP context.
 * @param arg Callback argument pointer.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_transfer_cb_arg(OSSL_CMP_CTX *ctx, void *arg);
/**
 * @brief Return the argument previously set for the message transfer callback.
 * @param ctx CMP context.
 * @return Transfer-callback argument, or NULL if unset.
 */
void *OSSL_CMP_CTX_get_transfer_cb_arg(const OSSL_CMP_CTX *ctx);
/* server authentication: */
/**
 * @brief Pin the expected CMP server certificate for response verification.
 * @param ctx CMP context.
 * @param cert Server certificate to trust directly, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_srvCert(OSSL_CMP_CTX *ctx, X509 *cert);
/**
 * @brief Pin the expected sender DN for incoming CMP response verification.
 * @param ctx CMP context.
 * @param name Expected sender X509_NAME, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_expected_sender(OSSL_CMP_CTX *ctx, const X509_NAME *name);
/**
 * @brief Set the trusted certificate store used to authenticate the CMP server.
 * @param ctx CMP context.
 * @param store X509_STORE of trust anchors and optional CRLs, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set0_trustedStore(OSSL_CMP_CTX *ctx, X509_STORE *store);
#define OSSL_CMP_CTX_set0_trusted OSSL_CMP_CTX_set0_trustedStore
/**
 * @brief Return the trusted certificate store used to authenticate the CMP server.
 * @param ctx CMP context.
 * @return Internal X509_STORE pointer owned by @p ctx, or NULL if unset.
 */
X509_STORE *OSSL_CMP_CTX_get0_trustedStore(const OSSL_CMP_CTX *ctx);
#define OSSL_CMP_CTX_get0_trusted OSSL_CMP_CTX_get0_trustedStore
/**
 * @brief Set untrusted certificates used when validating CMP server messages.
 * @param ctx CMP context.
 * @param certs Intermediate certificate stack, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_untrusted(OSSL_CMP_CTX *ctx, STACK_OF(X509) *certs);
/**
 * @brief Return the untrusted certificate stack configured on the context.
 * @param ctx CMP context.
 * @return Internal untrusted stack, or NULL if unset.
 */
STACK_OF(X509) *OSSL_CMP_CTX_get0_untrusted(const OSSL_CMP_CTX *ctx);
/* client authentication: */
/**
 * @brief Set the client CMP signer certificate on the context.
 * @param ctx CMP context.
 * @param cert Client certificate used to protect outgoing messages, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_cert(OSSL_CMP_CTX *ctx, X509 *cert);
/**
 * @brief Build and store a certificate chain for the CMP signer certificate.
 * @param ctx CMP context.
 * @param own_trusted Optional trust store for chain validation, or NULL to ignore verification errors.
 * @param candidates Optional intermediate certificates to augment the untrusted set.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_build_cert_chain(OSSL_CMP_CTX *ctx, X509_STORE *own_trusted,
    STACK_OF(X509) *candidates);
/**
 * @brief Set the private key used to protect outgoing CMP messages.
 * @param ctx CMP context.
 * @param pkey Private key matching the client certificate, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_pkey(OSSL_CMP_CTX *ctx, EVP_PKEY *pkey);
/**
 * @brief Set the reference value used for password-based CMP message protection.
 * @param ctx CMP context.
 * @param ref Reference octets copied into the context.
 * @param len Length of @p ref in bytes.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_referenceValue(OSSL_CMP_CTX *ctx,
    const unsigned char *ref, int len);
/**
 * @brief Set the shared secret used for MAC-based CMP message protection.
 * @param ctx CMP context.
 * @param sec Secret octets copied into the context.
 * @param len Length of @p sec in bytes.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_secretValue(OSSL_CMP_CTX *ctx,
    const unsigned char *sec, int len);
/* CMP message header and extra certificates: */
/**
 * @brief Set the intended recipient DN placed in outgoing CMP PKIHeader fields.
 * @param ctx CMP context.
 * @param name Recipient X509_NAME, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_recipient(OSSL_CMP_CTX *ctx, const X509_NAME *name);
/**
 * @brief Append an ITAV to the geninfo field of outgoing CMP messages.
 * @param ctx CMP context.
 * @param itav ITAV to push; ownership transfers to the context.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_push0_geninfo_ITAV(OSSL_CMP_CTX *ctx, OSSL_CMP_ITAV *itav);
/**
 * @brief Clear all geninfo ITAVs stored on the CMP context.
 * @param ctx CMP context.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_reset_geninfo_ITAVs(OSSL_CMP_CTX *ctx);
/**
 * @brief Return the geninfo ITAV stack configured on the context.
 * @param ctx CMP context.
 * @return Internal ITAV stack, or NULL if empty or unset.
 */
STACK_OF(OSSL_CMP_ITAV)
*OSSL_CMP_CTX_get0_geninfo_ITAVs(const OSSL_CMP_CTX *ctx);
/**
 * @brief Set extra certificates sent in outgoing CMP messages.
 * @param ctx CMP context.
 * @param extraCertsOut Certificate stack to send, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_extraCertsOut(OSSL_CMP_CTX *ctx,
    STACK_OF(X509) *extraCertsOut);
/* certificate template: */
/**
 * @brief Set the new key pair used in certificate-request templates.
 * @param ctx CMP context.
 * @param priv Non-zero to store the private key, zero for the public key only.
 * @param pkey Key to install; ownership transfers to the context.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set0_newPkey(OSSL_CMP_CTX *ctx, int priv, EVP_PKEY *pkey);
/**
 * @brief Return the new public or private key stored on the context.
 * @param ctx CMP context.
 * @param priv Non-zero to return the private key, zero for the public key.
 * @return Internal key pointer, or NULL if unset.
 */
EVP_PKEY *OSSL_CMP_CTX_get0_newPkey(const OSSL_CMP_CTX *ctx, int priv);
/**
 * @brief Set the intended issuer DN for the certificate template.
 * @param ctx CMP context.
 * @param name Issuer X509_NAME, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_issuer(OSSL_CMP_CTX *ctx, const X509_NAME *name);
/**
 * @brief Set the serial number field in the certificate template.
 * @param ctx CMP context.
 * @param sn Serial number to copy, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_serialNumber(OSSL_CMP_CTX *ctx, const ASN1_INTEGER *sn);
/**
 * @brief Set the subject DN in the certificate template.
 * @param ctx CMP context.
 * @param name Subject X509_NAME to copy, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_subjectName(OSSL_CMP_CTX *ctx, const X509_NAME *name);
/**
 * @brief Append a Subject Alternative Name to the certificate template.
 * @param ctx CMP context.
 * @param name GeneralName copied into the template SAN extension.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_push1_subjectAltName(OSSL_CMP_CTX *ctx,
    const GENERAL_NAME *name);
/**
 * @brief Replace request extensions in the certificate template.
 * @param ctx CMP context.
 * @param exts Extensions stack; ownership transfers to the context.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set0_reqExtensions(OSSL_CMP_CTX *ctx, X509_EXTENSIONS *exts);
/**
 * @brief Test whether the context contains a Subject Alternative Name extension.
 * @param ctx CMP context.
 * @return 1 if a SAN extension is present, 0 if not, or -1 on error.
 */
int OSSL_CMP_CTX_reqExtensions_have_SAN(OSSL_CMP_CTX *ctx);
/**
 * @brief Append a certificate policy to the template policy extension.
 * @param ctx CMP context.
 * @param pinfo PolicyInformation to append; ownership transfers to the context.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_push0_policy(OSSL_CMP_CTX *ctx, POLICYINFO *pinfo);
/**
 * @brief Set the old certificate referenced by a key-update request.
 * @param ctx CMP context.
 * @param cert Old certificate to copy into the context, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_oldCert(OSSL_CMP_CTX *ctx, X509 *cert);
/**
 * @brief Set a PKCS#10 CSR used for P10CR certificate requests.
 * @param ctx CMP context.
 * @param csr PKCS#10 request to copy, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_p10CSR(OSSL_CMP_CTX *ctx, const X509_REQ *csr);
/* misc body contents: */
/**
 * @brief Append an ITAV to the body of an outgoing General Message (genm).
 * @param ctx CMP context.
 * @param itav ITAV to push; ownership transfers to the context.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_push0_genm_ITAV(OSSL_CMP_CTX *ctx, OSSL_CMP_ITAV *itav);
/* certificate confirmation: */
/**
 * @brief Callback type for evaluating a newly enrolled certificate before certConf.
 * @param ctx CMP context.
 * @param cert Newly enrolled certificate to inspect.
 * @param fail_info Pre-decision PKIFailureInfo bit field from the library.
 * @param txt Optional output for a detail string on rejection.
 * @return 0 to accept the certificate, or a PKIFailureInfo bit field on rejection.
 */
typedef int (*OSSL_CMP_certConf_cb_t)(OSSL_CMP_CTX *ctx, X509 *cert,
    int fail_info, const char **txt);
/**
 * @brief Default certificate-confirmation callback that validates the new certificate chain.
 * @param ctx CMP context; callback argument should point to a trust store, or be NULL.
 * @param cert Newly enrolled certificate to validate.
 * @param fail_info Pre-decision PKIFailureInfo bit field.
 * @param text Optional output for a detail string on rejection.
 * @return 0 on acceptance, @p fail_info if non-zero, or OSSL_CMP_PKIFAILUREINFO_incorrectData.
 */
int OSSL_CMP_certConf_cb(OSSL_CMP_CTX *ctx, X509 *cert, int fail_info,
    const char **text);
/**
 * @brief Register the certificate-confirmation callback for the CMP client.
 * @param ctx CMP context.
 * @param cb Callback invoked before sending certConf, or NULL for the default.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_certConf_cb(OSSL_CMP_CTX *ctx, OSSL_CMP_certConf_cb_t cb);
/**
 * @brief Set the opaque argument passed to the certConf callback.
 * @param ctx CMP context.
 * @param arg Callback argument pointer.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set_certConf_cb_arg(OSSL_CMP_CTX *ctx, void *arg);
/**
 * @brief Return the argument previously set for the certConf callback.
 * @param ctx CMP context.
 * @return certConf-callback argument, or NULL if unset.
 */
void *OSSL_CMP_CTX_get_certConf_cb_arg(const OSSL_CMP_CTX *ctx);
/* result fetching: */
/**
 * @brief Return the PKIStatus from the last CMP transaction stored on the context.
 * @param ctx CMP context.
 * @return PKIStatus value, or -1 if unavailable.
 */
int OSSL_CMP_CTX_get_status(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return the statusString text from the last CMP transaction.
 * @param ctx CMP context.
 * @return Internal statusString stack, or NULL if absent.
 */
OSSL_CMP_PKIFREETEXT *OSSL_CMP_CTX_get0_statusString(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return the failInfo bit field from the last CMP transaction.
 * @param ctx CMP context.
 * @return failInfo integer, or -1 if unavailable.
 */
int OSSL_CMP_CTX_get_failInfoCode(const OSSL_CMP_CTX *ctx);
#define OSSL_CMP_PKISI_BUFLEN 1024
/**
 * @brief Return the validated CMP server certificate from the last transaction.
 * @param ctx CMP context.
 * @return Server certificate pointer owned by @p ctx, or NULL if unavailable.
 */
X509 *OSSL_CMP_CTX_get0_validatedSrvCert(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return the newly obtained certificate from the last transaction, if any.
 * @param ctx CMP context.
 * @return Pointer to the new certificate owned by @p ctx, or NULL if unavailable.
 */
X509 *OSSL_CMP_CTX_get0_newCert(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return a copy of the newly obtained certificate chain from the last transaction.
 * @param ctx CMP context.
 * @return Newly allocated certificate stack, or NULL if unavailable; caller must free.
 */
STACK_OF(X509) *OSSL_CMP_CTX_get1_newChain(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return a copy of CA certificates (caPubs) from the last certRep.
 * @param ctx CMP context.
 * @return Newly allocated certificate stack, or NULL if unavailable; caller must free.
 */
STACK_OF(X509) *OSSL_CMP_CTX_get1_caPubs(const OSSL_CMP_CTX *ctx);
/**
 * @brief Return a copy of extraCerts received in the last CMP message.
 * @param ctx CMP context.
 * @return Newly allocated certificate stack, or NULL if unavailable; caller must free.
 */
STACK_OF(X509) *OSSL_CMP_CTX_get1_extraCertsIn(const OSSL_CMP_CTX *ctx);
/**
 * @brief Set the transactionID placed in outgoing CMP PKIHeader fields.
 * @param ctx CMP context.
 * @param id Transaction ID octet string to copy, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_transactionID(OSSL_CMP_CTX *ctx,
    const ASN1_OCTET_STRING *id);
/**
 * @brief Set the senderNonce placed in outgoing CMP PKIHeader fields.
 * @param ctx CMP context.
 * @param nonce Sender nonce octet string to copy, or NULL to clear.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_CTX_set1_senderNonce(OSSL_CMP_CTX *ctx,
    const ASN1_OCTET_STRING *nonce);

/* from cmp_status.c */
/**
 * @brief Format the PKIStatusInfo from a CMP context into a human-readable string.
 * @param ctx CMP context.
 * @param buf Destination buffer.
 * @param bufsize Size of @p buf.
 * @return @p buf on success, or NULL on error.
 */
char *OSSL_CMP_CTX_snprint_PKIStatus(const OSSL_CMP_CTX *ctx, char *buf,
    size_t bufsize);
/**
 * @brief Format a PKIStatusInfo structure into a human-readable string.
 * @param statusInfo PKIStatusInfo to format.
 * @param buf Destination buffer.
 * @param bufsize Size of @p buf.
 * @return @p buf on success, or NULL on error.
 */
char *OSSL_CMP_snprint_PKIStatusInfo(const OSSL_CMP_PKISI *statusInfo,
    char *buf, size_t bufsize);
/**
 * @brief Allocate a PKIStatusInfo with status, optional failInfo, and statusString text.
 * @param status PKIStatus value (OSSL_CMP_PKISTATUS_*).
 * @param fail_info PKIFailureInfo bit field, or 0 if none.
 * @param text Optional status detail string copied into statusString, or NULL.
 * @return New PKIStatusInfo, or NULL on error.
 */
OSSL_CMP_PKISI *
OSSL_CMP_STATUSINFO_new(int status, int fail_info, const char *text);

/* from cmp_hdr.c */
/**
 * @brief Return the transactionID from a CMP PKIHeader.
 * @param hdr PKIHeader to query.
 * @return Internal transactionID octet string, or NULL if absent.
 */
ASN1_OCTET_STRING *OSSL_CMP_HDR_get0_transactionID(const OSSL_CMP_PKIHEADER *hdr);
/**
 * @brief Return the recipNonce from a CMP PKIHeader.
 * @param hdr PKIHeader to query.
 * @return Internal recipNonce octet string, or NULL if absent.
 */
ASN1_OCTET_STRING *OSSL_CMP_HDR_get0_recipNonce(const OSSL_CMP_PKIHEADER *hdr);
/**
 * @brief Return the geninfo ITAV stack from a CMP PKIHeader.
 * @param hdr PKIHeader to query.
 * @return Internal ITAV stack, or NULL if absent.
 */
STACK_OF(OSSL_CMP_ITAV)
*OSSL_CMP_HDR_get0_geninfo_ITAVs(const OSSL_CMP_PKIHEADER *hdr);

/* from cmp_msg.c */
/**
 * @brief Return the PKIHeader from a CMP message.
 * @param msg CMP message to query.
 * @return Internal PKIHeader pointer, or NULL on error.
 */
OSSL_CMP_PKIHEADER *OSSL_CMP_MSG_get0_header(const OSSL_CMP_MSG *msg);
/**
 * @brief Return the PKIBody choice id of a CMP message.
 * @param msg CMP message to query.
 * @return Body type (OSSL_CMP_* constant), or -1 on error.
 */
int OSSL_CMP_MSG_get_bodytype(const OSSL_CMP_MSG *msg);
/**
 * @brief Return the public key from the certificate template of a certificate-request message.
 * @param msg CMP certificate-request message (IR, CR, KUR, or similar).
 * @return Public key from the template, or NULL if absent or on error.
 */
X509_PUBKEY *OSSL_CMP_MSG_get0_certreq_publickey(const OSSL_CMP_MSG *msg);
/**
 * @brief Copy the context transactionID into a CMP message header.
 * @param ctx CMP context supplying the transactionID.
 * @param msg Outgoing CMP message whose header is updated.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_MSG_update_transactionID(OSSL_CMP_CTX *ctx, OSSL_CMP_MSG *msg);
/**
 * @brief Copy the context senderNonce into a CMP message recipNonce field.
 * @param ctx CMP context supplying the nonce.
 * @param msg Outgoing CMP message whose header is updated.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_MSG_update_recipNonce(OSSL_CMP_CTX *ctx, OSSL_CMP_MSG *msg);
/**
 * @brief Build a CRMF CertReqMsg from fields stored on the CMP context.
 * @param ctx CMP context with template and POPO settings.
 * @param for_KUR Non-zero when building a Key Update Request message.
 * @param rid Certificate request ID to assign.
 * @return New CRMF message on success, or NULL on error; caller must free.
 */
OSSL_CRMF_MSG *OSSL_CMP_CTX_setup_CRM(OSSL_CMP_CTX *ctx, int for_KUR, int rid);
/**
 * @brief Load a DER-encoded CMP message from a file.
 * @param file Path to the DER file.
 * @param libctx Library context, or NULL for the default.
 * @param propq Property query string, or NULL.
 * @return Parsed OSSL_CMP_MSG, or NULL on error.
 */
OSSL_CMP_MSG *OSSL_CMP_MSG_read(const char *file, OSSL_LIB_CTX *libctx,
    const char *propq);
/**
 * @brief Write a CMP message to a file in DER encoding.
 * @param file Destination file path.
 * @param msg CMP message to write.
 * @return Number of bytes written, or a negative value on error.
 */
int OSSL_CMP_MSG_write(const char *file, const OSSL_CMP_MSG *msg);
/**
 * @brief Decode a DER-encoded CMP message from a BIO.
 * @param bio BIO supplying DER bytes.
 * @param msg Optional destination pointer updated to the result.
 * @return Decoded CMP message, or NULL on error.
 */
OSSL_CMP_MSG *d2i_OSSL_CMP_MSG_bio(BIO *bio, OSSL_CMP_MSG **msg);
/**
 * @brief Encode a CMP message to DER and write it to a BIO.
 * @param bio Destination BIO.
 * @param msg CMP message to encode.
 * @return Number of bytes written, or a negative value on error.
 */
int i2d_OSSL_CMP_MSG_bio(BIO *bio, const OSSL_CMP_MSG *msg);

/* from cmp_vfy.c */
/**
 * @brief Verify protection and header fields of an incoming CMP message.
 * @param ctx CMP context with trust and protection settings.
 * @param msg CMP message to validate.
 * @return 1 if valid, 0 if invalid, or -1 on error.
 */
int OSSL_CMP_validate_msg(OSSL_CMP_CTX *ctx, const OSSL_CMP_MSG *msg);
/**
 * @brief Validate that @p cert chains to a trust anchor in @p trusted_store.
 * @param ctx CMP context (used for untrusted intermediates and callbacks).
 * @param trusted_store Trust store containing acceptable anchors.
 * @param cert Certificate to validate.
 * @return 1 if the path validates, 0 if not, or -1 on error.
 */
int OSSL_CMP_validate_cert_path(const OSSL_CMP_CTX *ctx,
    X509_STORE *trusted_store, X509 *cert);

/* from cmp_http.c */
#ifndef OPENSSL_NO_HTTP
/**
 * @brief Send a CMP request over HTTP(S) to the server configured in @p ctx and return the response.
 * @param ctx CMP context with server address, path, and transfer options.
 * @param req CMP request message to send.
 * @return Server response message on success, or NULL on error.
 */
OSSL_CMP_MSG *OSSL_CMP_MSG_http_perform(OSSL_CMP_CTX *ctx,
    const OSSL_CMP_MSG *req);
#endif

/* from cmp_server.c */
/**
 * @brief Opaque CMP server context holding callbacks and server-side state.
 */
typedef struct ossl_cmp_srv_ctx_st OSSL_CMP_SRV_CTX;
/**
 * @brief Process a CMP request using the callbacks registered in @p srv_ctx.
 * @param srv_ctx CMP server context.
 * @param req Incoming CMP request message.
 * @return Response CMP message on success, or NULL on error.
 */
OSSL_CMP_MSG *OSSL_CMP_SRV_process_request(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req);
/**
 * @brief Process a CMP request locally using the server callbacks on the context.
 * @param client_ctx CMP context configured with server-side callbacks.
 * @param req Incoming CMP request message.
 * @return Response CMP message on success, or NULL on error.
 */
OSSL_CMP_MSG *OSSL_CMP_CTX_server_perform(OSSL_CMP_CTX *client_ctx,
    const OSSL_CMP_MSG *req);
/**
 * @brief Allocate a CMP server context with default options.
 * @param libctx Library context, or NULL for the default.
 * @param propq Property query string for algorithm fetching, or NULL.
 * @return New server context, or NULL on allocation failure.
 */
OSSL_CMP_SRV_CTX *OSSL_CMP_SRV_CTX_new(OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Free a CMP server context and its resources.
 * @param srv_ctx Server context to free, or NULL.
 */
void OSSL_CMP_SRV_CTX_free(OSSL_CMP_SRV_CTX *srv_ctx);
/**
 * @brief Server callback type for processing IR/CR/KUR/P10CR certificate requests.
 * @param srv_ctx CMP server context.
 * @param req Incoming request message.
 * @param certReqId Certificate request ID from the message body.
 * @param crm CRMF CertReqMsg, if present.
 * @param p10cr PKCS#10 request, if present.
 * @param certOut Receives the issued certificate allocated by the callback.
 * @param chainOut Receives an optional chain allocated by the callback.
 * @param caPubs Receives optional caPubs allocated by the callback.
 * @return PKIStatusInfo for the certResponse, allocated by the callback.
 */
typedef OSSL_CMP_PKISI *(*OSSL_CMP_SRV_cert_request_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx, const OSSL_CMP_MSG *req, int certReqId,
    const OSSL_CRMF_MSG *crm, const X509_REQ *p10cr,
    X509 **certOut, STACK_OF(X509) **chainOut, STACK_OF(X509) **caPubs);
/**
 * @brief Server callback type for processing Revocation Request (RR) messages.
 * @param srv_ctx CMP server context.
 * @param req Incoming RR message.
 * @param issuer Issuer name of the certificate to revoke.
 * @param serial Serial number of the certificate to revoke.
 * @return PKIStatusInfo for the revocation response, allocated by the callback.
 */
typedef OSSL_CMP_PKISI *(*OSSL_CMP_SRV_rr_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req,
    const X509_NAME *issuer,
    const ASN1_INTEGER *serial);
/**
 * @brief Callback type for processing CMP General Message (genm) requests on the server.
 * @param srv_ctx CMP server context.
 * @param req Incoming genm request message.
 * @param in ITAVs from the request body.
 * @param out Address of a stack pointer to receive response ITAVs allocated by the callback.
 * @return 1 on success, 0 on error.
 */
typedef int (*OSSL_CMP_SRV_genm_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req,
    const STACK_OF(OSSL_CMP_ITAV) *in,
    STACK_OF(OSSL_CMP_ITAV) **out);
/**
 * @brief Server callback invoked when constructing an error message response.
 * @param srv_ctx CMP server context.
 * @param req Request that triggered the error, if available.
 * @param statusInfo PKIStatusInfo being sent.
 * @param errorCode Optional error code integer from the error message body.
 * @param errDetails Optional free-text error details.
 */
typedef void (*OSSL_CMP_SRV_error_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req,
    const OSSL_CMP_PKISI *statusInfo,
    const ASN1_INTEGER *errorCode,
    const OSSL_CMP_PKIFREETEXT *errDetails);
/**
 * @brief Server callback type for processing incoming certConf messages.
 * @param srv_ctx CMP server context.
 * @param req Incoming certConf message.
 * @param certReqId Certificate request ID from the certStatus entry.
 * @param certHash certHash from the certStatus entry.
 * @param si PKIStatusInfo from the certStatus entry.
 * @return 1 on success, 0 on rejection, or -1 on error.
 */
typedef int (*OSSL_CMP_SRV_certConf_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req,
    int certReqId,
    const ASN1_OCTET_STRING *certHash,
    const OSSL_CMP_PKISI *si);
/**
 * @brief Server callback type for processing pollReq messages.
 * @param srv_ctx CMP server context.
 * @param req Incoming pollReq message.
 * @param certReqId Certificate request ID being polled.
 * @param certReq Receives a pending certRep message when ready, or NULL.
 * @param check_after Receives suggested poll interval in seconds when not ready.
 * @return 1 on success, 0 on error.
 */
typedef int (*OSSL_CMP_SRV_pollReq_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req, int certReqId,
    OSSL_CMP_MSG **certReq,
    int64_t *check_after);
/**
 * @brief Register server-side CMP message processing callbacks.
 * @param srv_ctx Server context to initialize.
 * @param custom_ctx Application pointer returned by OSSL_CMP_SRV_CTX_get0_custom_ctx().
 * @param process_cert_request Callback for certificate requests, or NULL.
 * @param process_rr Callback for revocation requests, or NULL.
 * @param process_genm Callback for general messages, or NULL.
 * @param process_error Callback invoked when sending error messages, or NULL.
 * @param process_certConf Callback for certConf messages, or NULL.
 * @param process_pollReq Callback for pollReq messages, or NULL.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_SRV_CTX_init(OSSL_CMP_SRV_CTX *srv_ctx, void *custom_ctx,
    OSSL_CMP_SRV_cert_request_cb_t process_cert_request,
    OSSL_CMP_SRV_rr_cb_t process_rr,
    OSSL_CMP_SRV_genm_cb_t process_genm,
    OSSL_CMP_SRV_error_cb_t process_error,
    OSSL_CMP_SRV_certConf_cb_t process_certConf,
    OSSL_CMP_SRV_pollReq_cb_t process_pollReq);
/**
 * @brief Callback type for deciding whether to delay delivery of a CMP response.
 * @param srv_ctx CMP server context.
 * @param req Incoming request message for which delivery may be delayed.
 * @return 1 to delay delivery, 0 to respond immediately, or -1 on error.
 */
typedef int (*OSSL_CMP_SRV_delayed_delivery_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const OSSL_CMP_MSG *req);
/**
 * @brief Callback type for cleaning up server state after a transaction completes.
 * @param srv_ctx CMP server context.
 * @param id transactionID of the finished transaction.
 * @return 1 on success, 0 on error.
 */
typedef int (*OSSL_CMP_SRV_clean_transaction_cb_t)(OSSL_CMP_SRV_CTX *srv_ctx,
    const ASN1_OCTET_STRING *id);
/**
 * @brief Register delayed-delivery and transaction-cleanup callbacks on a server context.
 * @param srv_ctx Server context.
 * @param delay Optional callback deciding whether to delay response delivery.
 * @param clean Optional callback invoked when a transaction is finished.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_SRV_CTX_init_trans(OSSL_CMP_SRV_CTX *srv_ctx,
    OSSL_CMP_SRV_delayed_delivery_cb_t delay,
    OSSL_CMP_SRV_clean_transaction_cb_t clean);
/**
 * @brief Return the embedded CMP context from a server context.
 * @param srv_ctx Server context.
 * @return Internal OSSL_CMP_CTX pointer.
 */
OSSL_CMP_CTX *OSSL_CMP_SRV_CTX_get0_cmp_ctx(const OSSL_CMP_SRV_CTX *srv_ctx);
/**
 * @brief Return the application custom context pointer from a server context.
 * @param srv_ctx Server context.
 * @return Pointer supplied to OSSL_CMP_SRV_CTX_init(), or NULL if unset.
 */
void *OSSL_CMP_SRV_CTX_get0_custom_ctx(const OSSL_CMP_SRV_CTX *srv_ctx);
/**
 * @brief Enable sending unprotected CMP error and negative response messages.
 * @param srv_ctx CMP server context.
 * @param val Non-zero to enable, 0 to disable.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_SRV_CTX_set_send_unprotected_errors(OSSL_CMP_SRV_CTX *srv_ctx,
    int val);
/**
 * @brief Enable accepting CMP requests without protection or with invalid protection.
 * @param srv_ctx CMP server context.
 * @param val Non-zero to enable, 0 to disable.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_SRV_CTX_set_accept_unprotected(OSSL_CMP_SRV_CTX *srv_ctx, int val);
/**
 * @brief Enable accepting IR/CR/KUR requests with POPO raVerified.
 * @param srv_ctx CMP server context.
 * @param val Non-zero to enable, 0 to disable.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_SRV_CTX_set_accept_raverified(OSSL_CMP_SRV_CTX *srv_ctx, int val);
/**
 * @brief Enable or disable granting implicitConfirm in certRep messages.
 * @param srv_ctx CMP server context.
 * @param val Non-zero to enable, 0 to disable.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_SRV_CTX_set_grant_implicit_confirm(OSSL_CMP_SRV_CTX *srv_ctx,
    int val);

/* from cmp_client.c */
/**
 * @brief Execute a CMP certificate request transaction (IR/CR/KUR/P10CR).
 * @param ctx CMP client context.
 * @param req_type Body type (OSSL_CMP_IR, OSSL_CMP_CR, OSSL_CMP_KUR, or OSSL_CMP_P10CR).
 * @param crm Optional CRMF message for IR/CR/KUR; NULL to build from context fields.
 * @return Newly enrolled certificate on success, or NULL on error.
 */
X509 *OSSL_CMP_exec_certreq(OSSL_CMP_CTX *ctx, int req_type,
    const OSSL_CRMF_MSG *crm);
#define OSSL_CMP_IR 0
#define OSSL_CMP_CR 2
#define OSSL_CMP_P10CR 4
#define OSSL_CMP_KUR 7
#define OSSL_CMP_GENM 21
#define OSSL_CMP_ERROR 23
#define OSSL_CMP_exec_IR_ses(ctx) \
    OSSL_CMP_exec_certreq(ctx, OSSL_CMP_IR, NULL)
#define OSSL_CMP_exec_CR_ses(ctx) \
    OSSL_CMP_exec_certreq(ctx, OSSL_CMP_CR, NULL)
#define OSSL_CMP_exec_P10CR_ses(ctx) \
    OSSL_CMP_exec_certreq(ctx, OSSL_CMP_P10CR, NULL)
#define OSSL_CMP_exec_KUR_ses(ctx) \
    OSSL_CMP_exec_certreq(ctx, OSSL_CMP_KUR, NULL)
/**
 * @brief Start or continue a deferred CMP certificate request (pollReq flow).
 * @param ctx CMP client context.
 * @param req_type Body type (OSSL_CMP_IR, OSSL_CMP_CR, OSSL_CMP_KUR, or OSSL_CMP_P10CR).
 * @param crm Optional CRMF message for IR/CR/KUR.
 * @param checkAfter Receives server-suggested poll interval when the request is pending.
 * @return 1 if the certificate is ready, 0 if polling should continue, or -1 on error.
 */
int OSSL_CMP_try_certreq(OSSL_CMP_CTX *ctx, int req_type,
    const OSSL_CRMF_MSG *crm, int *checkAfter);
/**
 * @brief Execute a CMP Revocation Request (RR) transaction using context fields.
 * @param ctx CMP client context with oldCert and revocation reason configured.
 * @return 1 on success, 0 on failure, or -1 on error.
 */
int OSSL_CMP_exec_RR_ses(OSSL_CMP_CTX *ctx);
/**
 * @brief Execute a CMP General Message (genm) transaction and return response ITAVs.
 * @param ctx CMP client context with genm ITAVs configured.
 * @return Stack of response ITAVs on success, or NULL on error; caller must free contents.
 */
STACK_OF(OSSL_CMP_ITAV) *OSSL_CMP_exec_GENM_ses(OSSL_CMP_CTX *ctx);

/* from cmp_genm.c */
/**
 * @brief Request CA certificates from the CMP server via genm/genp and verify the response.
 * @param ctx CMP context referencing the CMP server.
 * @param out Receives a newly allocated stack of CA certificates; caller must free.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_get1_caCerts(OSSL_CMP_CTX *ctx, STACK_OF(X509) **out);
/**
 * @brief Request a root CA key update via genm/genp and verify the response.
 * @param ctx CMP context referencing the CMP server.
 * @param oldWithOld Current trusted root CA certificate, or NULL.
 * @param newWithNew Receives the new root CA certificate; caller must free.
 * @param newWithOld Receives the newWithOld transition certificate if non-NULL; caller must free.
 * @param oldWithNew Receives the oldWithNew transition certificate if non-NULL; caller must free.
 * @return 1 on success, 0 on error.
 */
int OSSL_CMP_get1_rootCaKeyUpdate(OSSL_CMP_CTX *ctx,
    const X509 *oldWithOld, X509 **newWithNew,
    X509 **newWithOld, X509 **oldWithNew);

#ifdef __cplusplus
}
#endif
#endif /* !defined(OPENSSL_NO_CMP) */
#endif /* !defined(OPENSSL_CMP_H) */
