/*
 * WARNING: do not edit!
 * Generated by Makefile from include/openssl/cms.h.in
 *
 * Copyright 2008-2022 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

/* clang-format off */

/* clang-format on */

#ifndef OPENSSL_CMS_H
#define OPENSSL_CMS_H
#pragma once

#include <openssl/macros.h>
#ifndef OPENSSL_NO_DEPRECATED_3_0
#define HEADER_CMS_H
#endif

#include <openssl/opensslconf.h>

#ifndef OPENSSL_NO_CMS
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/cmserr.h>
#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Opaque CMS EnvelopedData: recipient infos and encrypted content info.
 */
typedef struct CMS_EnvelopedData_st CMS_EnvelopedData;
/**
 * @brief Top-level Cryptographic Message Syntax (CMS) ContentInfo structure.
 */
typedef struct CMS_ContentInfo_st CMS_ContentInfo;
/**
 * @brief Opaque CMS SignerInfo: per-signer algorithms, sid, signed/unsigned attrs, and signature.
 */
typedef struct CMS_SignerInfo_st CMS_SignerInfo;
/**
 * @brief CMS SignedData content: digest algorithms, content, certificates, CRLs, and signer infos.
 */
typedef struct CMS_SignedData_st CMS_SignedData;
/**
 * @brief One certificate choice in a CMS SignedData certificates set (X.509, attribute, or other).
 */
typedef struct CMS_CertificateChoices CMS_CertificateChoices;
/**
 * @brief One revocation-info choice in a CMS SignedData crls set (CRL or other).
 */
typedef struct CMS_RevocationInfoChoice_st CMS_RevocationInfoChoice;
/**
 * @brief Per-recipient information in a CMS EnvelopedData or AuthEnvelopedData message.
 */
typedef struct CMS_RecipientInfo_st CMS_RecipientInfo;
/**
 * @brief ESS receipt request attribute carried on a CMS SignerInfo.
 */
typedef struct CMS_ReceiptRequest_st CMS_ReceiptRequest;
/**
 * @brief ESS signed receipt content verifying that a signed message was received.
 */
typedef struct CMS_Receipt_st CMS_Receipt;
/**
 * @brief Encrypted key for one recipient in a CMS key-agreement (KARI) RecipientInfo.
 */
typedef struct CMS_RecipientEncryptedKey_st CMS_RecipientEncryptedKey;
/**
 * @brief Optional other-key-attribute identifying material in a CMS KEK RecipientInfo.
 */
typedef struct CMS_OtherKeyAttribute_st CMS_OtherKeyAttribute;

/* clang-format off */
/**
 * @brief Opaque STACK_OF(CMS_SignerInfo) container type.
 */
struct stack_st_CMS_SignerInfo;
SKM_DEFINE_STACK_OF_INTERNAL(CMS_SignerInfo, CMS_SignerInfo, CMS_SignerInfo)
#define sk_CMS_SignerInfo_num(sk) OPENSSL_sk_num(ossl_check_const_CMS_SignerInfo_sk_type(sk))
#define sk_CMS_SignerInfo_value(sk, idx) ((CMS_SignerInfo *)OPENSSL_sk_value(ossl_check_const_CMS_SignerInfo_sk_type(sk), (idx)))
#define sk_CMS_SignerInfo_new(cmp) ((STACK_OF(CMS_SignerInfo) *)OPENSSL_sk_new(ossl_check_CMS_SignerInfo_compfunc_type(cmp)))
#define sk_CMS_SignerInfo_new_null() ((STACK_OF(CMS_SignerInfo) *)OPENSSL_sk_new_null())
#define sk_CMS_SignerInfo_new_reserve(cmp, n) ((STACK_OF(CMS_SignerInfo) *)OPENSSL_sk_new_reserve(ossl_check_CMS_SignerInfo_compfunc_type(cmp), (n)))
#define sk_CMS_SignerInfo_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_CMS_SignerInfo_sk_type(sk), (n))
#define sk_CMS_SignerInfo_free(sk) OPENSSL_sk_free(ossl_check_CMS_SignerInfo_sk_type(sk))
#define sk_CMS_SignerInfo_zero(sk) OPENSSL_sk_zero(ossl_check_CMS_SignerInfo_sk_type(sk))
#define sk_CMS_SignerInfo_delete(sk, i) ((CMS_SignerInfo *)OPENSSL_sk_delete(ossl_check_CMS_SignerInfo_sk_type(sk), (i)))
#define sk_CMS_SignerInfo_delete_ptr(sk, ptr) ((CMS_SignerInfo *)OPENSSL_sk_delete_ptr(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr)))
#define sk_CMS_SignerInfo_push(sk, ptr) OPENSSL_sk_push(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr))
#define sk_CMS_SignerInfo_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr))
#define sk_CMS_SignerInfo_pop(sk) ((CMS_SignerInfo *)OPENSSL_sk_pop(ossl_check_CMS_SignerInfo_sk_type(sk)))
#define sk_CMS_SignerInfo_shift(sk) ((CMS_SignerInfo *)OPENSSL_sk_shift(ossl_check_CMS_SignerInfo_sk_type(sk)))
#define sk_CMS_SignerInfo_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_CMS_SignerInfo_sk_type(sk),ossl_check_CMS_SignerInfo_freefunc_type(freefunc))
#define sk_CMS_SignerInfo_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr), (idx))
#define sk_CMS_SignerInfo_set(sk, idx, ptr) ((CMS_SignerInfo *)OPENSSL_sk_set(ossl_check_CMS_SignerInfo_sk_type(sk), (idx), ossl_check_CMS_SignerInfo_type(ptr)))
#define sk_CMS_SignerInfo_find(sk, ptr) OPENSSL_sk_find(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr))
#define sk_CMS_SignerInfo_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr))
#define sk_CMS_SignerInfo_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_type(ptr), pnum)
#define sk_CMS_SignerInfo_sort(sk) OPENSSL_sk_sort(ossl_check_CMS_SignerInfo_sk_type(sk))
#define sk_CMS_SignerInfo_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_CMS_SignerInfo_sk_type(sk))
#define sk_CMS_SignerInfo_dup(sk) ((STACK_OF(CMS_SignerInfo) *)OPENSSL_sk_dup(ossl_check_const_CMS_SignerInfo_sk_type(sk)))
#define sk_CMS_SignerInfo_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(CMS_SignerInfo) *)OPENSSL_sk_deep_copy(ossl_check_const_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_copyfunc_type(copyfunc), ossl_check_CMS_SignerInfo_freefunc_type(freefunc)))
#define sk_CMS_SignerInfo_set_cmp_func(sk, cmp) ((sk_CMS_SignerInfo_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_CMS_SignerInfo_sk_type(sk), ossl_check_CMS_SignerInfo_compfunc_type(cmp)))

SKM_DEFINE_STACK_OF_INTERNAL(CMS_RecipientEncryptedKey, CMS_RecipientEncryptedKey, CMS_RecipientEncryptedKey)
#define sk_CMS_RecipientEncryptedKey_num(sk) OPENSSL_sk_num(ossl_check_const_CMS_RecipientEncryptedKey_sk_type(sk))
#define sk_CMS_RecipientEncryptedKey_value(sk, idx) ((CMS_RecipientEncryptedKey *)OPENSSL_sk_value(ossl_check_const_CMS_RecipientEncryptedKey_sk_type(sk), (idx)))
#define sk_CMS_RecipientEncryptedKey_new(cmp) ((STACK_OF(CMS_RecipientEncryptedKey) *)OPENSSL_sk_new(ossl_check_CMS_RecipientEncryptedKey_compfunc_type(cmp)))
#define sk_CMS_RecipientEncryptedKey_new_null() ((STACK_OF(CMS_RecipientEncryptedKey) *)OPENSSL_sk_new_null())
#define sk_CMS_RecipientEncryptedKey_new_reserve(cmp, n) ((STACK_OF(CMS_RecipientEncryptedKey) *)OPENSSL_sk_new_reserve(ossl_check_CMS_RecipientEncryptedKey_compfunc_type(cmp), (n)))
#define sk_CMS_RecipientEncryptedKey_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), (n))
#define sk_CMS_RecipientEncryptedKey_free(sk) OPENSSL_sk_free(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk))
#define sk_CMS_RecipientEncryptedKey_zero(sk) OPENSSL_sk_zero(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk))
#define sk_CMS_RecipientEncryptedKey_delete(sk, i) ((CMS_RecipientEncryptedKey *)OPENSSL_sk_delete(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), (i)))
#define sk_CMS_RecipientEncryptedKey_delete_ptr(sk, ptr) ((CMS_RecipientEncryptedKey *)OPENSSL_sk_delete_ptr(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr)))
#define sk_CMS_RecipientEncryptedKey_push(sk, ptr) OPENSSL_sk_push(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr))
#define sk_CMS_RecipientEncryptedKey_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr))
#define sk_CMS_RecipientEncryptedKey_pop(sk) ((CMS_RecipientEncryptedKey *)OPENSSL_sk_pop(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk)))
#define sk_CMS_RecipientEncryptedKey_shift(sk) ((CMS_RecipientEncryptedKey *)OPENSSL_sk_shift(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk)))
#define sk_CMS_RecipientEncryptedKey_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk),ossl_check_CMS_RecipientEncryptedKey_freefunc_type(freefunc))
#define sk_CMS_RecipientEncryptedKey_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr), (idx))
#define sk_CMS_RecipientEncryptedKey_set(sk, idx, ptr) ((CMS_RecipientEncryptedKey *)OPENSSL_sk_set(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), (idx), ossl_check_CMS_RecipientEncryptedKey_type(ptr)))
#define sk_CMS_RecipientEncryptedKey_find(sk, ptr) OPENSSL_sk_find(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr))
#define sk_CMS_RecipientEncryptedKey_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr))
#define sk_CMS_RecipientEncryptedKey_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_type(ptr), pnum)
#define sk_CMS_RecipientEncryptedKey_sort(sk) OPENSSL_sk_sort(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk))
#define sk_CMS_RecipientEncryptedKey_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_CMS_RecipientEncryptedKey_sk_type(sk))
#define sk_CMS_RecipientEncryptedKey_dup(sk) ((STACK_OF(CMS_RecipientEncryptedKey) *)OPENSSL_sk_dup(ossl_check_const_CMS_RecipientEncryptedKey_sk_type(sk)))
#define sk_CMS_RecipientEncryptedKey_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(CMS_RecipientEncryptedKey) *)OPENSSL_sk_deep_copy(ossl_check_const_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_copyfunc_type(copyfunc), ossl_check_CMS_RecipientEncryptedKey_freefunc_type(freefunc)))
#define sk_CMS_RecipientEncryptedKey_set_cmp_func(sk, cmp) ((sk_CMS_RecipientEncryptedKey_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_CMS_RecipientEncryptedKey_sk_type(sk), ossl_check_CMS_RecipientEncryptedKey_compfunc_type(cmp)))
SKM_DEFINE_STACK_OF_INTERNAL(CMS_RecipientInfo, CMS_RecipientInfo, CMS_RecipientInfo)
#define sk_CMS_RecipientInfo_num(sk) OPENSSL_sk_num(ossl_check_const_CMS_RecipientInfo_sk_type(sk))
#define sk_CMS_RecipientInfo_value(sk, idx) ((CMS_RecipientInfo *)OPENSSL_sk_value(ossl_check_const_CMS_RecipientInfo_sk_type(sk), (idx)))
#define sk_CMS_RecipientInfo_new(cmp) ((STACK_OF(CMS_RecipientInfo) *)OPENSSL_sk_new(ossl_check_CMS_RecipientInfo_compfunc_type(cmp)))
#define sk_CMS_RecipientInfo_new_null() ((STACK_OF(CMS_RecipientInfo) *)OPENSSL_sk_new_null())
#define sk_CMS_RecipientInfo_new_reserve(cmp, n) ((STACK_OF(CMS_RecipientInfo) *)OPENSSL_sk_new_reserve(ossl_check_CMS_RecipientInfo_compfunc_type(cmp), (n)))
#define sk_CMS_RecipientInfo_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_CMS_RecipientInfo_sk_type(sk), (n))
#define sk_CMS_RecipientInfo_free(sk) OPENSSL_sk_free(ossl_check_CMS_RecipientInfo_sk_type(sk))
#define sk_CMS_RecipientInfo_zero(sk) OPENSSL_sk_zero(ossl_check_CMS_RecipientInfo_sk_type(sk))
#define sk_CMS_RecipientInfo_delete(sk, i) ((CMS_RecipientInfo *)OPENSSL_sk_delete(ossl_check_CMS_RecipientInfo_sk_type(sk), (i)))
#define sk_CMS_RecipientInfo_delete_ptr(sk, ptr) ((CMS_RecipientInfo *)OPENSSL_sk_delete_ptr(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr)))
#define sk_CMS_RecipientInfo_push(sk, ptr) OPENSSL_sk_push(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr))
#define sk_CMS_RecipientInfo_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr))
#define sk_CMS_RecipientInfo_pop(sk) ((CMS_RecipientInfo *)OPENSSL_sk_pop(ossl_check_CMS_RecipientInfo_sk_type(sk)))
#define sk_CMS_RecipientInfo_shift(sk) ((CMS_RecipientInfo *)OPENSSL_sk_shift(ossl_check_CMS_RecipientInfo_sk_type(sk)))
#define sk_CMS_RecipientInfo_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_CMS_RecipientInfo_sk_type(sk),ossl_check_CMS_RecipientInfo_freefunc_type(freefunc))
#define sk_CMS_RecipientInfo_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr), (idx))
#define sk_CMS_RecipientInfo_set(sk, idx, ptr) ((CMS_RecipientInfo *)OPENSSL_sk_set(ossl_check_CMS_RecipientInfo_sk_type(sk), (idx), ossl_check_CMS_RecipientInfo_type(ptr)))
#define sk_CMS_RecipientInfo_find(sk, ptr) OPENSSL_sk_find(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr))
#define sk_CMS_RecipientInfo_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr))
#define sk_CMS_RecipientInfo_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_type(ptr), pnum)
#define sk_CMS_RecipientInfo_sort(sk) OPENSSL_sk_sort(ossl_check_CMS_RecipientInfo_sk_type(sk))
#define sk_CMS_RecipientInfo_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_CMS_RecipientInfo_sk_type(sk))
#define sk_CMS_RecipientInfo_dup(sk) ((STACK_OF(CMS_RecipientInfo) *)OPENSSL_sk_dup(ossl_check_const_CMS_RecipientInfo_sk_type(sk)))
#define sk_CMS_RecipientInfo_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(CMS_RecipientInfo) *)OPENSSL_sk_deep_copy(ossl_check_const_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_copyfunc_type(copyfunc), ossl_check_CMS_RecipientInfo_freefunc_type(freefunc)))
#define sk_CMS_RecipientInfo_set_cmp_func(sk, cmp) ((sk_CMS_RecipientInfo_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_CMS_RecipientInfo_sk_type(sk), ossl_check_CMS_RecipientInfo_compfunc_type(cmp)))

/**
 * @brief Opaque STACK_OF(CMS_RevocationInfoChoice) container type.
 */
struct stack_st_CMS_RevocationInfoChoice;
SKM_DEFINE_STACK_OF_INTERNAL(CMS_RevocationInfoChoice, CMS_RevocationInfoChoice, CMS_RevocationInfoChoice)
#define sk_CMS_RevocationInfoChoice_num(sk) OPENSSL_sk_num(ossl_check_const_CMS_RevocationInfoChoice_sk_type(sk))
#define sk_CMS_RevocationInfoChoice_value(sk, idx) ((CMS_RevocationInfoChoice *)OPENSSL_sk_value(ossl_check_const_CMS_RevocationInfoChoice_sk_type(sk), (idx)))
#define sk_CMS_RevocationInfoChoice_new(cmp) ((STACK_OF(CMS_RevocationInfoChoice) *)OPENSSL_sk_new(ossl_check_CMS_RevocationInfoChoice_compfunc_type(cmp)))
#define sk_CMS_RevocationInfoChoice_new_null() ((STACK_OF(CMS_RevocationInfoChoice) *)OPENSSL_sk_new_null())
#define sk_CMS_RevocationInfoChoice_new_reserve(cmp, n) ((STACK_OF(CMS_RevocationInfoChoice) *)OPENSSL_sk_new_reserve(ossl_check_CMS_RevocationInfoChoice_compfunc_type(cmp), (n)))
#define sk_CMS_RevocationInfoChoice_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), (n))
#define sk_CMS_RevocationInfoChoice_free(sk) OPENSSL_sk_free(ossl_check_CMS_RevocationInfoChoice_sk_type(sk))
#define sk_CMS_RevocationInfoChoice_zero(sk) OPENSSL_sk_zero(ossl_check_CMS_RevocationInfoChoice_sk_type(sk))
#define sk_CMS_RevocationInfoChoice_delete(sk, i) ((CMS_RevocationInfoChoice *)OPENSSL_sk_delete(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), (i)))
#define sk_CMS_RevocationInfoChoice_delete_ptr(sk, ptr) ((CMS_RevocationInfoChoice *)OPENSSL_sk_delete_ptr(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr)))
#define sk_CMS_RevocationInfoChoice_push(sk, ptr) OPENSSL_sk_push(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr))
#define sk_CMS_RevocationInfoChoice_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr))
#define sk_CMS_RevocationInfoChoice_pop(sk) ((CMS_RevocationInfoChoice *)OPENSSL_sk_pop(ossl_check_CMS_RevocationInfoChoice_sk_type(sk)))
#define sk_CMS_RevocationInfoChoice_shift(sk) ((CMS_RevocationInfoChoice *)OPENSSL_sk_shift(ossl_check_CMS_RevocationInfoChoice_sk_type(sk)))
#define sk_CMS_RevocationInfoChoice_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_CMS_RevocationInfoChoice_sk_type(sk),ossl_check_CMS_RevocationInfoChoice_freefunc_type(freefunc))
#define sk_CMS_RevocationInfoChoice_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr), (idx))
#define sk_CMS_RevocationInfoChoice_set(sk, idx, ptr) ((CMS_RevocationInfoChoice *)OPENSSL_sk_set(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), (idx), ossl_check_CMS_RevocationInfoChoice_type(ptr)))
#define sk_CMS_RevocationInfoChoice_find(sk, ptr) OPENSSL_sk_find(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr))
#define sk_CMS_RevocationInfoChoice_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr))
#define sk_CMS_RevocationInfoChoice_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_type(ptr), pnum)
#define sk_CMS_RevocationInfoChoice_sort(sk) OPENSSL_sk_sort(ossl_check_CMS_RevocationInfoChoice_sk_type(sk))
#define sk_CMS_RevocationInfoChoice_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_CMS_RevocationInfoChoice_sk_type(sk))
#define sk_CMS_RevocationInfoChoice_dup(sk) ((STACK_OF(CMS_RevocationInfoChoice) *)OPENSSL_sk_dup(ossl_check_const_CMS_RevocationInfoChoice_sk_type(sk)))
#define sk_CMS_RevocationInfoChoice_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(CMS_RevocationInfoChoice) *)OPENSSL_sk_deep_copy(ossl_check_const_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_copyfunc_type(copyfunc), ossl_check_CMS_RevocationInfoChoice_freefunc_type(freefunc)))
#define sk_CMS_RevocationInfoChoice_set_cmp_func(sk, cmp) ((sk_CMS_RevocationInfoChoice_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_CMS_RevocationInfoChoice_sk_type(sk), ossl_check_CMS_RevocationInfoChoice_compfunc_type(cmp)))

/* clang-format on */

/**
 * @brief Return the ASN.1 item descriptor for CMS_EnvelopedData.
 * @return Pointer to the static ASN1_ITEM for CMS_EnvelopedData.
 */
const ASN1_ITEM *CMS_EnvelopedData_it(void);
/**
 * @brief Allocate an empty CMS SignedData structure.
 * @return New CMS_SignedData, or NULL on allocation failure.
 */
CMS_SignedData *CMS_SignedData_new(void);
/**
 * @brief Free a CMS SignedData structure and its contents.
 * @param a Value to free, or NULL.
 */
void CMS_SignedData_free(CMS_SignedData *a);
/**
 * @brief Allocate an empty CMS ContentInfo structure.
 * @return New CMS_ContentInfo, or NULL on allocation failure.
 */
CMS_ContentInfo *CMS_ContentInfo_new(void);
/**
 * @brief Free a CMS ContentInfo structure and its contents.
 * @param a Value to free, or NULL.
 */
void CMS_ContentInfo_free(CMS_ContentInfo *a);
/**
 * @brief Decode a CMS ContentInfo from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded CMS_ContentInfo, or NULL on error.
 */
CMS_ContentInfo *d2i_CMS_ContentInfo(CMS_ContentInfo **a, const unsigned char **in, long len);
/**
 * @brief Encode a CMS ContentInfo to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_CMS_ContentInfo(const CMS_ContentInfo *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for CMS_ContentInfo.
 * @return Pointer to the static ASN1_ITEM for CMS_ContentInfo.
 */
const ASN1_ITEM *CMS_ContentInfo_it(void);
/**
 * @brief Allocate an empty CMS ReceiptRequest structure.
 * @return New CMS_ReceiptRequest, or NULL on allocation failure.
 */
CMS_ReceiptRequest *CMS_ReceiptRequest_new(void);
/**
 * @brief Free a CMS ReceiptRequest structure and its contents.
 * @param a Value to free, or NULL.
 */
void CMS_ReceiptRequest_free(CMS_ReceiptRequest *a);
/**
 * @brief Decode a CMS ReceiptRequest from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded CMS_ReceiptRequest, or NULL on error.
 */
CMS_ReceiptRequest *d2i_CMS_ReceiptRequest(CMS_ReceiptRequest **a, const unsigned char **in, long len);
/**
 * @brief Encode a CMS ReceiptRequest to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_CMS_ReceiptRequest(const CMS_ReceiptRequest *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for CMS_ReceiptRequest.
 * @return Pointer to the static ASN1_ITEM for CMS_ReceiptRequest.
 */
const ASN1_ITEM *CMS_ReceiptRequest_it(void);
/**
 * @brief Print a CMS_ContentInfo structure to a BIO.
 * @param out BIO to write human-readable output to.
 * @param x CMS ContentInfo to print.
 * @param indent Indentation depth in spaces.
 * @param pctx Optional ASN.1 print context, or NULL for defaults.
 * @return 1 on success, or 0 on failure.
 */
int CMS_ContentInfo_print_ctx(BIO *out, const CMS_ContentInfo *x, int indent,
    const ASN1_PCTX *pctx);

/**
 * @brief Allocate a CMS ContentInfo associated with a library context and property query.
 * @param libctx Library context used when fetching algorithms for this object, or NULL for the default.
 * @param propq Property query string for provider algorithm selection, or NULL.
 * @return New CMS_ContentInfo, or NULL on allocation failure.
 */
CMS_ContentInfo *CMS_ContentInfo_new_ex(OSSL_LIB_CTX *libctx, const char *propq);

#define CMS_SIGNERINFO_ISSUER_SERIAL 0
#define CMS_SIGNERINFO_KEYIDENTIFIER 1

#define CMS_RECIPINFO_NONE -1
#define CMS_RECIPINFO_TRANS 0
#define CMS_RECIPINFO_AGREE 1
#define CMS_RECIPINFO_KEK 2
#define CMS_RECIPINFO_PASS 3
#define CMS_RECIPINFO_OTHER 4

/* S/MIME related flags */

#define CMS_TEXT 0x1
#define CMS_NOCERTS 0x2
#define CMS_NO_CONTENT_VERIFY 0x4
#define CMS_NO_ATTR_VERIFY 0x8
#define CMS_NOSIGS \
    (CMS_NO_CONTENT_VERIFY | CMS_NO_ATTR_VERIFY)
#define CMS_NOINTERN 0x10
#define CMS_NO_SIGNER_CERT_VERIFY 0x20
#define CMS_NOVERIFY 0x20
#define CMS_DETACHED 0x40
#define CMS_BINARY 0x80
#define CMS_NOATTR 0x100
#define CMS_NOSMIMECAP 0x200
#define CMS_NOOLDMIMETYPE 0x400
#define CMS_CRLFEOL 0x800
#define CMS_STREAM 0x1000
#define CMS_NOCRL 0x2000
#define CMS_PARTIAL 0x4000
#define CMS_REUSE_DIGEST 0x8000
#define CMS_USE_KEYID 0x10000
#define CMS_DEBUG_DECRYPT 0x20000
#define CMS_KEY_PARAM 0x40000
#define CMS_ASCIICRLF 0x80000
#define CMS_CADES 0x100000
#define CMS_USE_ORIGINATOR_KEYID 0x200000

/**
 * @brief Return the ASN.1 content-type OID of a CMS ContentInfo.
 * @param cms ContentInfo to query.
 * @return Internal ASN1_OBJECT for the content type (for example NID_pkcs7_signed); do not free.
 */
const ASN1_OBJECT *CMS_get0_type(const CMS_ContentInfo *cms);

/**
 * @brief Build a BIO chain that reads or writes the CMS content for @p cms.
 * @param cms ContentInfo whose processing BIO chain is created.
 * @param icont Optional content BIO to push under the CMS filters; NULL allocates an appropriate content BIO.
 * @return BIO chain suitable for reading or writing content, or NULL on error.
 */
BIO *CMS_dataInit(CMS_ContentInfo *cms, BIO *icont);
/**
 * @brief Finalize CMS content processing after streaming through the BIO from CMS_dataInit().
 * @param cms ContentInfo whose content digests/signatures are completed.
 * @param bio BIO chain previously returned by CMS_dataInit() (or an equivalent filter chain).
 * @return 1 on success, or 0 on failure.
 */
int CMS_dataFinal(CMS_ContentInfo *cms, BIO *bio);

/**
 * @brief Return a pointer to the embedded content octet string of a CMS ContentInfo.
 * @param cms ContentInfo whose eContent is accessed.
 * @return Address of the internal ASN1_OCTET_STRING pointer (may point to NULL if detached), or NULL on error.
 */
ASN1_OCTET_STRING **CMS_get0_content(CMS_ContentInfo *cms);
/**
 * @brief Test whether a CMS ContentInfo carries detached (absent) embedded content.
 * @param cms ContentInfo to query.
 * @return 1 if content is detached, 0 if embedded content is present, or -1 on error.
 */
int CMS_is_detached(CMS_ContentInfo *cms);
/**
 * @brief Mark CMS content as detached (external) or embedded.
 * @param cms ContentInfo whose eContent embedding is updated.
 * @param detached Nonzero for detached content; zero to keep content inside SignedData.
 * @return 1 on success, or 0 on failure.
 */
int CMS_set_detached(CMS_ContentInfo *cms, int detached);

#ifdef OPENSSL_PEM_H
DECLARE_PEM_rw(CMS, CMS_ContentInfo)
#endif
/**
 * @brief Prepare a CMS ContentInfo for indefinite-length (streaming) ASN.1 encoding.
 * @param boundary On success, receives the address of the content data pointer used as the streaming boundary.
 * @param cms ContentInfo whose embedded content is marked for NDEF streaming.
 * @return 1 on success, or 0 on failure.
 */
int CMS_stream(unsigned char ***boundary, CMS_ContentInfo *cms);
/**
 * @brief Decode a CMS ContentInfo from a BIO in DER form.
 * @param bp BIO that supplies DER input.
 * @param cms Optional destination pointer updated to the result, or NULL.
 * @return Decoded CMS_ContentInfo, or NULL on error.
 */
CMS_ContentInfo *d2i_CMS_bio(BIO *bp, CMS_ContentInfo **cms);
/**
 * @brief Encode a CMS ContentInfo to a BIO in DER form.
 * @param bp Destination BIO.
 * @param cms ContentInfo to encode.
 * @return 1 on success, or 0 on failure.
 */
int i2d_CMS_bio(BIO *bp, CMS_ContentInfo *cms);

/**
 * @brief Wrap a CMS ContentInfo in a filter BIO that writes indefinite-length BER to @p out.
 * @param out Underlying BIO that receives the encoded CMS structure.
 * @param cms CMS ContentInfo to encode through the filter.
 * @return New filter BIO, or NULL on failure; free with BIO_free_all().
 */
BIO *BIO_new_CMS(BIO *out, CMS_ContentInfo *cms);
/**
 * @brief Stream a CMS ContentInfo to @p out as BER, optionally pulling content from @p in.
 * @param out Destination BIO for the BER encoding.
 * @param cms CMS structure to encode.
 * @param in Optional BIO supplying streaming content bytes, or NULL.
 * @param flags CMS output flags (for example CMS_STREAM).
 * @return 1 on success, or 0 on failure.
 */
int i2d_CMS_bio_stream(BIO *out, CMS_ContentInfo *cms, BIO *in, int flags);
/**
 * @brief Write a CMS ContentInfo as a PEM CMS message, optionally streaming content from @p in.
 * @param out BIO that receives the PEM-encoded CMS.
 * @param cms CMS structure to encode.
 * @param in BIO supplying detached or streaming content when required by @p flags, or NULL.
 * @param flags CMS_* flags controlling streaming and encoding behaviour.
 * @return 1 on success, or 0 on error.
 */
int PEM_write_bio_CMS_stream(BIO *out, CMS_ContentInfo *cms, BIO *in,
    int flags);
/**
 * @brief Parse an S/MIME message from a BIO into a CMS_ContentInfo.
 * @param bio BIO from which the S/MIME message is read.
 * @param bcont If non-NULL, receives a memory BIO with cleartext signed content, or is set to NULL.
 * @return Parsed CMS_ContentInfo, or NULL on error.
 *
 * Equivalent to SMIME_read_CMS_ex() with flags 0 and a NULL reuse pointer.
 */
CMS_ContentInfo *SMIME_read_CMS(BIO *bio, BIO **bcont);
/**
 * @brief Parse an S/MIME message into a CMS_ContentInfo, with optional flags and reuse.
 * @param bio BIO from which the S/MIME message is read.
 * @param flags Parse flags such as CMS_BINARY and SMIME_ASCIICRLF; 0 matches SMIME_read_CMS().
 * @param bcont If non-NULL, receives a memory BIO with cleartext signed content, or is set to NULL.
 * @param ci Optional existing CMS_ContentInfo to populate (for example from CMS_ContentInfo_new_ex), or NULL to allocate.
 * @return Parsed CMS_ContentInfo, or NULL on error.
 */
CMS_ContentInfo *SMIME_read_CMS_ex(BIO *bio, int flags, BIO **bcont, CMS_ContentInfo **ci);
/**
 * @brief Write a CMS_ContentInfo as an S/MIME (MIME) message to @p bio.
 * @param bio Output BIO receiving the MIME-formatted CMS.
 * @param cms CMS object to serialise (typically signed or enveloped data).
 * @param data Optional content BIO for detached/streaming content, or NULL.
 * @param flags CMS_* / SMIME_* flags controlling MIME headers and streaming.
 * @return 1 on success, or 0 on failure.
 */
int SMIME_write_CMS(BIO *bio, CMS_ContentInfo *cms, BIO *data, int flags);

/**
 * @brief Finalise a partially built CMS_ContentInfo (for example digest computation and field fill-in).
 * @param cms ContentInfo created with CMS_PARTIAL that still needs finalisation.
 * @param data BIO supplying content to process (for example for digesting).
 * @param dcont BIO that receives processed content for detached data, or usually NULL.
 * @param flags CMS flags controlling finalisation behaviour.
 * @return 1 on success, or 0 on failure.
 *
 * Used when CMS_PARTIAL is set and streaming I/O is not performing finalisation internally.
 */
int CMS_final(CMS_ContentInfo *cms, BIO *data, BIO *dcont,
    unsigned int flags);
/**
 * @brief Finalize a partially built CMS SignedData using a precomputed content digest.
 * @param cms Partial CMS structure created with CMS_PARTIAL (or streaming) flags.
 * @param md Precomputed message digest of the content.
 * @param mdlen Length of @p md in bytes.
 * @param dcont Detached content BIO when applicable, or NULL.
 * @param flags CMS finalization flags.
 * @return 1 on success, or 0 on failure.
 */
int CMS_final_digest(CMS_ContentInfo *cms,
    const unsigned char *md, unsigned int mdlen, BIO *dcont,
    unsigned int flags);

/**
 * @brief Create a CMS SignedData structure with the default library context.
 * @param signcert Signer certificate corresponding to @p pkey, or NULL for certificates-only.
 * @param pkey Signer private key, or NULL when only embedding certificates.
 * @param certs Optional intermediate certificates to include, or NULL.
 * @param data Content BIO to sign.
 * @param flags CMS signing flags (for example CMS_DETACHED, CMS_BINARY).
 * @return New SignedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_sign(X509 *signcert, EVP_PKEY *pkey,
    STACK_OF(X509) *certs, BIO *data,
    unsigned int flags);
/**
 * @brief Create a CMS SignedData structure using a library context.
 * @param signcert Signer certificate corresponding to @p pkey, or NULL for certificates-only.
 * @param pkey Signer private key, or NULL when only embedding certificates.
 * @param certs Optional intermediate certificates to include, or NULL.
 * @param data Content BIO to sign (read fully unless CMS_STREAM / CMS_PARTIAL flags apply).
 * @param flags CMS signing flags (for example CMS_DETACHED, CMS_BINARY).
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return New SignedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_sign_ex(X509 *signcert, EVP_PKEY *pkey,
    STACK_OF(X509) *certs, BIO *data,
    unsigned int flags, OSSL_LIB_CTX *libctx,
    const char *propq);

/**
 * @brief Create a CMS signed receipt ContentInfo for a SignerInfo that requested a receipt.
 * @param si SignerInfo from the original SignedData that contains the receipt request.
 * @param signcert Certificate of the receipt signer.
 * @param pkey Private key corresponding to @p signcert.
 * @param certs Optional additional certificates to include (for example intermediate CAs), or NULL.
 * @param flags Optional CMS flags (CMS_DETACHED, CMS_BINARY, CMS_NOATTR, CMS_TEXT, and CMS_STREAM are not supported).
 * @return New signed-receipt ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_sign_receipt(CMS_SignerInfo *si,
    X509 *signcert, EVP_PKEY *pkey,
    STACK_OF(X509) *certs, unsigned int flags);

/**
 * @brief Write the payload of a CMS Data ContentInfo to a BIO.
 * @param cms ContentInfo of type NID_pkcs7_data.
 * @param out Destination BIO for the extracted content.
 * @param flags Optional CMS content-copy flags (for example CMS_TEXT).
 * @return 1 on success, or 0 on failure.
 */
int CMS_data(CMS_ContentInfo *cms, BIO *out, unsigned int flags);
/**
 * @brief Create a CMS Data ContentInfo from bytes read from @p in.
 * @param in BIO supplying the content octets.
 * @param flags CMS flags; CMS_STREAM defers CMS_final() for streaming.
 * @return New CMS_ContentInfo of type NID_pkcs7_data, or NULL on error.
 *
 * Equivalent to CMS_data_create_ex() with a NULL library context and property query.
 */
CMS_ContentInfo *CMS_data_create(BIO *in, unsigned int flags);
/**
 * @brief Create a CMS Data contentInfo wrapping the octets read from @p in.
 * @param in BIO supplying the content bytes to embed.
 * @param flags CMS_* flags (for example CMS_STREAM / CMS_PARTIAL).
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider algorithms, or NULL.
 * @return New CMS_ContentInfo, or NULL on error; free with CMS_ContentInfo_free().
 */
CMS_ContentInfo *CMS_data_create_ex(BIO *in, unsigned int flags,
    OSSL_LIB_CTX *libctx, const char *propq);

/**
 * @brief Verify a CMS DigestedData ContentInfo and optionally write the content.
 * @param cms ContentInfo of type NID_pkcs7_digest to verify.
 * @param dcont Detached content BIO when the digest is detached; normally NULL.
 * @param out Optional BIO that receives the content after successful verification, or NULL.
 * @param flags Optional CMS verify flags (for example CMS_TEXT).
 * @return 1 on successful verification, or 0 on failure.
 */
int CMS_digest_verify(CMS_ContentInfo *cms, BIO *dcont, BIO *out,
    unsigned int flags);
/**
 * @brief Create a CMS DigestedData ContentInfo from content read from a BIO.
 * @param in BIO supplying the data to digest.
 * @param md Message digest algorithm to apply.
 * @param flags Optional CMS flags; CMS_DETACHED and CMS_STREAM are supported.
 * @return New DigestedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_digest_create(BIO *in, const EVP_MD *md,
    unsigned int flags);
/**
 * @brief Create a CMS DigestedData ContentInfo using a library context and property query.
 * @param in BIO supplying the data to digest.
 * @param md Message digest algorithm to apply.
 * @param flags Optional CMS flags; CMS_DETACHED and CMS_STREAM are supported.
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return New DigestedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_digest_create_ex(BIO *in, const EVP_MD *md,
    unsigned int flags, OSSL_LIB_CTX *libctx,
    const char *propq);

/**
 * @brief Decrypt a CMS EncryptedData ContentInfo with a symmetric key.
 * @param cms EncryptedData ContentInfo to decrypt (AEAD ciphers are not supported).
 * @param key Symmetric decryption key bytes.
 * @param keylen Length of @p key in bytes.
 * @param dcont Detached encrypted-content BIO, or NULL when content is embedded.
 * @param out BIO that receives the decrypted plaintext.
 * @param flags Optional CMS flags (for example CMS_TEXT).
 * @return 1 on success, or 0 on failure.
 */
int CMS_EncryptedData_decrypt(CMS_ContentInfo *cms,
    const unsigned char *key, size_t keylen,
    BIO *dcont, BIO *out, unsigned int flags);
/**
 * @brief Create a CMS EncryptedData ContentInfo by encrypting data from a BIO.
 * @param in BIO supplying the plaintext to encrypt.
 * @param cipher Symmetric cipher; must support ASN.1 encoding of its parameters (AEAD not supported).
 * @param key Encryption key bytes.
 * @param keylen Length of @p key in bytes.
 * @param flags CMS_* option flags such as CMS_DETACHED, CMS_STREAM, or CMS_PARTIAL.
 * @return New CMS_ContentInfo of type NID_pkcs7_encrypted, or NULL on error.
 *
 * Equivalent to CMS_EncryptedData_encrypt_ex() with a NULL library context and property query.
 * Unless CMS_STREAM and/or CMS_PARTIAL is set, CMS_final() is called internally.
 */
CMS_ContentInfo *CMS_EncryptedData_encrypt(BIO *in, const EVP_CIPHER *cipher,
    const unsigned char *key,
    size_t keylen, unsigned int flags);
/**
 * @brief Create a CMS EncryptedData ContentInfo by encrypting data from a BIO (with libctx).
 * @param in BIO supplying the plaintext to encrypt.
 * @param cipher Symmetric cipher; must support ASN.1 encoding of its parameters (AEAD not supported).
 * @param key Encryption key bytes.
 * @param keylen Length of @p key in bytes.
 * @param flags CMS_* option flags such as CMS_DETACHED, CMS_STREAM, or CMS_PARTIAL.
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return New EncryptedData ContentInfo, or NULL on error.
 *
 * Unless CMS_STREAM and/or CMS_PARTIAL is set, CMS_final() is called internally.
 */
CMS_ContentInfo *CMS_EncryptedData_encrypt_ex(BIO *in, const EVP_CIPHER *cipher,
    const unsigned char *key,
    size_t keylen, unsigned int flags,
    OSSL_LIB_CTX *libctx,
    const char *propq);

/**
 * @brief Set the content-encryption cipher and copy the symmetric key into a CMS EncryptedData.
 * @param cms ContentInfo expected to contain EncryptedData (AEAD ciphers are not supported).
 * @param ciph Symmetric cipher whose ASN.1 parameters are recorded.
 * @param key Symmetric key bytes to copy.
 * @param keylen Length of @p key in octets.
 * @return 1 on success, or 0 on failure.
 */
int CMS_EncryptedData_set1_key(CMS_ContentInfo *cms, const EVP_CIPHER *ciph,
    const unsigned char *key, size_t keylen);

/**
 * @brief Verify CMS SignedData signatures and write the content to @p out when requested.
 * @param cms SignedData ContentInfo to verify.
 * @param certs Optional untrusted certificates to aid signer location, or NULL.
 * @param store Trusted certificate store used to build and validate signer chains, or NULL.
 * @param dcont Detached content BIO when the payload is not embedded; otherwise NULL.
 * @param out Optional BIO that receives the verified content, or NULL.
 * @param flags CMS verify flags (for example CMS_NO_SIGNER_CERT_VERIFY).
 * @return 1 on success, or 0 on failure.
 */
int CMS_verify(CMS_ContentInfo *cms, STACK_OF(X509) *certs,
    X509_STORE *store, BIO *dcont, BIO *out, unsigned int flags);

/**
 * @brief Verify a CMS signed receipt against the original SignedData that requested it.
 * @param rcms Signed receipt ContentInfo to verify.
 * @param ocms Original SignedData ContentInfo that contained the receipt request.
 * @param certs Certificates in which to search for the receipt's signing certificate.
 * @param store Trusted store used for certificate chain verification.
 * @param flags Optional CMS verify flags (CMS_DETACHED, CMS_BINARY, CMS_TEXT, and CMS_STREAM are not supported).
 * @return 1 on successful verification, or 0 on failure.
 */
int CMS_verify_receipt(CMS_ContentInfo *rcms, CMS_ContentInfo *ocms,
    STACK_OF(X509) *certs,
    X509_STORE *store, unsigned int flags);

/**
 * @brief Return the signer certificates collected during a successful CMS_verify().
 * @param cms SignedData ContentInfo previously verified with CMS_verify() or CMS_SignedData_verify().
 * @return Internal stack of signer certificates (do not free), or NULL on error.
 */
STACK_OF(X509) *CMS_get0_signers(CMS_ContentInfo *cms);

/**
 * @brief Create a CMS EnvelopedData or AuthEnvelopedData encrypting content for recipient certificates.
 * @param certs Stack of recipient certificates (RSA, Diffie-Hellman, or EC keys).
 * @param in BIO supplying the content to encrypt (unused when CMS_STREAM is set).
 * @param cipher Symmetric content-encryption cipher; GCM yields AuthEnvelopedData.
 * @param flags Optional CMS flags (CMS_TEXT, CMS_BINARY, CMS_USE_KEYID, CMS_STREAM, CMS_PARTIAL, CMS_DETACHED, …).
 * @return New enveloped ContentInfo, or NULL on error.
 *
 * Equivalent to CMS_encrypt_ex() with a NULL library context and property query.
 */
CMS_ContentInfo *CMS_encrypt(STACK_OF(X509) *certs, BIO *in,
    const EVP_CIPHER *cipher, unsigned int flags);
/**
 * @brief Create a CMS EnvelopedData or AuthEnvelopedData encrypting content for recipient certificates.
 * @param certs Stack of recipient certificates (RSA, Diffie-Hellman, or EC keys).
 * @param in BIO supplying the content to encrypt (unused when CMS_STREAM is set).
 * @param cipher Symmetric content-encryption cipher; GCM yields AuthEnvelopedData.
 * @param flags Optional CMS flags (CMS_TEXT, CMS_BINARY, CMS_USE_KEYID, CMS_STREAM, CMS_PARTIAL, CMS_DETACHED, …).
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return New enveloped ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_encrypt_ex(STACK_OF(X509) *certs, BIO *in,
    const EVP_CIPHER *cipher, unsigned int flags,
    OSSL_LIB_CTX *libctx, const char *propq);

/**
 * @brief Decrypt a CMS EnvelopedData or AuthEnvelopedData and write the content.
 * @param cms Enveloped ContentInfo to decrypt.
 * @param pkey Recipient private key, or NULL if a key was already set via CMS_decrypt_set1_*.
 * @param cert Recipient certificate used to locate the matching RecipientInfo; may be NULL.
 * @param dcont Detached encrypted-content BIO when applicable; normally NULL.
 * @param out BIO that receives the decrypted content (may be NULL when only setting up keys).
 * @param flags Optional CMS decrypt flags (for example CMS_TEXT or CMS_DEBUG_DECRYPT).
 * @return 1 on success, or 0 on failure.
 */
int CMS_decrypt(CMS_ContentInfo *cms, EVP_PKEY *pkey, X509 *cert,
    BIO *dcont, BIO *out, unsigned int flags);

/**
 * @brief Decrypt CMS recipient key material using a private key, then store it for CMS_decrypt().
 * @param cms CMS ContentInfo to decrypt; on success stores @p pk for a later CMS_decrypt() with NULL key arguments.
 * @param pk Recipient private key used to unwrap the content-encryption key.
 * @param cert Recipient certificate used to locate the matching RecipientInfo; may be NULL to try all recipients.
 * @return 1 on success, or 0 on failure.
 */
int CMS_decrypt_set1_pkey(CMS_ContentInfo *cms, EVP_PKEY *pk, X509 *cert);
/**
 * @brief Decrypt CMS EnvelopedData/AuthEnvelopedData recipient key material using a private key and optional peer certificate.
 * @param cms CMS ContentInfo to decrypt; on success stores @p pk for a later CMS_decrypt() with NULL key arguments.
 * @param pk Recipient private key used to unwrap the content-encryption key.
 * @param cert Recipient certificate used to locate the matching RecipientInfo; may be NULL to try all recipients.
 * @param peer Optional originator certificate for key-agreement recipients, or NULL.
 * @return 1 on success, or 0 on failure.
 */
int CMS_decrypt_set1_pkey_and_peer(CMS_ContentInfo *cms, EVP_PKEY *pk,
    X509 *cert, X509 *peer);
/**
 * @brief Install a KEKRecipientInfo key on a CMS ContentInfo so CMS_decrypt can use it.
 * @param cms Enveloped ContentInfo that contains a KEK recipient.
 * @param key Symmetric key-encryption key octets.
 * @param keylen Length of @p key in bytes.
 * @param id Optional key identifier matching the recipient's keyEncryptionKeyIdentifier, or NULL.
 * @param idlen Length of @p id in bytes when @p id is non-NULL.
 * @return 1 on success, or 0 on failure.
 */
int CMS_decrypt_set1_key(CMS_ContentInfo *cms,
    unsigned char *key, size_t keylen,
    const unsigned char *id, size_t idlen);
/**
 * @brief Decrypt CMS PasswordRecipientInfo key material and store it for a later CMS_decrypt().
 * @param cms Enveloped ContentInfo containing a password recipient.
 * @param pass Password bytes used to derive the key-encryption key.
 * @param passlen Length of @p pass in octets, or a negative value if @p pass is a NUL-terminated string.
 * @return 1 on success, or 0 on failure.
 */
int CMS_decrypt_set1_password(CMS_ContentInfo *cms,
    unsigned char *pass, ossl_ssize_t passlen);

/**
 * @brief Return the RecipientInfo structures from a CMS EnvelopedData message.
 * @param cms CMS ContentInfo expected to contain EnvelopedData (or AuthEnvelopedData).
 * @return Stack of CMS_RecipientInfo entries, or NULL on error.
 */
STACK_OF(CMS_RecipientInfo) *CMS_get0_RecipientInfos(CMS_ContentInfo *cms);
/**
 * @brief Return the CMS RecipientInfo type of @p ri.
 * @param ri Recipient info to query.
 * @return One of CMS_RECIPINFO_TRANS, CMS_RECIPINFO_AGREE, CMS_RECIPINFO_KEK,
 *         CMS_RECIPINFO_PASS, or CMS_RECIPINFO_OTHER.
 */
int CMS_RecipientInfo_type(CMS_RecipientInfo *ri);
/**
 * @brief Return the EVP_PKEY_CTX used for key transport or key agreement on a recipient info.
 * @param ri Recipient info of type CMS_RECIPINFO_TRANS or CMS_RECIPINFO_AGREE.
 * @return Internal EVP_PKEY_CTX pointer (do not free), or NULL if none / wrong type.
 */
EVP_PKEY_CTX *CMS_RecipientInfo_get0_pkey_ctx(CMS_RecipientInfo *ri);
/**
 * @brief Create an empty CMS AuthEnvelopedData ContentInfo for an AEAD cipher.
 * @param cipher Symmetric AEAD cipher to use (currently AES-GCM variants); must encode ASN.1 parameters.
 * @return New AuthEnvelopedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_AuthEnvelopedData_create(const EVP_CIPHER *cipher);
/**
 * @brief Create an empty CMS AuthEnvelopedData ContentInfo using a library context.
 * @param cipher Symmetric AEAD cipher to use (for example AES-GCM); must encode ASN.1 parameters.
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return New AuthEnvelopedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *
CMS_AuthEnvelopedData_create_ex(const EVP_CIPHER *cipher, OSSL_LIB_CTX *libctx,
    const char *propq);
/**
 * @brief Create an empty CMS EnvelopedData ContentInfo for @p cipher (default library context).
 * @param cipher Content-encryption cipher whose ASN.1 parameters will be encoded.
 * @return New EnvelopedData ContentInfo, or NULL on error; free with CMS_ContentInfo_free.
 */
CMS_ContentInfo *CMS_EnvelopedData_create(const EVP_CIPHER *cipher);
/**
 * @brief Create an empty CMS EnvelopedData ContentInfo using a library context.
 * @param cipher Content-encryption cipher whose ASN.1 parameters will be encoded.
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return New EnvelopedData ContentInfo, or NULL on error.
 */
CMS_ContentInfo *CMS_EnvelopedData_create_ex(const EVP_CIPHER *cipher,
    OSSL_LIB_CTX *libctx,
    const char *propq);
/**
 * @brief Decrypt a CMS EnvelopedData structure and return a BIO of the plaintext.
 * @param env EnvelopedData to decrypt.
 * @param detached_data Detached encrypted-content BIO when applicable; normally NULL.
 * @param pkey Recipient private key when @p secret is NULL.
 * @param cert Recipient certificate used to select the RecipientInfo; recommended when @p pkey is set.
 * @param secret Pre-shared content-encryption key, or NULL to unwrap with @p pkey.
 * @param flags Optional CMS decrypt flags (for example CMS_TEXT).
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for provider selection, or NULL.
 * @return BIO containing the decrypted content, or NULL on error.
 */
BIO *CMS_EnvelopedData_decrypt(CMS_EnvelopedData *env, BIO *detached_data,
    EVP_PKEY *pkey, X509 *cert,
    ASN1_OCTET_STRING *secret, unsigned int flags,
    OSSL_LIB_CTX *libctx, const char *propq);

/**
 * @brief Add a KeyTransRecipientInfo for @p recip to a partial CMS enveloped ContentInfo.
 * @param cms Enveloped ContentInfo created with CMS_PARTIAL (for example via CMS_encrypt()).
 * @param recip Recipient certificate whose public key wraps the content-encryption key.
 * @param flags Optional CMS flags such as CMS_USE_KEYID.
 * @return Internal pointer to the new CMS_RecipientInfo, or NULL on error.
 */
CMS_RecipientInfo *CMS_add1_recipient_cert(CMS_ContentInfo *cms,
    X509 *recip, unsigned int flags);
/**
 * @brief Add a recipient certificate and optional originator key material to enveloped CMS.
 * @param cms Enveloped ContentInfo created with CMS_PARTIAL.
 * @param recip Recipient certificate to add.
 * @param originatorPrivKey Originator private key for key-agreement recipients, or NULL when unused.
 * @param originator Originator certificate corresponding to @p originatorPrivKey, or NULL when unused.
 * @param flags Optional CMS flags such as CMS_USE_KEYID.
 * @return Internal pointer to the new CMS_RecipientInfo, or NULL on error.
 */
CMS_RecipientInfo *CMS_add1_recipient(CMS_ContentInfo *cms, X509 *recip,
    EVP_PKEY *originatorPrivKey, X509 *originator, unsigned int flags);
/**
 * @brief Transfer ownership of a private key into a key-transport RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_TRANS.
 * @param pkey Private key that @p ri will own (or NULL to clear); previous key is freed.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_set0_pkey(CMS_RecipientInfo *ri, EVP_PKEY *pkey);
/**
 * @brief Compare a certificate against the recipient identifier in a key-transport RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_TRANS.
 * @param cert Certificate whose issuer/serial or subject key id is compared.
 * @return 0 if @p cert matches the recipient id, or non-zero otherwise.
 */
int CMS_RecipientInfo_ktri_cert_cmp(CMS_RecipientInfo *ri, X509 *cert);
/**
 * @brief Retrieve key-transport algorithms and related objects from a RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_TRANS.
 * @param pk Receives the recipient public key if available, or NULL if not requested.
 * @param recip Receives the recipient certificate if available, or NULL if not requested.
 * @param palg Receives the key-encryption algorithm, or NULL if not requested.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_ktri_get0_algs(CMS_RecipientInfo *ri,
    EVP_PKEY **pk, X509 **recip,
    X509_ALGOR **palg);
/**
 * @brief Get the certificate recipient identifier from a key-transport RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_TRANS.
 * @param keyid Receives the subject key identifier when that form is used, or NULL if not requested.
 * @param issuer Receives the issuer name when issuerAndSerialNumber is used, or NULL if not requested.
 * @param sno Receives the serial number when issuerAndSerialNumber is used, or NULL if not requested.
 * @return 1 on success, or 0 on error.
 */
int CMS_RecipientInfo_ktri_get0_signer_id(CMS_RecipientInfo *ri,
    ASN1_OCTET_STRING **keyid,
    X509_NAME **issuer,
    ASN1_INTEGER **sno);

/**
 * @brief Add a KEKRecipientInfo that wraps the content-encryption key with a symmetric KEK.
 * @param cms Enveloped ContentInfo created with CMS_PARTIAL.
 * @param nid Key-wrap algorithm NID (AES wrap NIDs, or NID_undef to choose from @p keylen).
 * @param key Symmetric key-encryption key; ownership transfers to @p cms.
 * @param keylen Length of @p key in octets.
 * @param id Key identifier bytes; ownership transfers to @p cms.
 * @param idlen Length of @p id in octets.
 * @param date Optional key validity date, or NULL.
 * @param otherTypeId Optional otherKeyAttribute type OID, or NULL.
 * @param otherType Optional otherKeyAttribute value, or NULL.
 * @return Internal pointer to the new CMS_RecipientInfo, or NULL on error.
 */
CMS_RecipientInfo *CMS_add0_recipient_key(CMS_ContentInfo *cms, int nid,
    unsigned char *key, size_t keylen,
    unsigned char *id, size_t idlen,
    ASN1_GENERALIZEDTIME *date,
    ASN1_OBJECT *otherTypeId,
    ASN1_TYPE *otherType);

/**
 * @brief Return non-owning pointers to the key-encryption key identifier fields of a KEKRI.
 * @param ri Recipient info of type CMS_RECIPINFO_KEK.
 * @param palg Optional out-parameter for the keyEncryptionAlgorithm, or NULL.
 * @param pid Optional out-parameter for the keyIdentifier OCTET STRING, or NULL.
 * @param pdate Optional out-parameter for the optional date, or NULL.
 * @param potherid Optional out-parameter for otherKeyAttribute OID, or NULL.
 * @param pothertype Optional out-parameter for otherKeyAttribute value, or NULL.
 * @return 1 on success, or 0 if @p ri is not a KEK recipient info.
 */
int CMS_RecipientInfo_kekri_get0_id(CMS_RecipientInfo *ri,
    X509_ALGOR **palg,
    ASN1_OCTET_STRING **pid,
    ASN1_GENERALIZEDTIME **pdate,
    ASN1_OBJECT **potherid,
    ASN1_TYPE **pothertype);

/**
 * @brief Attach a symmetric key-encryption key to a KEK RecipientInfo (transfers ownership of @p key).
 * @param ri Recipient info of type CMS_RECIPINFO_KEK.
 * @param key Key bytes allocated with OPENSSL_malloc(); ownership transferred to @p ri (may be NULL to clear).
 * @param keylen Length of @p key in bytes.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_set0_key(CMS_RecipientInfo *ri,
    unsigned char *key, size_t keylen);

/**
 * @brief Compare a key identifier against the keyIdentifier of a KEK RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_KEK.
 * @param id Key identifier bytes to compare.
 * @param idlen Length of @p id in octets.
 * @return 0 if the identifiers match, or non-zero otherwise.
 */
int CMS_RecipientInfo_kekri_id_cmp(CMS_RecipientInfo *ri,
    const unsigned char *id, size_t idlen);

/**
 * @brief Supply the password used to derive the KEK for a PasswordRecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_PASS.
 * @param pass Password bytes; ownership transfers to @p ri (may be cleared on free).
 * @param passlen Length of @p pass in bytes, or -1 if NUL-terminated.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_set0_password(CMS_RecipientInfo *ri,
    unsigned char *pass,
    ossl_ssize_t passlen);

/**
 * @brief Add a PasswordRecipientInfo that derives a KEK from a password.
 * @param cms Enveloped ContentInfo created with CMS_PARTIAL.
 * @param iter PBKDF2 iteration count, or a non-positive value for the default.
 * @param wrap_nid Password-based key-wrap algorithm NID, or <= 0 for NID_id_alg_PWRI_KEK.
 * @param pbe_nid Password-based KDF NID, or <= 0 for NID_id_pbkdf2.
 * @param pass Password bytes; ownership transfers to @p cms (may be set later via CMS_RecipientInfo_set0_password).
 * @param passlen Length of @p pass in octets, or a negative value if @p pass is a NUL-terminated string.
 * @param kekciph Cipher used to wrap the content-encryption key; NULL uses the enveloped content cipher.
 * @return Internal pointer to the new CMS_RecipientInfo, or NULL on error.
 */
CMS_RecipientInfo *CMS_add0_recipient_password(CMS_ContentInfo *cms,
    int iter, int wrap_nid,
    int pbe_nid,
    unsigned char *pass,
    ossl_ssize_t passlen,
    const EVP_CIPHER *kekciph);

/**
 * @brief Decrypt one CMS RecipientInfo after associating the recipient key with it.
 * @param cms Enveloped ContentInfo that owns @p ri.
 * @param ri RecipientInfo whose encrypted key is unwrapped into the content-encryption key.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_decrypt(CMS_ContentInfo *cms, CMS_RecipientInfo *ri);
/**
 * @brief Encrypt the content-encryption key into one CMS RecipientInfo.
 * @param cms Enveloped ContentInfo that owns @p ri; the CEK must already be available (for example after decrypt).
 * @param ri RecipientInfo that receives the wrapped content-encryption key.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_encrypt(const CMS_ContentInfo *cms, CMS_RecipientInfo *ri);

/**
 * @brief Decompress a CMS CompressedData ContentInfo to @p out.
 * @param cms CompressedData ContentInfo to expand.
 * @param dcont Optional BIO supplying detached content, or NULL when content is embedded.
 * @param out BIO that receives the uncompressed content octets.
 * @param flags Optional CMS flags such as CMS_TEXT.
 * @return 1 on success, or 0 on failure.
 */
int CMS_uncompress(CMS_ContentInfo *cms, BIO *dcont, BIO *out,
    unsigned int flags);
/**
 * @brief Create a CMS CompressedData ContentInfo from content read from a BIO.
 * @param in Content to compress (ignored for reading when CMS_STREAM is set).
 * @param comp_nid Compression algorithm NID, or NID_undef for the default (zlib).
 * @param flags Optional CMS flags such as CMS_TEXT, CMS_BINARY, CMS_STREAM, or CMS_DETACHED.
 * @return New CMS_ContentInfo on success, or NULL on error.
 */
CMS_ContentInfo *CMS_compress(BIO *in, int comp_nid, unsigned int flags);

/**
 * @brief Set the embedded eContentType OID of a CMS ContentInfo (copied).
 * @param cms ContentInfo created with CMS_PARTIAL, before it is finalized.
 * @param oid Embedded content-type object identifier to copy into @p cms.
 * @return 1 on success, or 0 on error.
 */
int CMS_set1_eContentType(CMS_ContentInfo *cms, const ASN1_OBJECT *oid);
/**
 * @brief Return the embedded eContentType OID of a CMS ContentInfo.
 * @param cms ContentInfo whose encapsulated content type is queried.
 * @return Internal ASN1_OBJECT pointer (do not free), or the type object for the structure.
 */
const ASN1_OBJECT *CMS_get0_eContentType(CMS_ContentInfo *cms);

/**
 * @brief Append an empty CertificateChoices slot to a CMS SignedData certificates set.
 * @param cms ContentInfo of type signed-data (or similar) that holds certificates.
 * @return Newly added CMS_CertificateChoices, or NULL on error; ownership stays with @p cms.
 */
CMS_CertificateChoices *CMS_add0_CertificateChoices(CMS_ContentInfo *cms);
/**
 * @brief Add a certificate to a SignedData or EnvelopedData CMS ContentInfo (transfers ownership).
 * @param cms ContentInfo of type signed data or (authenticated) enveloped data.
 * @param cert Certificate to include; on success the caller must not free it.
 * @return 1 on success, or 0 on failure.
 */
int CMS_add0_cert(CMS_ContentInfo *cms, X509 *cert);
/**
 * @brief Add a certificate to a CMS ContentInfo, taking a reference on @p cert.
 * @param cms ContentInfo of type signed data or (authenticated) enveloped data.
 * @param cert Certificate to add unless already present; caller retains ownership.
 * @return 1 on success, or 0 on failure.
 */
int CMS_add1_cert(CMS_ContentInfo *cms, X509 *cert);
/**
 * @brief Return a new stack of all certificates carried in a CMS ContentInfo.
 * @param cms ContentInfo of type signed data or (authenticated) enveloped data.
 * @return New STACK_OF(X509) the caller must free (certificates are up-reffed), or NULL if none or on error.
 */
STACK_OF(X509) *CMS_get1_certs(CMS_ContentInfo *cms);

/**
 * @brief Append an empty RevocationInfoChoice to a CMS ContentInfo's CRL set.
 * @param cms ContentInfo of type signed data or (authenticated) enveloped data.
 * @return Internal pointer to the new choice (populate type and contents), or NULL on error.
 */
CMS_RevocationInfoChoice *CMS_add0_RevocationInfoChoice(CMS_ContentInfo *cms);
/**
 * @brief Add a CRL to a SignedData or EnvelopedData CMS ContentInfo (transfers ownership).
 * @param cms ContentInfo of type signed data or (authenticated) enveloped data.
 * @param crl CRL to include; on success the caller must not free it.
 * @return 1 on success, or 0 on failure.
 */
int CMS_add0_crl(CMS_ContentInfo *cms, X509_CRL *crl);
/**
 * @brief Add a CRL to a SignedData or EnvelopedData CMS ContentInfo (up-refs the CRL).
 * @param cms ContentInfo of type signed data or (authenticated) enveloped data.
 * @param crl CRL to include; the caller retains ownership and must free it.
 * @return 1 on success, or 0 on failure.
 */
int CMS_add1_crl(CMS_ContentInfo *cms, X509_CRL *crl);
/**
 * @brief Return a newly allocated stack of CRLs embedded in a CMS ContentInfo.
 * @param cms CMS structure that may contain certificates/CRLs (typically SignedData).
 * @return New STACK_OF(X509_CRL) with up-referenced CRLs, or NULL if none / on error.
 */
STACK_OF(X509_CRL) *CMS_get1_crls(CMS_ContentInfo *cms);

/**
 * @brief Initialize @p cms as an empty CMS SignedData (for example for certificates-only).
 * @param cms ContentInfo that receives a SignedData structure if not already present.
 * @return 1 on success, or 0 on failure.
 */
int CMS_SignedData_init(CMS_ContentInfo *cms);
/**
 * @brief Add a signer certificate and private key to a CMS SignedData ContentInfo.
 * @param cms CMS_ContentInfo that must already be SignedData (for example from CMS_sign() with CMS_PARTIAL).
 * @param signer Signer certificate.
 * @param pk Private key corresponding to @p signer.
 * @param md Message digest to use, or NULL to select the default digest for the key algorithm.
 * @param flags CMS_* option flags controlling digest reuse, attributes, and finalization.
 * @return The new CMS_SignerInfo on success, or NULL on error.
 *
 * Unless CMS_REUSE_DIGEST is set, the ContentInfo is incomplete until finalized by streaming or CMS_final().
 */
CMS_SignerInfo *CMS_add1_signer(CMS_ContentInfo *cms,
    X509 *signer, EVP_PKEY *pk, const EVP_MD *md,
    unsigned int flags);
/**
 * @brief Return the EVP_PKEY_CTX used while signing or verifying a CMS SignerInfo.
 * @param si SignerInfo whose public-key context is requested.
 * @return Internal EVP_PKEY_CTX pointer (do not free), or NULL if none is set.
 */
EVP_PKEY_CTX *CMS_SignerInfo_get0_pkey_ctx(CMS_SignerInfo *si);
/**
 * @brief Return the message-digest context used while signing or verifying a CMS SignerInfo.
 * @param si SignerInfo whose digest context is requested.
 * @return Internal EVP_MD_CTX pointer (do not free), or NULL if none is set.
 */
EVP_MD_CTX *CMS_SignerInfo_get0_md_ctx(CMS_SignerInfo *si);
/**
 * @brief Return all CMS_SignerInfo structures from a SignedData ContentInfo.
 * @param cms ContentInfo expected to contain SignedData.
 * @return Internal stack of SignerInfos (do not free), or NULL if none / not SignedData.
 */
STACK_OF(CMS_SignerInfo) *CMS_get0_SignerInfos(CMS_ContentInfo *cms);

/**
 * @brief Associate a signer certificate with a CMS SignerInfo (increments the cert reference).
 * @param si SignerInfo to update.
 * @param signer Signer certificate to attach.
 */
void CMS_SignerInfo_set1_signer_cert(CMS_SignerInfo *si, X509 *signer);
/**
 * @brief Get the signer identifier from a CMS SignerInfo (key id, or issuer and serial).
 * @param si SignerInfo whose sid is read.
 * @param keyid Receives the subject key identifier when that form is used, or NULL if not requested.
 * @param issuer Receives the issuer name when issuerAndSerialNumber is used, or NULL if not requested.
 * @param sno Receives the serial number when issuerAndSerialNumber is used, or NULL if not requested.
 * @return 1 on success, or 0 on failure.
 */
int CMS_SignerInfo_get0_signer_id(CMS_SignerInfo *si,
    ASN1_OCTET_STRING **keyid,
    X509_NAME **issuer, ASN1_INTEGER **sno);
/**
 * @brief Compare a certificate against the signer identifier of a CMS SignerInfo.
 * @param si SignerInfo whose sid is compared.
 * @param cert Candidate signer certificate.
 * @return 0 if @p cert matches the signer id, or non-zero otherwise.
 */
int CMS_SignerInfo_cert_cmp(CMS_SignerInfo *si, X509 *cert);
/**
 * @brief Attach signer certificates from @p certs to matching CMS SignerInfos.
 * @param cms Signed CMS ContentInfo whose SignerInfos are updated.
 * @param certs Candidate signer certificates; matching ones are referenced by the CMS structure.
 * @param flags CMS_NOINTERN and related flags controlling where certificates are taken from.
 * @return Number of SignerInfos that received a certificate, or a negative value on error.
 */
int CMS_set1_signers_certs(CMS_ContentInfo *cms, STACK_OF(X509) *certs,
    unsigned int flags);
/**
 * @brief Retrieve algorithm and key pointers from a CMS SignerInfo.
 * @param si SignerInfo to query.
 * @param pk Receives the signer's public key if available, or NULL if not requested.
 * @param signer Receives the signer certificate if available, or NULL if not requested.
 * @param pdig Receives the digest algorithm, or NULL if not requested.
 * @param psig Receives the signature algorithm, or NULL if not requested.
 */
void CMS_SignerInfo_get0_algs(CMS_SignerInfo *si, EVP_PKEY **pk,
    X509 **signer, X509_ALGOR **pdig,
    X509_ALGOR **psig);
/**
 * @brief Return a pointer to the signature OCTET STRING inside a CMS SignerInfo.
 * @param si SignerInfo whose signature value is accessed.
 * @return Internal ASN1_OCTET_STRING pointer that may be read or modified; do not free.
 */
ASN1_OCTET_STRING *CMS_SignerInfo_get0_signature(CMS_SignerInfo *si);
/**
 * @brief Explicitly finalize and sign a CMS SignerInfo (for CMS_PARTIAL with CMS_REUSE_DIGEST).
 * @param si SignerInfo that already has digest, key, and any extra signed attributes prepared.
 * @return 1 on success, or 0 on failure.
 */
int CMS_SignerInfo_sign(CMS_SignerInfo *si);
/**
 * @brief Verify the signature on a CMS SignerInfo's signed attributes.
 * @param si SignerInfo with an associated public key (for example after CMS_SignerInfo_set1_signer_cert).
 * @return 1 on success, 0 on failure, or a negative value on a more serious error.
 */
int CMS_SignerInfo_verify(CMS_SignerInfo *si);
/**
 * @brief Verify that the content digest matches a CMS SignerInfo (messageDigest or signature).
 * @param si SignerInfo whose content signature or signed messageDigest attribute is checked.
 * @param chain BIO chain supplying the signed content (as used during CMS verification).
 * @return 1 on success, 0 on failure, or a negative value on a more serious error.
 */
int CMS_SignerInfo_verify_content(CMS_SignerInfo *si, BIO *chain);
/**
 * @brief Verify a CMS SignedData structure and return a BIO of the signed content on success.
 * @param sd SignedData to verify (not freed by this call).
 * @param detached_data Detached content BIO, or NULL if content is encapsulated.
 * @param scerts Optional stack of signer certificates, or NULL.
 * @param store Trusted certificate store for chain verification, or NULL if not required by @p flags.
 * @param extra Optional extra certificates to add for chain building, or NULL.
 * @param crls Optional CRLs to add for verification, or NULL.
 * @param flags CMS verify flags (same meaning as CMS_verify()).
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query string, or NULL.
 * @return Memory BIO containing the content on success, or NULL on failure.
 */
BIO *CMS_SignedData_verify(CMS_SignedData *sd, BIO *detached_data,
    STACK_OF(X509) *scerts, X509_STORE *store,
    STACK_OF(X509) *extra, STACK_OF(X509_CRL) *crls,
    unsigned int flags,
    OSSL_LIB_CTX *libctx, const char *propq);

/**
 * @brief Encode a stack of algorithms as an SMIMECapabilities signed attribute on a SignerInfo.
 * @param si SignerInfo that receives the SMIMECapabilities attribute.
 * @param algs Stack of X509_ALGOR capability entries (for example built with CMS_add_simple_smimecap).
 * @return 1 on success, or 0 on failure.
 */
int CMS_add_smimecap(CMS_SignerInfo *si, STACK_OF(X509_ALGOR) *algs);
/**
 * @brief Append one S/MIME capability AlgorithmIdentifier to a stack.
 * @param algs Address of the stack to create or extend (may point to NULL).
 * @param algnid Algorithm NID for the capability (cipher or similar).
 * @param keysize Optional key-size parameter in bits; if <= 0, no parameter is included.
 * @return 1 on success, or 0 on failure.
 */
int CMS_add_simple_smimecap(STACK_OF(X509_ALGOR) **algs,
    int algnid, int keysize);
/**
 * @brief Populate @p smcap with a standard set of S/MIME capability AlgorithmIdentifiers.
 * @param smcap Address of the stack to create or extend (may point to NULL).
 * @return 1 on success, or 0 if any capability could not be added.
 */
int CMS_add_standard_smimecap(STACK_OF(X509_ALGOR) **smcap);

/**
 * @brief Return the number of signed attributes on a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs set is queried.
 * @return Attribute count, or -1 if signedAttrs is absent.
 */
int CMS_signed_get_attr_count(const CMS_SignerInfo *si);
/**
 * @brief Find a signed attribute in @p si by NID, searching after @p lastpos.
 * @param si SignerInfo whose signedAttrs are searched.
 * @param nid NID of the attribute OID to locate.
 * @param lastpos Index to search after, or -1 to start from the beginning.
 * @return Attribute index on success, or -1 if not found / on error.
 */
int CMS_signed_get_attr_by_NID(const CMS_SignerInfo *si, int nid,
    int lastpos);
/**
 * @brief Find the next signed attribute matching an OID in a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs are searched.
 * @param obj Attribute type OID to match.
 * @param lastpos Index after which to continue searching (-1 to start from the beginning).
 * @return Index of the matching attribute, or -1 if none is found (or on error).
 */
int CMS_signed_get_attr_by_OBJ(const CMS_SignerInfo *si, const ASN1_OBJECT *obj,
    int lastpos);
/**
 * @brief Return the signed attribute at index @p loc from a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs set is queried.
 * @param loc Zero-based attribute index (0 .. CMS_signed_get_attr_count() - 1).
 * @return Internal X509_ATTRIBUTE pointer (do not free), or NULL on error.
 */
X509_ATTRIBUTE *CMS_signed_get_attr(const CMS_SignerInfo *si, int loc);
/**
 * @brief Remove and return the signed attribute at index @p loc from a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs set is modified.
 * @param loc Zero-based index of the attribute to delete.
 * @return Removed attribute (caller frees with X509_ATTRIBUTE_free), or NULL on error.
 */
X509_ATTRIBUTE *CMS_signed_delete_attr(CMS_SignerInfo *si, int loc);
/**
 * @brief Append a copy of an X509_ATTRIBUTE to a CMS SignerInfo's signed attributes.
 * @param si SignerInfo whose signedAttrs set is extended.
 * @param attr Attribute to duplicate and append.
 * @return 1 on success, or 0 on failure.
 */
int CMS_signed_add1_attr(CMS_SignerInfo *si, X509_ATTRIBUTE *attr);
/**
 * @brief Append a signed attribute identified by ASN.1 object to a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs set is extended.
 * @param obj Attribute type OID.
 * @param type ASN.1 string type of @p bytes (for example V_ASN1_OCTET_STRING).
 * @param bytes Attribute value bytes to copy into the new X509_ATTRIBUTE.
 * @param len Length of @p bytes in octets.
 * @return 1 on success, or 0 on failure.
 */
int CMS_signed_add1_attr_by_OBJ(CMS_SignerInfo *si,
    const ASN1_OBJECT *obj, int type,
    const void *bytes, int len);
/**
 * @brief Append a signed attribute identified by NID to a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs set is extended.
 * @param nid Attribute type NID (for example NID_pkcs9_signingTime).
 * @param type ASN.1 string/type code for @p bytes (for example V_ASN1_OCTET_STRING).
 * @param bytes Attribute value bytes interpreted according to @p type.
 * @param len Length of @p bytes in bytes.
 * @return 1 on success, or 0 on failure.
 */
int CMS_signed_add1_attr_by_NID(CMS_SignerInfo *si,
    int nid, int type,
    const void *bytes, int len);
/**
 * @brief Append a signed attribute identified by short name to a CMS SignerInfo.
 * @param si SignerInfo whose signedAttrs set is extended.
 * @param attrname Attribute type name (for example an SN_* string from obj_mac.h).
 * @param type ASN.1 string type of @p bytes (for example V_ASN1_OCTET_STRING).
 * @param bytes Attribute value bytes to copy into the new X509_ATTRIBUTE.
 * @param len Length of @p bytes in octets.
 * @return 1 on success, or 0 on failure.
 */
int CMS_signed_add1_attr_by_txt(CMS_SignerInfo *si,
    const char *attrname, int type,
    const void *bytes, int len);
/**
 * @brief Return the first matching signed-attribute value of a given ASN.1 type.
 * @param si SignerInfo whose signedAttrs are searched.
 * @param oid Attribute type OID to match.
 * @param lastpos Index after which to continue searching (-1 to start from the beginning).
 * @param type Expected ASN.1 type of the attribute value (for example V_ASN1_OCTET_STRING).
 * @return Pointer to the attribute value data, or NULL if not found / type mismatch.
 */
void *CMS_signed_get0_data_by_OBJ(const CMS_SignerInfo *si,
    const ASN1_OBJECT *oid,
    int lastpos, int type);

/**
 * @brief Return how many unsigned attributes are present on a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs are counted.
 * @return Attribute count, or -1 if the unsigned attribute list is NULL.
 */
int CMS_unsigned_get_attr_count(const CMS_SignerInfo *si);
/**
 * @brief Find an unsigned attribute by NID in a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs are searched.
 * @param nid Attribute type NID to match.
 * @param lastpos Index after which to continue searching (-1 to start from the beginning).
 * @return Attribute index, or -1 if not found.
 */
int CMS_unsigned_get_attr_by_NID(const CMS_SignerInfo *si, int nid,
    int lastpos);
/**
 * @brief Find an unsigned attribute by ASN.1 object in a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs are searched.
 * @param obj Attribute type OID to match.
 * @param lastpos Index after which to continue searching (-1 to start from the beginning).
 * @return Attribute index, or -1 if not found.
 */
int CMS_unsigned_get_attr_by_OBJ(const CMS_SignerInfo *si,
    const ASN1_OBJECT *obj, int lastpos);
/**
 * @brief Return the unsigned attribute at an index in a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs are accessed.
 * @param loc Zero-based index in the range [0, CMS_unsigned_get_attr_count(si) - 1].
 * @return Internal X509_ATTRIBUTE pointer (do not free), or NULL on error.
 */
X509_ATTRIBUTE *CMS_unsigned_get_attr(const CMS_SignerInfo *si, int loc);
/**
 * @brief Remove and return the unsigned attribute at an index in a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs are modified.
 * @param loc Zero-based index of the attribute to remove.
 * @return Removed X509_ATTRIBUTE (caller owns it), or NULL on error.
 */
X509_ATTRIBUTE *CMS_unsigned_delete_attr(CMS_SignerInfo *si, int loc);
/**
 * @brief Append a copy of an X509_ATTRIBUTE to a CMS SignerInfo's unsigned attributes.
 * @param si SignerInfo whose unsignedAttrs set is extended.
 * @param attr Attribute to copy; must not be NULL.
 * @return 1 on success, or 0 on failure.
 */
int CMS_unsigned_add1_attr(CMS_SignerInfo *si, X509_ATTRIBUTE *attr);
/**
 * @brief Append an unsigned attribute identified by ASN.1 object to a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs set is extended.
 * @param obj Attribute type OID.
 * @param type ASN.1 string type of @p bytes (for example V_ASN1_OCTET_STRING).
 * @param bytes Attribute value bytes to copy into the new X509_ATTRIBUTE.
 * @param len Length of @p bytes in octets.
 * @return 1 on success, or 0 on failure.
 */
int CMS_unsigned_add1_attr_by_OBJ(CMS_SignerInfo *si,
    const ASN1_OBJECT *obj, int type,
    const void *bytes, int len);
/**
 * @brief Append an unsigned attribute identified by NID to a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs set is extended.
 * @param nid Attribute type NID (for example NID_pkcs9_signingTime).
 * @param type ASN.1 string type for @p bytes (for example V_ASN1_OCTET_STRING).
 * @param bytes Attribute value bytes, or NULL when @p len is 0.
 * @param len Length of @p bytes in octets.
 * @return 1 on success, or 0 on failure.
 */
int CMS_unsigned_add1_attr_by_NID(CMS_SignerInfo *si,
    int nid, int type,
    const void *bytes, int len);
/**
 * @brief Append an unsigned attribute identified by name to a CMS SignerInfo.
 * @param si SignerInfo whose unsignedAttrs set is extended.
 * @param attrname Attribute type name (short or long name from obj_mac.h).
 * @param type ASN.1 string type of @p bytes (for example V_ASN1_OCTET_STRING).
 * @param bytes Attribute value bytes to copy into the new X509_ATTRIBUTE.
 * @param len Length of @p bytes in octets.
 * @return 1 on success, or 0 on failure.
 */
int CMS_unsigned_add1_attr_by_txt(CMS_SignerInfo *si,
    const char *attrname, int type,
    const void *bytes, int len);
/**
 * @brief Find an unsigned attribute by OID and return its first ASN.1 value data pointer.
 * @param si SignerInfo whose unsignedAttrs are searched.
 * @param oid Attribute type object identifier to match.
 * @param lastpos Search start index; use a negative value to start from the beginning (see CMS_signed_get0_data_by_OBJ).
 * @param type Expected ASN.1 type of the attribute value (must not be V_ASN1_BOOLEAN or V_ASN1_NULL).
 * @return Pointer to the attribute value data, or NULL on error or if not found.
 */
void *CMS_unsigned_get0_data_by_OBJ(CMS_SignerInfo *si, ASN1_OBJECT *oid,
    int lastpos, int type);

/**
 * @brief Extract a CMS ReceiptRequest attribute from a SignerInfo.
 * @param si SignerInfo whose signed attributes are searched.
 * @param prr Receives a newly allocated ReceiptRequest on success; set to NULL if absent.
 * @return 1 if found, 0 if not present, or -1 on decode error.
 */
int CMS_get1_ReceiptRequest(CMS_SignerInfo *si, CMS_ReceiptRequest **prr);
/**
 * @brief Allocate a CMS signed-receipt request with the given identifiers and recipient lists.
 * @param id Receipt content identifier bytes, or NULL to generate a random id.
 * @param idlen Length of @p id in bytes; ignored when @p id is NULL.
 * @param allorfirst Non-zero to request receipts from all or first-tier recipients as encoded by CMS; see CMS_ReceiptRequest_create0(3).
 * @param receiptList Stack of GeneralNames listing who should send receipts, or NULL.
 * @param receiptsTo Stack of GeneralNames listing where receipts should be sent, or NULL.
 * @return New CMS_ReceiptRequest taking ownership of the stacks on success, or NULL on error.
 */
CMS_ReceiptRequest *CMS_ReceiptRequest_create0(
    unsigned char *id, int idlen, int allorfirst,
    STACK_OF(GENERAL_NAMES) *receiptList,
    STACK_OF(GENERAL_NAMES) *receiptsTo);
/**
 * @brief Allocate a CMS signed-receipt request using a library context for RNG.
 * @param id Receipt content identifier bytes, or NULL to generate a random id.
 * @param idlen Length of @p id in bytes; ignored when @p id is NULL.
 * @param allorfirst Value for receiptsFrom allOrFirstTier when @p receiptList is NULL.
 * @param receiptList Stack of GeneralNames listing who should send receipts, or NULL.
 * @param receiptsTo Stack of GeneralNames listing where receipts should be sent, or NULL.
 * @param libctx Library context used to obtain the public random generator, or NULL.
 * @return New CMS_ReceiptRequest taking ownership of the stacks on success, or NULL on error.
 */
CMS_ReceiptRequest *CMS_ReceiptRequest_create0_ex(
    unsigned char *id, int idlen, int allorfirst,
    STACK_OF(GENERAL_NAMES) *receiptList,
    STACK_OF(GENERAL_NAMES) *receiptsTo,
    OSSL_LIB_CTX *libctx);

/**
 * @brief Add a CMS signed receipt request to a SignerInfo.
 * @param si SignerInfo that receives the receipt request attribute.
 * @param rr Receipt request to add (caller retains ownership of @p rr).
 * @return 1 on success, or 0 on error.
 */
int CMS_add1_ReceiptRequest(CMS_SignerInfo *si, CMS_ReceiptRequest *rr);
/**
 * @brief Read the fields of a CMS ReceiptRequest without transferring ownership.
 * @param rr Receipt request to query.
 * @param pcid Receives the signedContentIdentifier, or NULL if not requested.
 * @param pallorfirst Receives allOrFirstTier when that receiptsFrom form is used, or NULL.
 * @param plist Receives the receiptList stack when that form is used, or NULL.
 * @param prto Receives the receiptsTo stack, or NULL if not requested.
 */
void CMS_ReceiptRequest_get0_values(CMS_ReceiptRequest *rr,
    ASN1_STRING **pcid,
    int *pallorfirst,
    STACK_OF(GENERAL_NAMES) **plist,
    STACK_OF(GENERAL_NAMES) **prto);
/**
 * @brief Get the key-encryption algorithm and optional UKM from a key-agreement recipient info.
 * @param ri Recipient info of type CMS_RECIPINFO_AGREE.
 * @param palg Receives the keyEncryptionAlgorithm, or NULL if not requested.
 * @param pukm Receives the user keying material (UKM), or NULL if not requested or absent.
 * @return 1 on success, or 0 if @p ri is not a key-agreement recipient info.
 */
int CMS_RecipientInfo_kari_get0_alg(CMS_RecipientInfo *ri,
    X509_ALGOR **palg,
    ASN1_OCTET_STRING **pukm);
/**
 * @brief Return the stack of RecipientEncryptedKey values from a key-agreement RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_AGREE.
 * @return Internal STACK_OF(CMS_RecipientEncryptedKey) (do not free), or NULL if @p ri is not KARI.
 */
STACK_OF(CMS_RecipientEncryptedKey)
*CMS_RecipientInfo_kari_get0_reks(CMS_RecipientInfo *ri);

/**
 * @brief Get the originator identifier from a key-agreement RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_AGREE.
 * @param pubalg Receives the originator public-key algorithm, or NULL if not requested.
 * @param pubkey Receives the originator public key BIT STRING, or NULL if not requested.
 * @param keyid Receives the originator subject key identifier, or NULL if not requested.
 * @param issuer Receives the originator issuer name, or NULL if not requested.
 * @param sno Receives the originator serial number, or NULL if not requested.
 * @return 1 on success, or 0 if @p ri is not a key-agreement recipient.
 */
int CMS_RecipientInfo_kari_get0_orig_id(CMS_RecipientInfo *ri,
    X509_ALGOR **pubalg,
    ASN1_BIT_STRING **pubkey,
    ASN1_OCTET_STRING **keyid,
    X509_NAME **issuer,
    ASN1_INTEGER **sno);

/**
 * @brief Compare a certificate against the originator identifier of a KARI RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_AGREE.
 * @param cert Candidate originator certificate.
 * @return 0 if @p cert matches, non-zero if it does not, -1 if the originator form is unsupported, or -2 if @p ri is not KARI.
 */
int CMS_RecipientInfo_kari_orig_id_cmp(CMS_RecipientInfo *ri, X509 *cert);

/**
 * @brief Extract KeyAgreeRecipientIdentifier fields from a RecipientEncryptedKey.
 * @param rek RecipientEncryptedKey to query.
 * @param keyid Receives subjectKeyIdentifier when that form is used, or NULL to skip.
 * @param tm Receives date when present with subjectKeyIdentifier, or NULL to skip.
 * @param other Receives otherKeyAttribute when present, or NULL to skip.
 * @param issuer Receives issuer name when IssuerAndSerialNumber is used, or NULL to skip.
 * @param sno Receives serial number when IssuerAndSerialNumber is used, or NULL to skip.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientEncryptedKey_get0_id(CMS_RecipientEncryptedKey *rek,
    ASN1_OCTET_STRING **keyid,
    ASN1_GENERALIZEDTIME **tm,
    CMS_OtherKeyAttribute **other,
    X509_NAME **issuer, ASN1_INTEGER **sno);
/**
 * @brief Compare a certificate against the recipient identifier of a RecipientEncryptedKey.
 * @param rek Per-recipient encrypted key from a KARI RecipientInfo.
 * @param cert Candidate recipient certificate.
 * @return 0 if @p cert matches the recipient id, non-zero if not, or -1 if the id form is unsupported.
 */
int CMS_RecipientEncryptedKey_cert_cmp(CMS_RecipientEncryptedKey *rek,
    X509 *cert);
/**
 * @brief Associate a private key with a key-agreement (KARI) CMS RecipientInfo.
 * @param ri Recipient info that must be of type CMS_RECIPINFO_AGREE.
 * @param pk Private key used for key agreement; ownership transfers to @p ri (may be NULL to clear).
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_kari_set0_pkey(CMS_RecipientInfo *ri, EVP_PKEY *pk);
/**
 * @brief Associate a private key and optional peer certificate with a key-agreement CMS RecipientInfo.
 * @param ri Recipient info that must be of type CMS_RECIPINFO_AGREE.
 * @param pk Private key used for key agreement; ownership transfers to @p ri (may be NULL to clear).
 * @param peer Peer (originator) certificate used when deriving shared secrets, or NULL when unused.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_kari_set0_pkey_and_peer(CMS_RecipientInfo *ri, EVP_PKEY *pk, X509 *peer);
/**
 * @brief Return the key-wrap cipher context associated with a key-agreement RecipientInfo.
 * @param ri Recipient info of type CMS_RECIPINFO_AGREE.
 * @return Internal EVP_CIPHER_CTX used for CEK wrap/unwrap (do not free), or NULL if @p ri is not KARI.
 */
EVP_CIPHER_CTX *CMS_RecipientInfo_kari_get0_ctx(CMS_RecipientInfo *ri);
/**
 * @brief Unwrap the content-encryption key from one KARI RecipientEncryptedKey into @p cms.
 * @param cms Enveloped ContentInfo that receives the decrypted CEK.
 * @param ri Key-agreement RecipientInfo with private key and peer material already set.
 * @param rek RecipientEncryptedKey entry that holds the wrapped CEK for this recipient.
 * @return 1 on success, or 0 on failure.
 */
int CMS_RecipientInfo_kari_decrypt(CMS_ContentInfo *cms,
    CMS_RecipientInfo *ri,
    CMS_RecipientEncryptedKey *rek);

/**
 * @brief DER-encode a CMS SharedInfo structure used in key-encryption key derivation.
 * @param pder Receives a newly allocated DER encoding on success; free with OPENSSL_free.
 * @param kekalg Key-encryption algorithm identifier placed in SharedInfo.
 * @param ukm Optional user keying material OCTET STRING, or NULL.
 * @param keylen Length in bytes of the KEK being derived (encoded as a 4-byte INTEGER).
 * @return Length of the DER encoding, or a negative value on error.
 */
int CMS_SharedInfo_encode(unsigned char **pder, X509_ALGOR *kekalg,
    ASN1_OCTET_STRING *ukm, int keylen);

/* Backward compatibility for spelling errors. */
#define CMS_R_UNKNOWN_DIGEST_ALGORITM CMS_R_UNKNOWN_DIGEST_ALGORITHM
#define CMS_R_UNSUPPORTED_RECPIENTINFO_TYPE \
    CMS_R_UNSUPPORTED_RECIPIENTINFO_TYPE

#ifdef __cplusplus
}
#endif
#endif
#endif
