/*-
 * WARNING: do not edit!
 * Generated by Makefile from include/openssl/crmf.h.in
 *
 * Copyright 2007-2023 The OpenSSL Project Authors. All Rights Reserved.
 * Copyright Nokia 2007-2019
 * Copyright Siemens AG 2015-2019
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 *
 * CRMF (RFC 4211) implementation by M. Peylo, M. Viljanen, and D. von Oheimb.
 */

/* clang-format off */

/* clang-format on */

#ifndef OPENSSL_CRMF_H
#define OPENSSL_CRMF_H

#include <openssl/opensslconf.h>

#ifndef OPENSSL_NO_CRMF
#include <openssl/opensslv.h>
#include <openssl/safestack.h>
#include <openssl/crmferr.h>
#include <openssl/x509v3.h> /* for GENERAL_NAME etc. */

/* explicit #includes not strictly needed since implied by the above: */
#include <openssl/types.h>
#include <openssl/x509.h>

#ifdef __cplusplus
extern "C" {
#endif

#define OSSL_CRMF_POPOPRIVKEY_THISMESSAGE 0
#define OSSL_CRMF_POPOPRIVKEY_SUBSEQUENTMESSAGE 1
#define OSSL_CRMF_POPOPRIVKEY_DHMAC 2
#define OSSL_CRMF_POPOPRIVKEY_AGREEMAC 3
#define OSSL_CRMF_POPOPRIVKEY_ENCRYPTEDKEY 4

#define OSSL_CRMF_SUBSEQUENTMESSAGE_ENCRCERT 0
#define OSSL_CRMF_SUBSEQUENTMESSAGE_CHALLENGERESP 1
/**
 * @brief EncryptedValue from RFC 4211: optional algorithm identifiers and an encrypted bit string.
 */
typedef struct ossl_crmf_encryptedvalue_st OSSL_CRMF_ENCRYPTEDVALUE;
/**
 * @brief Allocate an empty OSSL_CRMF_ENCRYPTEDVALUE structure.
 * @return New OSSL_CRMF_ENCRYPTEDVALUE, or NULL on allocation failure.
 */
OSSL_CRMF_ENCRYPTEDVALUE *OSSL_CRMF_ENCRYPTEDVALUE_new(void);
/**
 * @brief Free an OSSL_CRMF_ENCRYPTEDVALUE structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_ENCRYPTEDVALUE_free(OSSL_CRMF_ENCRYPTEDVALUE *a);
/**
 * @brief Decode an OSSL_CRMF_ENCRYPTEDVALUE from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_ENCRYPTEDVALUE, or NULL on error.
 */
OSSL_CRMF_ENCRYPTEDVALUE *d2i_OSSL_CRMF_ENCRYPTEDVALUE(OSSL_CRMF_ENCRYPTEDVALUE **a,
    const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_ENCRYPTEDVALUE to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_ENCRYPTEDVALUE(const OSSL_CRMF_ENCRYPTEDVALUE *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_ENCRYPTEDVALUE.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_ENCRYPTEDVALUE.
 */
const ASN1_ITEM *OSSL_CRMF_ENCRYPTEDVALUE_it(void);
/**
 * @brief CertReqMsg from RFC 4211: certificate request, optional proof-of-possession, and optional regInfo.
 */
typedef struct ossl_crmf_msg_st OSSL_CRMF_MSG;
/**
 * @brief Allocate an empty OSSL_CRMF_MSG structure.
 * @return New OSSL_CRMF_MSG, or NULL on allocation failure.
 */
OSSL_CRMF_MSG *OSSL_CRMF_MSG_new(void);
/**
 * @brief Free an OSSL_CRMF_MSG structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_MSG_free(OSSL_CRMF_MSG *a);
/**
 * @brief Decode an OSSL_CRMF_MSG from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_MSG, or NULL on error.
 */
OSSL_CRMF_MSG *d2i_OSSL_CRMF_MSG(OSSL_CRMF_MSG **a, const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_MSG to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_MSG(const OSSL_CRMF_MSG *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_MSG.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_MSG.
 */
const ASN1_ITEM *OSSL_CRMF_MSG_it(void);
/**
 * @brief Duplicate an OSSL_CRMF_MSG structure.
 * @param a Value to duplicate.
 * @return Copy of @p a, or NULL on error.
 */
OSSL_CRMF_MSG *OSSL_CRMF_MSG_dup(const OSSL_CRMF_MSG *a);
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CRMF_MSG, OSSL_CRMF_MSG, OSSL_CRMF_MSG)
#define sk_OSSL_CRMF_MSG_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CRMF_MSG_sk_type(sk))
#define sk_OSSL_CRMF_MSG_value(sk, idx) ((OSSL_CRMF_MSG *)OPENSSL_sk_value(ossl_check_const_OSSL_CRMF_MSG_sk_type(sk), (idx)))
#define sk_OSSL_CRMF_MSG_new(cmp) ((STACK_OF(OSSL_CRMF_MSG) *)OPENSSL_sk_new(ossl_check_OSSL_CRMF_MSG_compfunc_type(cmp)))
#define sk_OSSL_CRMF_MSG_new_null() ((STACK_OF(OSSL_CRMF_MSG) *)OPENSSL_sk_new_null())
#define sk_OSSL_CRMF_MSG_new_reserve(cmp, n) ((STACK_OF(OSSL_CRMF_MSG) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CRMF_MSG_compfunc_type(cmp), (n)))
#define sk_OSSL_CRMF_MSG_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CRMF_MSG_sk_type(sk), (n))
#define sk_OSSL_CRMF_MSG_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CRMF_MSG_sk_type(sk))
#define sk_OSSL_CRMF_MSG_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CRMF_MSG_sk_type(sk))
#define sk_OSSL_CRMF_MSG_delete(sk, i) ((OSSL_CRMF_MSG *)OPENSSL_sk_delete(ossl_check_OSSL_CRMF_MSG_sk_type(sk), (i)))
#define sk_OSSL_CRMF_MSG_delete_ptr(sk, ptr) ((OSSL_CRMF_MSG *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr)))
#define sk_OSSL_CRMF_MSG_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr))
#define sk_OSSL_CRMF_MSG_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr))
#define sk_OSSL_CRMF_MSG_pop(sk) ((OSSL_CRMF_MSG *)OPENSSL_sk_pop(ossl_check_OSSL_CRMF_MSG_sk_type(sk)))
#define sk_OSSL_CRMF_MSG_shift(sk) ((OSSL_CRMF_MSG *)OPENSSL_sk_shift(ossl_check_OSSL_CRMF_MSG_sk_type(sk)))
#define sk_OSSL_CRMF_MSG_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CRMF_MSG_sk_type(sk),ossl_check_OSSL_CRMF_MSG_freefunc_type(freefunc))
#define sk_OSSL_CRMF_MSG_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr), (idx))
#define sk_OSSL_CRMF_MSG_set(sk, idx, ptr) ((OSSL_CRMF_MSG *)OPENSSL_sk_set(ossl_check_OSSL_CRMF_MSG_sk_type(sk), (idx), ossl_check_OSSL_CRMF_MSG_type(ptr)))
#define sk_OSSL_CRMF_MSG_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr))
#define sk_OSSL_CRMF_MSG_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr))
#define sk_OSSL_CRMF_MSG_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_type(ptr), pnum)
#define sk_OSSL_CRMF_MSG_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CRMF_MSG_sk_type(sk))
#define sk_OSSL_CRMF_MSG_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CRMF_MSG_sk_type(sk))
#define sk_OSSL_CRMF_MSG_dup(sk) ((STACK_OF(OSSL_CRMF_MSG) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CRMF_MSG_sk_type(sk)))
#define sk_OSSL_CRMF_MSG_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CRMF_MSG) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_copyfunc_type(copyfunc), ossl_check_OSSL_CRMF_MSG_freefunc_type(freefunc)))
#define sk_OSSL_CRMF_MSG_set_cmp_func(sk, cmp) ((sk_OSSL_CRMF_MSG_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CRMF_MSG_sk_type(sk), ossl_check_OSSL_CRMF_MSG_compfunc_type(cmp)))

/* clang-format on */
/**
 * @brief AttributeTypeAndValue for CRMF regCtrl or regInfo attributes.
 */
typedef struct ossl_crmf_attributetypeandvalue_st OSSL_CRMF_ATTRIBUTETYPEANDVALUE;
/**
 * @brief PBMParameter from RFC 4211: salt, one-way function, iteration count, and MAC algorithm.
 */
typedef struct ossl_crmf_pbmparameter_st OSSL_CRMF_PBMPARAMETER;
/**
 * @brief Allocate an empty OSSL_CRMF_PBMPARAMETER structure.
 * @return New OSSL_CRMF_PBMPARAMETER, or NULL on allocation failure.
 */
OSSL_CRMF_PBMPARAMETER *OSSL_CRMF_PBMPARAMETER_new(void);
/**
 * @brief Free an OSSL_CRMF_PBMPARAMETER structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_PBMPARAMETER_free(OSSL_CRMF_PBMPARAMETER *a);
/**
 * @brief Decode an OSSL_CRMF_PBMPARAMETER from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_PBMPARAMETER, or NULL on error.
 */
OSSL_CRMF_PBMPARAMETER *d2i_OSSL_CRMF_PBMPARAMETER(OSSL_CRMF_PBMPARAMETER **a,
    const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_PBMPARAMETER to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_PBMPARAMETER(const OSSL_CRMF_PBMPARAMETER *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_PBMPARAMETER.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_PBMPARAMETER.
 */
const ASN1_ITEM *OSSL_CRMF_PBMPARAMETER_it(void);
/**
 * @brief POPOSigningKey from RFC 4211: optional POPOSigningKeyInput, algorithm identifier, and signature.
 */
typedef struct ossl_crmf_poposigningkey_st OSSL_CRMF_POPOSIGNINGKEY;
/**
 * @brief CertRequest from RFC 4211: certReqId, certTemplate, and optional controls.
 */
typedef struct ossl_crmf_certrequest_st OSSL_CRMF_CERTREQUEST;
/**
 * @brief CertId from RFC 4211: issuer GeneralName and certificate serial number.
 */
typedef struct ossl_crmf_certid_st OSSL_CRMF_CERTID;
/**
 * @brief Allocate an empty OSSL_CRMF_CERTID structure.
 * @return New OSSL_CRMF_CERTID, or NULL on allocation failure.
 */
OSSL_CRMF_CERTID *OSSL_CRMF_CERTID_new(void);
/**
 * @brief Free an OSSL_CRMF_CERTID structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_CERTID_free(OSSL_CRMF_CERTID *a);
/**
 * @brief Decode an OSSL_CRMF_CERTID from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_CERTID, or NULL on error.
 */
OSSL_CRMF_CERTID *d2i_OSSL_CRMF_CERTID(OSSL_CRMF_CERTID **a, const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_CERTID to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_CERTID(const OSSL_CRMF_CERTID *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_CERTID.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_CERTID.
 */
const ASN1_ITEM *OSSL_CRMF_CERTID_it(void);
/**
 * @brief Duplicate an OSSL_CRMF_CERTID structure.
 * @param a Value to duplicate.
 * @return Copy of @p a, or NULL on error.
 */
OSSL_CRMF_CERTID *OSSL_CRMF_CERTID_dup(const OSSL_CRMF_CERTID *a);
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(OSSL_CRMF_CERTID, OSSL_CRMF_CERTID, OSSL_CRMF_CERTID)
#define sk_OSSL_CRMF_CERTID_num(sk) OPENSSL_sk_num(ossl_check_const_OSSL_CRMF_CERTID_sk_type(sk))
#define sk_OSSL_CRMF_CERTID_value(sk, idx) ((OSSL_CRMF_CERTID *)OPENSSL_sk_value(ossl_check_const_OSSL_CRMF_CERTID_sk_type(sk), (idx)))
#define sk_OSSL_CRMF_CERTID_new(cmp) ((STACK_OF(OSSL_CRMF_CERTID) *)OPENSSL_sk_new(ossl_check_OSSL_CRMF_CERTID_compfunc_type(cmp)))
#define sk_OSSL_CRMF_CERTID_new_null() ((STACK_OF(OSSL_CRMF_CERTID) *)OPENSSL_sk_new_null())
#define sk_OSSL_CRMF_CERTID_new_reserve(cmp, n) ((STACK_OF(OSSL_CRMF_CERTID) *)OPENSSL_sk_new_reserve(ossl_check_OSSL_CRMF_CERTID_compfunc_type(cmp), (n)))
#define sk_OSSL_CRMF_CERTID_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), (n))
#define sk_OSSL_CRMF_CERTID_free(sk) OPENSSL_sk_free(ossl_check_OSSL_CRMF_CERTID_sk_type(sk))
#define sk_OSSL_CRMF_CERTID_zero(sk) OPENSSL_sk_zero(ossl_check_OSSL_CRMF_CERTID_sk_type(sk))
#define sk_OSSL_CRMF_CERTID_delete(sk, i) ((OSSL_CRMF_CERTID *)OPENSSL_sk_delete(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), (i)))
#define sk_OSSL_CRMF_CERTID_delete_ptr(sk, ptr) ((OSSL_CRMF_CERTID *)OPENSSL_sk_delete_ptr(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr)))
#define sk_OSSL_CRMF_CERTID_push(sk, ptr) OPENSSL_sk_push(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr))
#define sk_OSSL_CRMF_CERTID_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr))
#define sk_OSSL_CRMF_CERTID_pop(sk) ((OSSL_CRMF_CERTID *)OPENSSL_sk_pop(ossl_check_OSSL_CRMF_CERTID_sk_type(sk)))
#define sk_OSSL_CRMF_CERTID_shift(sk) ((OSSL_CRMF_CERTID *)OPENSSL_sk_shift(ossl_check_OSSL_CRMF_CERTID_sk_type(sk)))
#define sk_OSSL_CRMF_CERTID_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_OSSL_CRMF_CERTID_sk_type(sk),ossl_check_OSSL_CRMF_CERTID_freefunc_type(freefunc))
#define sk_OSSL_CRMF_CERTID_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr), (idx))
#define sk_OSSL_CRMF_CERTID_set(sk, idx, ptr) ((OSSL_CRMF_CERTID *)OPENSSL_sk_set(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), (idx), ossl_check_OSSL_CRMF_CERTID_type(ptr)))
#define sk_OSSL_CRMF_CERTID_find(sk, ptr) OPENSSL_sk_find(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr))
#define sk_OSSL_CRMF_CERTID_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr))
#define sk_OSSL_CRMF_CERTID_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_type(ptr), pnum)
#define sk_OSSL_CRMF_CERTID_sort(sk) OPENSSL_sk_sort(ossl_check_OSSL_CRMF_CERTID_sk_type(sk))
#define sk_OSSL_CRMF_CERTID_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_OSSL_CRMF_CERTID_sk_type(sk))
#define sk_OSSL_CRMF_CERTID_dup(sk) ((STACK_OF(OSSL_CRMF_CERTID) *)OPENSSL_sk_dup(ossl_check_const_OSSL_CRMF_CERTID_sk_type(sk)))
#define sk_OSSL_CRMF_CERTID_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(OSSL_CRMF_CERTID) *)OPENSSL_sk_deep_copy(ossl_check_const_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_copyfunc_type(copyfunc), ossl_check_OSSL_CRMF_CERTID_freefunc_type(freefunc)))
#define sk_OSSL_CRMF_CERTID_set_cmp_func(sk, cmp) ((sk_OSSL_CRMF_CERTID_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_OSSL_CRMF_CERTID_sk_type(sk), ossl_check_OSSL_CRMF_CERTID_compfunc_type(cmp)))

/* clang-format on */

/**
 * @brief PKIPublicationInfo from RFC 4211 section 6.3: publication action and optional SinglePubInfo list.
 */
typedef struct ossl_crmf_pkipublicationinfo_st OSSL_CRMF_PKIPUBLICATIONINFO;
/**
 * @brief Allocate an empty OSSL_CRMF_PKIPUBLICATIONINFO structure.
 * @return New OSSL_CRMF_PKIPUBLICATIONINFO, or NULL on allocation failure.
 */
OSSL_CRMF_PKIPUBLICATIONINFO *OSSL_CRMF_PKIPUBLICATIONINFO_new(void);
/**
 * @brief Free an OSSL_CRMF_PKIPUBLICATIONINFO structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_PKIPUBLICATIONINFO_free(OSSL_CRMF_PKIPUBLICATIONINFO *a);
/**
 * @brief Decode an OSSL_CRMF_PKIPUBLICATIONINFO from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_PKIPUBLICATIONINFO, or NULL on error.
 */
OSSL_CRMF_PKIPUBLICATIONINFO *d2i_OSSL_CRMF_PKIPUBLICATIONINFO(OSSL_CRMF_PKIPUBLICATIONINFO **a,
    const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_PKIPUBLICATIONINFO to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_PKIPUBLICATIONINFO(const OSSL_CRMF_PKIPUBLICATIONINFO *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_PKIPUBLICATIONINFO.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_PKIPUBLICATIONINFO.
 */
const ASN1_ITEM *OSSL_CRMF_PKIPUBLICATIONINFO_it(void);
/**
 * @brief SinglePubInfo from RFC 4211: publication method and optional publication location.
 */
typedef struct ossl_crmf_singlepubinfo_st OSSL_CRMF_SINGLEPUBINFO;
/**
 * @brief Allocate an empty OSSL_CRMF_SINGLEPUBINFO structure.
 * @return New OSSL_CRMF_SINGLEPUBINFO, or NULL on allocation failure.
 */
OSSL_CRMF_SINGLEPUBINFO *OSSL_CRMF_SINGLEPUBINFO_new(void);
/**
 * @brief Free an OSSL_CRMF_SINGLEPUBINFO structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_SINGLEPUBINFO_free(OSSL_CRMF_SINGLEPUBINFO *a);
/**
 * @brief Decode an OSSL_CRMF_SINGLEPUBINFO from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_SINGLEPUBINFO, or NULL on error.
 */
OSSL_CRMF_SINGLEPUBINFO *d2i_OSSL_CRMF_SINGLEPUBINFO(OSSL_CRMF_SINGLEPUBINFO **a,
    const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_SINGLEPUBINFO to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_SINGLEPUBINFO(const OSSL_CRMF_SINGLEPUBINFO *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_SINGLEPUBINFO.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_SINGLEPUBINFO.
 */
const ASN1_ITEM *OSSL_CRMF_SINGLEPUBINFO_it(void);
/**
 * @brief CertTemplate from RFC 4211: selected certificate fields for a requested certificate.
 */
typedef struct ossl_crmf_certtemplate_st OSSL_CRMF_CERTTEMPLATE;
/**
 * @brief Allocate an empty OSSL_CRMF_CERTTEMPLATE structure.
 * @return New OSSL_CRMF_CERTTEMPLATE, or NULL on allocation failure.
 */
OSSL_CRMF_CERTTEMPLATE *OSSL_CRMF_CERTTEMPLATE_new(void);
/**
 * @brief Free an OSSL_CRMF_CERTTEMPLATE structure and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_CERTTEMPLATE_free(OSSL_CRMF_CERTTEMPLATE *a);
/**
 * @brief Decode an OSSL_CRMF_CERTTEMPLATE from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_CERTTEMPLATE, or NULL on error.
 */
OSSL_CRMF_CERTTEMPLATE *d2i_OSSL_CRMF_CERTTEMPLATE(OSSL_CRMF_CERTTEMPLATE **a,
    const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_CERTTEMPLATE to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_CERTTEMPLATE(const OSSL_CRMF_CERTTEMPLATE *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_CERTTEMPLATE.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_CERTTEMPLATE.
 */
const ASN1_ITEM *OSSL_CRMF_CERTTEMPLATE_it(void);
/**
 * @brief CertReqMessages from RFC 4211: a sequence of CertReqMsg values.
 */
typedef STACK_OF(OSSL_CRMF_MSG) OSSL_CRMF_MSGS;
/**
 * @brief Allocate an empty OSSL_CRMF_MSGS stack.
 * @return New OSSL_CRMF_MSGS, or NULL on allocation failure.
 */
OSSL_CRMF_MSGS *OSSL_CRMF_MSGS_new(void);
/**
 * @brief Free an OSSL_CRMF_MSGS stack and its contents.
 * @param a Value to free, or NULL.
 */
void OSSL_CRMF_MSGS_free(OSSL_CRMF_MSGS *a);
/**
 * @brief Decode an OSSL_CRMF_MSGS sequence from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded OSSL_CRMF_MSGS, or NULL on error.
 */
OSSL_CRMF_MSGS *d2i_OSSL_CRMF_MSGS(OSSL_CRMF_MSGS **a, const unsigned char **in, long len);
/**
 * @brief Encode an OSSL_CRMF_MSGS sequence to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_OSSL_CRMF_MSGS(const OSSL_CRMF_MSGS *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for OSSL_CRMF_MSGS.
 * @return Pointer to the static ASN1_ITEM for OSSL_CRMF_MSGS.
 */
const ASN1_ITEM *OSSL_CRMF_MSGS_it(void);

/**
 * @brief OptionalValidity from RFC 4211: optional notBefore and notAfter times in a certTemplate.
 */
typedef struct ossl_crmf_optionalvalidity_st OSSL_CRMF_OPTIONALVALIDITY;

/* crmf_pbm.c */
/**
 * @brief Create a PBMParameter for password-based MAC POPO (RFC 4211 section 4.4).
 * @param libctx Library context for algorithm fetching, or NULL for the default.
 * @param slen Length of the random salt in bytes.
 * @param owfnid NID of the one-way function digest.
 * @param itercnt OWF iteration count.
 * @param macnid NID of the MAC algorithm.
 * @return New PBMParameter, or NULL on error.
 */
OSSL_CRMF_PBMPARAMETER *OSSL_CRMF_pbmp_new(OSSL_LIB_CTX *libctx, size_t slen,
    int owfnid, size_t itercnt,
    int macnid);
/**
 * @brief Compute a Password-Based MAC (PBM) for CRMF POPO using the given parameters, message, and secret.
 * @param libctx Library context for algorithm fetching, or NULL for the default.
 * @param propq Property query for the MAC algorithm, or NULL.
 * @param pbmp PBMParameter describing salt, OWF, iteration count, and MAC.
 * @param msg Message octets to authenticate.
 * @param msglen Length of @p msg in bytes.
 * @param sec Shared secret / password octets.
 * @param seclen Length of @p sec in bytes.
 * @param mac On success, receives a newly allocated MAC buffer (caller frees with OPENSSL_free()).
 * @param maclen Optional; on success receives the MAC length in bytes when non-NULL.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_pbm_new(OSSL_LIB_CTX *libctx, const char *propq,
    const OSSL_CRMF_PBMPARAMETER *pbmp,
    const unsigned char *msg, size_t msglen,
    const unsigned char *sec, size_t seclen,
    unsigned char **mac, size_t *maclen);

/* crmf_lib.c */
/**
 * @brief Set the regToken regCtrl in a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param tok Registration token value to copy; see RFC 4211 section 6.1.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regCtrl_regToken(OSSL_CRMF_MSG *msg,
    const ASN1_UTF8STRING *tok);
/**
 * @brief Return the regToken regCtrl from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal regToken pointer, or NULL if absent.
 */
ASN1_UTF8STRING
*OSSL_CRMF_MSG_get0_regCtrl_regToken(const OSSL_CRMF_MSG *msg);
/**
 * @brief Set the authenticator regCtrl in a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param auth Authenticator value to copy; see RFC 4211 section 6.2.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regCtrl_authenticator(OSSL_CRMF_MSG *msg,
    const ASN1_UTF8STRING *auth);
/**
 * @brief Return the authenticator regCtrl from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal authenticator pointer, or NULL if absent or on error.
 */
ASN1_UTF8STRING
*OSSL_CRMF_MSG_get0_regCtrl_authenticator(const OSSL_CRMF_MSG *msg);
/**
 * @brief Append a SinglePubInfo to a PKIPublicationInfo pubInfos list.
 * @param pi PKIPublicationInfo to update.
 * @param spi SinglePubInfo to append; ownership is transferred to @p pi.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_PKIPublicationInfo_push0_SinglePubInfo(OSSL_CRMF_PKIPUBLICATIONINFO *pi,
    OSSL_CRMF_SINGLEPUBINFO *spi);
#define OSSL_CRMF_PUB_METHOD_DONTCARE 0
#define OSSL_CRMF_PUB_METHOD_X500 1
#define OSSL_CRMF_PUB_METHOD_WEB 2
#define OSSL_CRMF_PUB_METHOD_LDAP 3
/**
 * @brief Set publication method and optional location in a SinglePubInfo.
 * @param spi SinglePubInfo to update.
 * @param method Publication method (OSSL_CRMF_PUB_METHOD_*).
 * @param nm Optional publication location as a GeneralName; ownership is transferred when non-NULL.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set0_SinglePubInfo(OSSL_CRMF_SINGLEPUBINFO *spi,
    int method, GENERAL_NAME *nm);
#define OSSL_CRMF_PUB_ACTION_DONTPUBLISH 0
#define OSSL_CRMF_PUB_ACTION_PLEASEPUBLISH 1
/**
 * @brief Set the publication action in a PKIPublicationInfo.
 * @param pi PKIPublicationInfo to update.
 * @param action Publication action (OSSL_CRMF_PUB_ACTION_*); see RFC 4211 section 6.3.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set_PKIPublicationInfo_action(OSSL_CRMF_PKIPUBLICATIONINFO *pi,
    int action);
/**
 * @brief Set the pkiPublicationInfo regCtrl in a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param pi PKIPublicationInfo value to copy; see RFC 4211 section 6.3.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regCtrl_pkiPublicationInfo(OSSL_CRMF_MSG *msg,
    const OSSL_CRMF_PKIPUBLICATIONINFO *pi);
/**
 * @brief Return the pkiPublicationInfo regCtrl from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal PKIPublicationInfo pointer, or NULL if absent; see RFC 4211 section 6.3.
 */
OSSL_CRMF_PKIPUBLICATIONINFO
*OSSL_CRMF_MSG_get0_regCtrl_pkiPublicationInfo(const OSSL_CRMF_MSG *msg);
/**
 * @brief Set the protocolEncrKey regCtrl in a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param pubkey Protocol encryption public key to copy; see RFC 4211 section 6.6.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regCtrl_protocolEncrKey(OSSL_CRMF_MSG *msg,
    const X509_PUBKEY *pubkey);
/**
 * @brief Return the protocolEncrKey regCtrl from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal protocol encryption public key, or NULL if absent; see RFC 4211 section 6.6.
 */
X509_PUBKEY
*OSSL_CRMF_MSG_get0_regCtrl_protocolEncrKey(const OSSL_CRMF_MSG *msg);
/**
 * @brief Set the oldCertID regCtrl in a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param cid CertId identifying the certificate being renewed; copied into the message.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regCtrl_oldCertID(OSSL_CRMF_MSG *msg,
    const OSSL_CRMF_CERTID *cid);
/**
 * @brief Return the oldCertID regCtrl from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal CertId of the certificate being renewed, or NULL if absent; see RFC 4211 section 6.5.
 */
OSSL_CRMF_CERTID
*OSSL_CRMF_MSG_get0_regCtrl_oldCertID(const OSSL_CRMF_MSG *msg);
/**
 * @brief Create an OSSL_CRMF_CERTID from an issuer name and serial number.
 * @param issuer Issuer distinguished name to copy into the CertId.
 * @param serial Certificate serial number to copy into the CertId.
 * @return New OSSL_CRMF_CERTID, or NULL on error; free with OSSL_CRMF_CERTID_free().
 */
OSSL_CRMF_CERTID *OSSL_CRMF_CERTID_gen(const X509_NAME *issuer,
    const ASN1_INTEGER *serial);

/**
 * @brief Set the utf8Pairs regInfo in a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param utf8pairs UTF-8 string value to copy into regInfo.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regInfo_utf8Pairs(OSSL_CRMF_MSG *msg,
    const ASN1_UTF8STRING *utf8pairs);
/**
 * @brief Return the first utf8Pairs regInfo from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal utf8Pairs pointer, or NULL if absent.
 */
ASN1_UTF8STRING
*OSSL_CRMF_MSG_get0_regInfo_utf8Pairs(const OSSL_CRMF_MSG *msg);
/**
 * @brief Add a copy of a certReq regInfo value to a CRMF CertReqMsg.
 * @param msg CertReqMsg to update.
 * @param cr CertRequest value to copy; see RFC 4211 section 7.2.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set1_regInfo_certReq(OSSL_CRMF_MSG *msg,
    const OSSL_CRMF_CERTREQUEST *cr);
/**
 * @brief Return the first certReq regInfo from a CRMF CertReqMsg, if present.
 * @param msg CertReqMsg to query.
 * @return Internal certReq pointer, or NULL if absent.
 */
OSSL_CRMF_CERTREQUEST
*OSSL_CRMF_MSG_get0_regInfo_certReq(const OSSL_CRMF_MSG *msg);

/**
 * @brief Set optional validity times in the certTemplate of a CRMF CertReqMsg.
 * @param crm CertReqMsg to update.
 * @param notBefore Optional notBefore time; ownership transfers when non-NULL.
 * @param notAfter Optional notAfter time; ownership transfers when non-NULL.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set0_validity(OSSL_CRMF_MSG *crm,
    ASN1_TIME *notBefore, ASN1_TIME *notAfter);
/**
 * @brief Set the certReqId field in a CRMF CertReqMsg.
 * @param crm CertReqMsg to update.
 * @param rid Certificate request ID as a nonnegative integer.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set_certReqId(OSSL_CRMF_MSG *crm, int rid);
/**
 * @brief Return the certReqId from a CRMF CertReqMsg.
 * @param crm CertReqMsg to query.
 * @return Certificate request ID as a nonnegative integer, or -1 on error.
 */
int OSSL_CRMF_MSG_get_certReqId(const OSSL_CRMF_MSG *crm);
/**
 * @brief Set X.509 extensions in the certTemplate of a CRMF CertReqMsg.
 * @param crm CertReqMsg to update.
 * @param exts Extensions stack to install; any previous extensions are freed and ownership of @p exts is transferred.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_set0_extensions(OSSL_CRMF_MSG *crm, X509_EXTENSIONS *exts);

/**
 * @brief Append an X.509 extension to the certTemplate of a CRMF CertReqMsg.
 * @param crm CertReqMsg to update.
 * @param ext Extension to push; ownership is transferred to @p crm.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_push0_extension(OSSL_CRMF_MSG *crm, X509_EXTENSION *ext);
#define OSSL_CRMF_POPO_NONE -1
#define OSSL_CRMF_POPO_RAVERIFIED 0
#define OSSL_CRMF_POPO_SIGNATURE 1
#define OSSL_CRMF_POPO_KEYENC 2
#define OSSL_CRMF_POPO_KEYAGREE 3
/**
 * @brief Create and set the Proof-of-Possession field in a CRMF CertReqMsg.
 * @param meth POPO method (OSSL_CRMF_POPO_*); see RFC 4211 section 4.
 * @param crm CertReqMsg to update.
 * @param pkey Private key used when @p meth is OSSL_CRMF_POPO_SIGNATURE.
 * @param digest Digest for signature POPO; ignored for Ed25519/Ed448 keys.
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for algorithm fetches, or NULL.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_MSG_create_popo(int meth, OSSL_CRMF_MSG *crm,
    EVP_PKEY *pkey, const EVP_MD *digest,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Verify proof-of-possession on a CRMF CertReqMessages sequence.
 * @param reqs CertReqMessages to verify.
 * @param rid certReqId of the message to verify, or -1 to verify all messages.
 * @param acceptRAVerified Non-zero to accept POPO raVerified without further checks.
 * @param libctx Library context for algorithm fetching, or NULL for the default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 if POPO verifies, 0 if not, or -1 on error.
 */
int OSSL_CRMF_MSGS_verify_popo(const OSSL_CRMF_MSGS *reqs,
    int rid, int acceptRAVerified,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Return the certTemplate from a CRMF CertReqMsg.
 * @param crm CertReqMsg to query.
 * @return Internal certTemplate pointer, or NULL on error.
 */
OSSL_CRMF_CERTTEMPLATE *OSSL_CRMF_MSG_get0_tmpl(const OSSL_CRMF_MSG *crm);
/**
 * @brief Return the public key from a CRMF CertTemplate.
 * @param tmpl CertTemplate to query.
 * @return Internal public key pointer, or NULL if absent or on error.
 */
X509_PUBKEY
*OSSL_CRMF_CERTTEMPLATE_get0_publicKey(const OSSL_CRMF_CERTTEMPLATE *tmpl);
/**
 * @brief Return the subject name from a CRMF CertTemplate.
 * @param tmpl CertTemplate to query.
 * @return Internal subject name pointer, or NULL if absent or on error.
 */
const X509_NAME *OSSL_CRMF_CERTTEMPLATE_get0_subject(const OSSL_CRMF_CERTTEMPLATE *tmpl);
/**
 * @brief Return the issuer name from a CRMF CertTemplate.
 * @param tmpl CertTemplate to query.
 * @return Internal issuer name pointer, or NULL if absent or on error.
 */
const X509_NAME *OSSL_CRMF_CERTTEMPLATE_get0_issuer(const OSSL_CRMF_CERTTEMPLATE *tmpl);
/**
 * @brief Return the serial number from a CRMF CertTemplate.
 * @param tmpl CertTemplate to query.
 * @return Internal serial number pointer, or NULL if absent or on error.
 */
const ASN1_INTEGER *OSSL_CRMF_CERTTEMPLATE_get0_serialNumber(const OSSL_CRMF_CERTTEMPLATE *tmpl);
/**
 * @brief Return the X.509 extensions from a CRMF CertTemplate.
 * @param tmpl CertTemplate to query.
 * @return Internal extensions stack, or NULL if absent or on error.
 */
X509_EXTENSIONS
*OSSL_CRMF_CERTTEMPLATE_get0_extensions(const OSSL_CRMF_CERTTEMPLATE *tmpl);
/**
 * @brief Return the issuer name from a CRMF CertId.
 * @param cid CertId to query.
 * @return Internal issuer name pointer, or NULL if absent or on error.
 */
const X509_NAME *OSSL_CRMF_CERTID_get0_issuer(const OSSL_CRMF_CERTID *cid);
/**
 * @brief Return the serial number from a CRMF CertId.
 * @param cid CertId to query.
 * @return Internal serial number pointer, or NULL if absent or on error.
 */
const ASN1_INTEGER *OSSL_CRMF_CERTID_get0_serialNumber(const OSSL_CRMF_CERTID *cid);
/**
 * @brief Populate selected fields of a CRMF CertTemplate.
 * @param tmpl CertTemplate to update.
 * @param pubkey Optional public key; reference count is incremented when non-NULL.
 * @param subject Optional subject name to copy.
 * @param issuer Optional issuer name to copy.
 * @param serial Optional serial number to copy.
 * @return 1 on success, or 0 on error.
 */
int OSSL_CRMF_CERTTEMPLATE_fill(OSSL_CRMF_CERTTEMPLATE *tmpl,
    EVP_PKEY *pubkey,
    const X509_NAME *subject,
    const X509_NAME *issuer,
    const ASN1_INTEGER *serial);
/**
 * @brief Decrypt the certificate held in an EncryptedValue.
 * @param ecert EncryptedValue containing the encrypted certificate.
 * @param libctx Library context for algorithm fetches, or NULL for the default.
 * @param propq Property query for algorithm fetches, or NULL.
 * @param pkey Private key used to decrypt the certificate (indirect POPO; RFC 4210 section 5.2.8.2).
 * @return Decrypted X509 certificate copy owned by the caller, or NULL on error; free with X509_free().
 */
X509 *OSSL_CRMF_ENCRYPTEDVALUE_get1_encCert(const OSSL_CRMF_ENCRYPTEDVALUE *ecert,
    OSSL_LIB_CTX *libctx, const char *propq,
    EVP_PKEY *pkey);

#ifdef __cplusplus
}
#endif
#endif /* !defined(OPENSSL_NO_CRMF) */
#endif /* !defined(OPENSSL_CRMF_H) */
