/*
 * WARNING: do not edit!
 * Generated by Makefile from include/openssl/pkcs12.h.in
 *
 * Copyright 1999-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

/* clang-format off */

/* clang-format on */

#ifndef OPENSSL_PKCS12_H
#define OPENSSL_PKCS12_H
#pragma once

#include <openssl/macros.h>
#ifndef OPENSSL_NO_DEPRECATED_3_0
#define HEADER_PKCS12_H
#endif

#include <openssl/bio.h>
#include <openssl/core.h>
#include <openssl/x509.h>
#include <openssl/pkcs12err.h>
#ifndef OPENSSL_NO_STDIO
#include <stdio.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define PKCS12_KEY_ID 1
#define PKCS12_IV_ID 2
#define PKCS12_MAC_ID 3

/* Default iteration count */
#ifndef PKCS12_DEFAULT_ITER
#define PKCS12_DEFAULT_ITER PKCS5_DEFAULT_ITER
#endif

#define PKCS12_MAC_KEY_LENGTH 20

/* The macro is expected to be used only internally. Kept for backwards compatibility. */
#define PKCS12_SALT_LEN 8

/* It's not clear if these are actually needed... */
#define PKCS12_key_gen PKCS12_key_gen_utf8
#define PKCS12_add_friendlyname PKCS12_add_friendlyname_utf8

/* MS key usage constants */

#define KEY_EX 0x10
#define KEY_SIG 0x80

/**
 * @brief MAC salt, iteration count, and digest algorithm for a PKCS#12 PFX integrity check.
 */
typedef struct PKCS12_MAC_DATA_st PKCS12_MAC_DATA;

/**
 * @brief Top-level PKCS#12 PFX structure (version, authSafes, and optional MAC).
 */
typedef struct PKCS12_st PKCS12;

/**
 * @brief One PKCS#12 safeBag holding a certificate, key, CRL, secret, or nested safeContents.
 */
typedef struct PKCS12_SAFEBAG_st PKCS12_SAFEBAG;

/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(PKCS12_SAFEBAG, PKCS12_SAFEBAG, PKCS12_SAFEBAG)
#define sk_PKCS12_SAFEBAG_num(sk) OPENSSL_sk_num(ossl_check_const_PKCS12_SAFEBAG_sk_type(sk))
#define sk_PKCS12_SAFEBAG_value(sk, idx) ((PKCS12_SAFEBAG *)OPENSSL_sk_value(ossl_check_const_PKCS12_SAFEBAG_sk_type(sk), (idx)))
#define sk_PKCS12_SAFEBAG_new(cmp) ((STACK_OF(PKCS12_SAFEBAG) *)OPENSSL_sk_new(ossl_check_PKCS12_SAFEBAG_compfunc_type(cmp)))
#define sk_PKCS12_SAFEBAG_new_null() ((STACK_OF(PKCS12_SAFEBAG) *)OPENSSL_sk_new_null())
#define sk_PKCS12_SAFEBAG_new_reserve(cmp, n) ((STACK_OF(PKCS12_SAFEBAG) *)OPENSSL_sk_new_reserve(ossl_check_PKCS12_SAFEBAG_compfunc_type(cmp), (n)))
#define sk_PKCS12_SAFEBAG_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_PKCS12_SAFEBAG_sk_type(sk), (n))
#define sk_PKCS12_SAFEBAG_free(sk) OPENSSL_sk_free(ossl_check_PKCS12_SAFEBAG_sk_type(sk))
#define sk_PKCS12_SAFEBAG_zero(sk) OPENSSL_sk_zero(ossl_check_PKCS12_SAFEBAG_sk_type(sk))
#define sk_PKCS12_SAFEBAG_delete(sk, i) ((PKCS12_SAFEBAG *)OPENSSL_sk_delete(ossl_check_PKCS12_SAFEBAG_sk_type(sk), (i)))
#define sk_PKCS12_SAFEBAG_delete_ptr(sk, ptr) ((PKCS12_SAFEBAG *)OPENSSL_sk_delete_ptr(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr)))
#define sk_PKCS12_SAFEBAG_push(sk, ptr) OPENSSL_sk_push(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr))
#define sk_PKCS12_SAFEBAG_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr))
#define sk_PKCS12_SAFEBAG_pop(sk) ((PKCS12_SAFEBAG *)OPENSSL_sk_pop(ossl_check_PKCS12_SAFEBAG_sk_type(sk)))
#define sk_PKCS12_SAFEBAG_shift(sk) ((PKCS12_SAFEBAG *)OPENSSL_sk_shift(ossl_check_PKCS12_SAFEBAG_sk_type(sk)))
#define sk_PKCS12_SAFEBAG_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_PKCS12_SAFEBAG_sk_type(sk),ossl_check_PKCS12_SAFEBAG_freefunc_type(freefunc))
#define sk_PKCS12_SAFEBAG_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr), (idx))
#define sk_PKCS12_SAFEBAG_set(sk, idx, ptr) ((PKCS12_SAFEBAG *)OPENSSL_sk_set(ossl_check_PKCS12_SAFEBAG_sk_type(sk), (idx), ossl_check_PKCS12_SAFEBAG_type(ptr)))
#define sk_PKCS12_SAFEBAG_find(sk, ptr) OPENSSL_sk_find(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr))
#define sk_PKCS12_SAFEBAG_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr))
#define sk_PKCS12_SAFEBAG_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_type(ptr), pnum)
#define sk_PKCS12_SAFEBAG_sort(sk) OPENSSL_sk_sort(ossl_check_PKCS12_SAFEBAG_sk_type(sk))
#define sk_PKCS12_SAFEBAG_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_PKCS12_SAFEBAG_sk_type(sk))
#define sk_PKCS12_SAFEBAG_dup(sk) ((STACK_OF(PKCS12_SAFEBAG) *)OPENSSL_sk_dup(ossl_check_const_PKCS12_SAFEBAG_sk_type(sk)))
#define sk_PKCS12_SAFEBAG_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(PKCS12_SAFEBAG) *)OPENSSL_sk_deep_copy(ossl_check_const_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_copyfunc_type(copyfunc), ossl_check_PKCS12_SAFEBAG_freefunc_type(freefunc)))
#define sk_PKCS12_SAFEBAG_set_cmp_func(sk, cmp) ((sk_PKCS12_SAFEBAG_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_PKCS12_SAFEBAG_sk_type(sk), ossl_check_PKCS12_SAFEBAG_compfunc_type(cmp)))

/* clang-format on */


/**
 * @brief Bag payload choice structure (certBag, crlBag, secretBag, or other ASN.1 value).
 */
typedef struct pkcs12_bag_st PKCS12_BAGS;

#define PKCS12_ERROR 0
#define PKCS12_OK 1

/* Compatibility macros */

#ifndef OPENSSL_NO_DEPRECATED_1_1_0

#define M_PKCS12_bag_type PKCS12_bag_type
#define M_PKCS12_cert_bag_type PKCS12_cert_bag_type
#define M_PKCS12_crl_bag_type PKCS12_cert_bag_type

#define PKCS12_certbag2x509 PKCS12_SAFEBAG_get1_cert
#define PKCS12_certbag2scrl PKCS12_SAFEBAG_get1_crl
#define PKCS12_bag_type PKCS12_SAFEBAG_get_nid
#define PKCS12_cert_bag_type PKCS12_SAFEBAG_get_bag_nid
#define PKCS12_x5092certbag PKCS12_SAFEBAG_create_cert
#define PKCS12_x509crl2certbag PKCS12_SAFEBAG_create_crl
#define PKCS12_MAKE_KEYBAG PKCS12_SAFEBAG_create0_p8inf
#define PKCS12_MAKE_SHKEYBAG PKCS12_SAFEBAG_create_pkcs8_encrypt

#endif
#ifndef OPENSSL_NO_DEPRECATED_1_1_0
/**
 * @brief Retrieve a PKCS#12 safeBag attribute by NID (deprecated; use PKCS12_SAFEBAG_get0_attr()).
 * @param bag SafeBag to query.
 * @param attr_nid NID of the attribute to retrieve.
 * @return Attribute value, or NULL if absent or on error.
 */
OSSL_DEPRECATEDIN_1_1_0 ASN1_TYPE *PKCS12_get_attr(const PKCS12_SAFEBAG *bag,
    int attr_nid);
#endif

/**
 * @brief Retrieve a PKCS#8 private-key attribute by NID.
 * @param p8 PKCS#8 private key info structure.
 * @param attr_nid NID of the attribute to retrieve.
 * @return Attribute value, or NULL if absent or on error.
 */
ASN1_TYPE *PKCS8_get_attr(PKCS8_PRIV_KEY_INFO *p8, int attr_nid);
/**
 * @brief Test whether a PKCS#12 PFX carries an integrity MAC.
 * @param p12 PKCS#12 structure to query.
 * @return 1 if a MAC is present, or 0 if absent or @p p12 is NULL.
 */
int PKCS12_mac_present(const PKCS12 *p12);
/**
 * @brief Retrieve MAC value and MAC-parameter fields from a PKCS#12 PFX.
 * @param pmac Receives the MAC octet string, or NULL to skip.
 * @param pmacalg Receives the MAC algorithm identifier, or NULL to skip.
 * @param psalt Receives the MAC salt, or NULL to skip.
 * @param piter Receives the MAC iteration count, or NULL to skip.
 * @param p12 PKCS#12 structure to query.
 */
void PKCS12_get0_mac(const ASN1_OCTET_STRING **pmac,
    const X509_ALGOR **pmacalg,
    const ASN1_OCTET_STRING **psalt,
    const ASN1_INTEGER **piter,
    const PKCS12 *p12);

/**
 * @brief Get a PKCS#12 safeBag attribute value by NID.
 * @param bag SafeBag to query.
 * @param attr_nid NID of the attribute to retrieve.
 * @return Attribute value, or NULL if absent or on error.
 */
const ASN1_TYPE *PKCS12_SAFEBAG_get0_attr(const PKCS12_SAFEBAG *bag,
    int attr_nid);
/**
 * @brief Return the safeBag type OID without copying it.
 * @param bag SafeBag to query.
 * @return Internal safeBag type OID, or NULL if @p bag is NULL; do not free.
 */
const ASN1_OBJECT *PKCS12_SAFEBAG_get0_type(const PKCS12_SAFEBAG *bag);
/**
 * @brief Get the safeBag type as an NID.
 * @param bag SafeBag to query.
 * @return NID of the safeBag type (e.g. NID_certBag, NID_keyBag), or -1 if none.
 */
int PKCS12_SAFEBAG_get_nid(const PKCS12_SAFEBAG *bag);
/**
 * @brief Get the type of the object contained within a safeBag.
 * @param bag SafeBag to query.
 * @return NID of the contained object, or -1 if none.
 */
int PKCS12_SAFEBAG_get_bag_nid(const PKCS12_SAFEBAG *bag);
/**
 * @brief Retrieve the ASN.1 object contained within a safeBag.
 * @param bag SafeBag to query.
 * @return Pointer to the bag object, or NULL on error.
 */
const ASN1_TYPE *PKCS12_SAFEBAG_get0_bag_obj(const PKCS12_SAFEBAG *bag);
/**
 * @brief Get the type of the object contained within a safeBag as an OID.
 * @param bag SafeBag to query.
 * @return OID of the contained object, or NULL on error.
 */
const ASN1_OBJECT *PKCS12_SAFEBAG_get0_bag_type(const PKCS12_SAFEBAG *bag);

/**
 * @brief Extract an X.509 certificate from a certBag safeBag with a library context.
 * @param bag SafeBag containing a certificate.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return New X509 certificate, or NULL on error. Caller must free.
 */
X509 *PKCS12_SAFEBAG_get1_cert_ex(const PKCS12_SAFEBAG *bag, OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Extract an X.509 certificate from a certBag safeBag.
 * @param bag SafeBag containing a certificate.
 * @return New X509 certificate, or NULL on error. Caller must free.
 */
X509 *PKCS12_SAFEBAG_get1_cert(const PKCS12_SAFEBAG *bag);
/**
 * @brief Extract an X.509 CRL from a crlBag safeBag with a library context.
 * @param bag SafeBag containing a CRL.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return New X509_CRL, or NULL on error. Caller must free.
 */
X509_CRL *PKCS12_SAFEBAG_get1_crl_ex(const PKCS12_SAFEBAG *bag, OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Extract an X.509 CRL from a crlBag safeBag.
 * @param bag SafeBag containing a CRL.
 * @return New X509_CRL, or NULL on error. Caller must free.
 */
X509_CRL *PKCS12_SAFEBAG_get1_crl(const PKCS12_SAFEBAG *bag);
/**
 * @brief Retrieve the nested safeBags from a safeContentsBag.
 * @param bag SafeBag of type safeContentsBag.
 * @return Stack of nested safeBags, or NULL on error.
 */
const STACK_OF(PKCS12_SAFEBAG) *
PKCS12_SAFEBAG_get0_safes(const PKCS12_SAFEBAG *bag);
/**
 * @brief Return the PKCS#8 private key info from a keyBag or pkcs8ShroudedKeyBag.
 * @param bag SafeBag containing a private key.
 * @return PKCS#8 private key info, or NULL on error.
 */
const PKCS8_PRIV_KEY_INFO *PKCS12_SAFEBAG_get0_p8inf(const PKCS12_SAFEBAG *bag);
/**
 * @brief Return the encrypted PKCS#8 structure from a pkcs8ShroudedKeyBag safeBag.
 * @param bag SafeBag to query.
 * @return Internal X509_SIG pointer for the shrouded key, or NULL if @p bag is not pkcs8ShroudedKeyBag; do not free.
 */
const X509_SIG *PKCS12_SAFEBAG_get0_pkcs8(const PKCS12_SAFEBAG *bag);

/**
 * @brief Create a certBag safeBag containing the supplied certificate.
 * @param x509 Certificate to embed.
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create_cert(X509 *x509);
/**
 * @brief Create a crlBag safeBag containing the supplied CRL.
 * @param crl CRL to embed.
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create_crl(X509_CRL *crl);
/**
 * @brief Create a secretBag safeBag with the supplied ASN.1 value.
 * @param type NID tagging the secret contents.
 * @param vtype ASN.1 type of @p value.
 * @param value Octets of the secret value.
 * @param len Length of @p value in bytes.
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create_secret(int type, int vtype, const unsigned char *value, int len);
/**
 * @brief Create an unencrypted keyBag safeBag from PKCS#8 private key info.
 * @param p8 Private key info to embed (ownership transfers to the safeBag on success).
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create0_p8inf(PKCS8_PRIV_KEY_INFO *p8);
/**
 * @brief Create a pkcs8ShroudedKeyBag safeBag wrapping an already-encrypted PKCS#8 key.
 * @param p8 Encrypted PKCS#8 structure (X509_SIG); ownership transfers to the safeBag on success.
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create0_pkcs8(X509_SIG *p8);
/**
 * @brief Create an encrypted pkcs8ShroudedKeyBag safeBag from PKCS#8 private key info.
 * @param pbe_nid PBE algorithm NID, or 0 for a default.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for key derivation, or NULL to generate one.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count, or 0 for the default (2048).
 * @param p8inf Private key info to encrypt.
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create_pkcs8_encrypt(int pbe_nid,
    const char *pass,
    int passlen,
    unsigned char *salt,
    int saltlen, int iter,
    PKCS8_PRIV_KEY_INFO *p8inf);
/**
 * @brief Create an encrypted pkcs8ShroudedKeyBag safeBag from PKCS#8 private key info.
 * @param pbe_nid PBE algorithm NID, or 0 for a default.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for key derivation, or NULL to generate one.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count, or 0 for the default (2048).
 * @param p8inf Private key info to encrypt.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_create_pkcs8_encrypt_ex(int pbe_nid,
    const char *pass,
    int passlen,
    unsigned char *salt,
    int saltlen, int iter,
    PKCS8_PRIV_KEY_INFO *p8inf,
    OSSL_LIB_CTX *ctx,
    const char *propq);

/**
 * @brief Pack an ASN.1 object into a certBag or crlBag safeBag.
 * @param obj Object to pack (e.g. X509 or X509_CRL).
 * @param it ASN.1 item descriptor for @p obj.
 * @param nid1 NID of the inner bag type (e.g. NID_x509Certificate).
 * @param nid2 NID of the outer safeBag type (e.g. NID_certBag).
 * @return New safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_item_pack_safebag(void *obj, const ASN1_ITEM *it,
    int nid1, int nid2);
/**
 * @brief Decrypt a PKCS#8 encrypted private key.
 * @param p8 Encrypted PKCS#8 structure (X509_SIG).
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @return Decrypted PKCS#8 private key info, or NULL on error.
 */
PKCS8_PRIV_KEY_INFO *PKCS8_decrypt(const X509_SIG *p8, const char *pass,
    int passlen);
/**
 * @brief Decrypt a PKCS#8 encrypted private key using a library context.
 * @param p8 Encrypted PKCS#8 structure (X509_SIG).
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Decrypted PKCS#8 private key info, or NULL on error.
 */
PKCS8_PRIV_KEY_INFO *PKCS8_decrypt_ex(const X509_SIG *p8, const char *pass,
    int passlen, OSSL_LIB_CTX *ctx,
    const char *propq);
/**
 * @brief Decrypt the PKCS#8 shrouded key in a pkcs8ShroudedKeyBag safeBag.
 * @param bag SafeBag containing an encrypted private key.
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @return Decrypted PKCS#8 private key info, or NULL on error.
 */
PKCS8_PRIV_KEY_INFO *PKCS12_decrypt_skey(const PKCS12_SAFEBAG *bag,
    const char *pass, int passlen);
/**
 * @brief Decrypt the PKCS#8 shrouded key in a pkcs8ShroudedKeyBag safeBag.
 * @param bag SafeBag containing an encrypted private key.
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Decrypted PKCS#8 private key info, or NULL on error.
 */
PKCS8_PRIV_KEY_INFO *PKCS12_decrypt_skey_ex(const PKCS12_SAFEBAG *bag,
    const char *pass, int passlen,
    OSSL_LIB_CTX *ctx,
    const char *propq);
/**
 * @brief Encrypt a PKCS#8 private key info structure (default library context).
 * @param pbe_nid PBE algorithm NID.
 * @param cipher Cipher for PBES2, or NULL when @p pbe_nid selects a full PBE scheme.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for key derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count for key derivation.
 * @param p8 Private key info to encrypt.
 * @return Encrypted key in an X509_SIG, or NULL on error.
 */
X509_SIG *PKCS8_encrypt(int pbe_nid, const EVP_CIPHER *cipher,
    const char *pass, int passlen, unsigned char *salt,
    int saltlen, int iter, PKCS8_PRIV_KEY_INFO *p8);
/**
 * @brief Encrypt a PKCS#8 private key info structure.
 * @param pbe_nid PBE algorithm NID.
 * @param cipher Cipher for PBES2, or NULL when @p pbe_nid selects a full PBE scheme.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for key derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count for key derivation.
 * @param p8 Private key info to encrypt.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Encrypted key in an X509_SIG, or NULL on error.
 */
X509_SIG *PKCS8_encrypt_ex(int pbe_nid, const EVP_CIPHER *cipher,
    const char *pass, int passlen, unsigned char *salt,
    int saltlen, int iter, PKCS8_PRIV_KEY_INFO *p8,
    OSSL_LIB_CTX *ctx, const char *propq);
/**
 * @brief Encrypt PKCS#8 private key info using a pre-built PBE algorithm.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param p8inf Private key info to encrypt.
 * @param pbe PBE algorithm parameters.
 * @return Encrypted key in an X509_SIG, or NULL on error.
 */
X509_SIG *PKCS8_set0_pbe(const char *pass, int passlen,
    PKCS8_PRIV_KEY_INFO *p8inf, X509_ALGOR *pbe);
/**
 * @brief Encrypt PKCS#8 private key info using a pre-built PBE algorithm.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param p8inf Private key info to encrypt.
 * @param pbe PBE algorithm parameters.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Encrypted key in an X509_SIG, or NULL on error.
 */
X509_SIG *PKCS8_set0_pbe_ex(const char *pass, int passlen,
    PKCS8_PRIV_KEY_INFO *p8inf, X509_ALGOR *pbe,
    OSSL_LIB_CTX *ctx, const char *propq);
/**
 * @brief Pack a stack of safeBags into a PKCS#7 data ContentInfo.
 * @param sk Stack of safeBags to encode.
 * @return PKCS#7 data object, or NULL on error.
 */
PKCS7 *PKCS12_pack_p7data(STACK_OF(PKCS12_SAFEBAG) *sk);
/**
 * @brief Unpack safeBags from a PKCS#7 data ContentInfo.
 * @param p7 PKCS#7 data content info wrapping a PKCS12_SAFEBAGS sequence.
 * @return Stack of safeBags, or NULL if @p p7 is not data type or on decode error.
 */
STACK_OF(PKCS12_SAFEBAG) *PKCS12_unpack_p7data(PKCS7 *p7);
/**
 * @brief Pack safeBags into a PKCS#7 encrypted-data ContentInfo (default library context).
 * @param pbe_nid PBE or cipher NID for encryption (cipher NID selects PBES2 with that cipher).
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for key derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count for key derivation.
 * @param bags Stack of safeBags to encrypt.
 * @return PKCS#7 encrypted-data object, or NULL on error.
 */
PKCS7 *PKCS12_pack_p7encdata(int pbe_nid, const char *pass, int passlen,
    unsigned char *salt, int saltlen, int iter,
    STACK_OF(PKCS12_SAFEBAG) *bags);
/**
 * @brief Pack safeBags into a PKCS#7 encrypted-data ContentInfo.
 * @param pbe_nid PBE or cipher NID for encryption.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for key derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count for key derivation.
 * @param bags Stack of safeBags to encrypt.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return PKCS#7 encrypted-data object, or NULL on error.
 */
PKCS7 *PKCS12_pack_p7encdata_ex(int pbe_nid, const char *pass, int passlen,
    unsigned char *salt, int saltlen, int iter,
    STACK_OF(PKCS12_SAFEBAG) *bags,
    OSSL_LIB_CTX *ctx, const char *propq);

/**
 * @brief Unpack safeBags from a PKCS#7 encrypted-data ContentInfo.
 * @param p7 PKCS#7 encrypted-data content info wrapping a PKCS12_SAFEBAGS sequence.
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @return Stack of safeBags, or NULL if @p p7 is not encrypted-data or on decode error.
 */
STACK_OF(PKCS12_SAFEBAG) *PKCS12_unpack_p7encdata(PKCS7 *p7, const char *pass,
    int passlen);

/**
 * @brief Encode a stack of PKCS#7 authSafes contentInfos into a PKCS#12 structure.
 * @param p12 PKCS#12 structure whose authSafes field is updated.
 * @param safes Stack of PKCS#7 content infos to embed.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_pack_authsafes(PKCS12 *p12, STACK_OF(PKCS7) *safes);
/**
 * @brief Unpack the authSafes PKCS#7 contentInfos from a PKCS#12 structure.
 * @param p12 PKCS#12 structure to unpack.
 * @return Stack of PKCS#7 content infos, or NULL if @p p12 authSafes is not data type or on decode error.
 */
STACK_OF(PKCS7) *PKCS12_unpack_authsafes(const PKCS12 *p12);

/**
 * @brief Add a PKCS#9 localKeyID attribute to a safeBag.
 * @param bag SafeBag to modify.
 * @param name Octet-string local key identifier.
 * @param namelen Length of @p name in bytes.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_localkeyid(PKCS12_SAFEBAG *bag, unsigned char *name,
    int namelen);
/**
 * @brief Add a PKCS#9 friendlyName attribute (ASCII) to a safeBag.
 * @param bag SafeBag to modify.
 * @param name ASCII friendly name.
 * @param namelen Length of @p name in bytes, or -1 for strlen().
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_friendlyname_asc(PKCS12_SAFEBAG *bag, const char *name,
    int namelen);
/**
 * @brief Add a PKCS#9 friendlyName attribute (UTF-8) to a safeBag.
 * @param bag SafeBag to modify.
 * @param name UTF-8 friendly name.
 * @param namelen Length of @p name in bytes, or -1 for strlen().
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_friendlyname_utf8(PKCS12_SAFEBAG *bag, const char *name,
    int namelen);
/**
 * @brief Add a Microsoft CSP Name attribute (ASCII) to a safeBag.
 * @param bag SafeBag to modify.
 * @param name ASCII CSP name.
 * @param namelen Length of @p name in bytes, or -1 for strlen().
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_CSPName_asc(PKCS12_SAFEBAG *bag, const char *name,
    int namelen);
/**
 * @brief Add a PKCS#9 friendlyName attribute (BMPString) to a safeBag.
 * @param bag SafeBag to modify.
 * @param name Unicode friendly name (big-endian UTF-16, not NUL-terminated).
 * @param namelen Length of @p name in bytes.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_friendlyname_uni(PKCS12_SAFEBAG *bag,
    const unsigned char *name, int namelen);
/**
 * @brief Add a PKCS#12 attribute to a safeBag by NID.
 * @param bag SafeBag to modify.
 * @param nid NID of the attribute type.
 * @param type ASN.1 type of the attribute value.
 * @param bytes Attribute value octets.
 * @param len Length of @p bytes.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add1_attr_by_NID(PKCS12_SAFEBAG *bag, int nid, int type,
    const unsigned char *bytes, int len);
/**
 * @brief Add a PKCS#12 attribute to a safeBag by name.
 * @param bag SafeBag to modify.
 * @param attrname Short name or OID of the attribute type.
 * @param type ASN.1 type of the attribute value.
 * @param bytes Attribute value octets.
 * @param len Length of @p bytes.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add1_attr_by_txt(PKCS12_SAFEBAG *bag, const char *attrname, int type,
    const unsigned char *bytes, int len);
/**
 * @brief Add a Microsoft key-usage attribute to PKCS#8 private key info.
 * @param p8 PKCS#8 private key info to modify.
 * @param usage Key-usage flag (KEY_SIG or KEY_EX).
 * @return 1 on success, 0 on failure.
 */
int PKCS8_add_keyusage(PKCS8_PRIV_KEY_INFO *p8, int usage);
/**
 * @brief Retrieve an attribute by NID from a stack of X509_ATTRIBUTEs.
 * @param attrs Stack of attributes to search.
 * @param attr_nid NID of the attribute to retrieve.
 * @return Attribute value (owned by the containing structure), or NULL if absent or on error.
 */
ASN1_TYPE *PKCS12_get_attr_gen(const STACK_OF(X509_ATTRIBUTE) *attrs,
    int attr_nid);
/**
 * @brief Retrieve the PKCS#9 friendlyName from a safeBag as a UTF-8 string.
 * @param bag SafeBag to query.
 * @return Allocated UTF-8 string, or NULL if absent or on error. Caller must free.
 */
char *PKCS12_get_friendlyname(PKCS12_SAFEBAG *bag);
/**
 * @brief Return the attribute stack attached to a safeBag without copying it.
 * @param bag SafeBag to query.
 * @return Internal stack of X509_ATTRIBUTE, or NULL if @p bag is NULL; do not free.
 */
const STACK_OF(X509_ATTRIBUTE) *
PKCS12_SAFEBAG_get0_attrs(const PKCS12_SAFEBAG *bag);
/**
 * @brief Assign a stack of X509_ATTRIBUTEs to a safeBag.
 * @param bag SafeBag to modify.
 * @param attrs Stack of attributes to assign (ownership transfers to @p bag).
 */
void PKCS12_SAFEBAG_set0_attrs(PKCS12_SAFEBAG *bag, STACK_OF(X509_ATTRIBUTE) *attrs);
/**
 * @brief Encrypt or decrypt a buffer using a PKCS#12 PBE algorithm.
 * @param algor PBE algorithm identifier.
 * @param pass Passphrase.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param in Input buffer.
 * @param inlen Length of @p in in bytes.
 * @param data Address of output buffer pointer (malloc'd on success).
 * @param datalen Address to receive output length in bytes.
 * @param en_de 1 to encrypt, 0 to decrypt.
 * @return Pointer to output buffer (same as *@p data), or NULL on error.
 */
unsigned char *PKCS12_pbe_crypt(const X509_ALGOR *algor,
    const char *pass, int passlen,
    const unsigned char *in, int inlen,
    unsigned char **data, int *datalen,
    int en_de);
/**
 * @brief Encrypt or decrypt a buffer using a PKCS#12 PBE algorithm.
 * @param algor PBE algorithm identifier.
 * @param pass Passphrase.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param in Input buffer.
 * @param inlen Length of @p in in bytes.
 * @param data Address of output buffer pointer (malloc'd on success).
 * @param datalen Address to receive output length in bytes.
 * @param en_de 1 to encrypt, 0 to decrypt.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Pointer to output buffer (same as *@p data), or NULL on error.
 */
unsigned char *PKCS12_pbe_crypt_ex(const X509_ALGOR *algor,
    const char *pass, int passlen,
    const unsigned char *in, int inlen,
    unsigned char **data, int *datalen,
    int en_de, OSSL_LIB_CTX *libctx,
    const char *propq);
/**
 * @brief Decrypt an ASN.1 octet string and decode the embedded object.
 * @param algor PBE algorithm identifier.
 * @param it ASN.1 item descriptor for the embedded type.
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param oct Encrypted octet string.
 * @param zbuf If nonzero, zero the decrypted buffer after use.
 * @return Decoded object, or NULL on error.
 */
void *PKCS12_item_decrypt_d2i(const X509_ALGOR *algor, const ASN1_ITEM *it,
    const char *pass, int passlen,
    const ASN1_OCTET_STRING *oct, int zbuf);
/**
 * @brief Decrypt an ASN.1 octet string and decode the embedded object.
 * @param algor PBE algorithm identifier.
 * @param it ASN.1 item descriptor for the embedded type.
 * @param pass Passphrase for decryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param oct Encrypted octet string.
 * @param zbuf If nonzero, zero the decrypted buffer after use.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Decoded object, or NULL on error.
 */
void *PKCS12_item_decrypt_d2i_ex(const X509_ALGOR *algor, const ASN1_ITEM *it,
    const char *pass, int passlen,
    const ASN1_OCTET_STRING *oct, int zbuf,
    OSSL_LIB_CTX *libctx,
    const char *propq);
/**
 * @brief Encode an ASN.1 object and encrypt the result.
 * @param algor PBE algorithm identifier.
 * @param it ASN.1 item descriptor for @p obj.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param obj Object to encode and encrypt.
 * @param zbuf If nonzero, zero the plaintext encoding buffer after encryption.
 * @return Encrypted data as an ASN.1 octet string, or NULL on error.
 */
ASN1_OCTET_STRING *PKCS12_item_i2d_encrypt(X509_ALGOR *algor,
    const ASN1_ITEM *it,
    const char *pass, int passlen,
    void *obj, int zbuf);
/**
 * @brief Encode an ASN.1 object and encrypt the result using a library context.
 * @param algor PBE algorithm identifier.
 * @param it ASN.1 item descriptor for @p obj.
 * @param pass Passphrase for encryption.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param obj Object to encode and encrypt.
 * @param zbuf If nonzero, zero the plaintext encoding buffer after encryption.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Encrypted data as an ASN.1 octet string, or NULL on error.
 */
ASN1_OCTET_STRING *PKCS12_item_i2d_encrypt_ex(X509_ALGOR *algor,
    const ASN1_ITEM *it,
    const char *pass, int passlen,
    void *obj, int zbuf,
    OSSL_LIB_CTX *ctx,
    const char *propq);
/**
 * @brief Create an empty PKCS#12 structure.
 * @param mode NID of the outer PKCS#7 content type wrapping authSafes (currently NID_pkcs7_data only).
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_init(int mode);
/**
 * @brief Create an empty PKCS#12 structure with a library context.
 * @param mode NID of the outer PKCS#7 content type wrapping authSafes (currently NID_pkcs7_data only).
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_init_ex(int mode, OSSL_LIB_CTX *ctx, const char *propq);

/**
 * @brief Derive key material using the PKCS#12 key-generation function (ASCII passphrase).
 * @param pass ASCII passphrase.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param id Purpose byte (PKCS12_KEY_ID, PKCS12_IV_ID, or PKCS12_MAC_ID).
 * @param iter Iteration count (values less than 1 are treated as 1).
 * @param n Number of bytes to derive.
 * @param out Buffer to receive derived key material.
 * @param md_type Message digest for the derivation.
 * @return 1 on success, 0 on error.
 */
int PKCS12_key_gen_asc(const char *pass, int passlen, unsigned char *salt,
    int saltlen, int id, int iter, int n,
    unsigned char *out, const EVP_MD *md_type);
/**
 * @brief Derive key material using the PKCS#12 key-generation function (ASCII passphrase).
 * @param pass ASCII passphrase.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param id Purpose byte (PKCS12_KEY_ID, PKCS12_IV_ID, or PKCS12_MAC_ID).
 * @param iter Iteration count (values less than 1 are treated as 1).
 * @param n Number of bytes to derive.
 * @param out Buffer to receive derived key material.
 * @param md_type Message digest for the derivation.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 on success, 0 on error.
 */
int PKCS12_key_gen_asc_ex(const char *pass, int passlen, unsigned char *salt,
    int saltlen, int id, int iter, int n,
    unsigned char *out, const EVP_MD *md_type,
    OSSL_LIB_CTX *ctx, const char *propq);
/**
 * @brief Derive key material using the PKCS#12 key-generation function (BMPString passphrase).
 * @param pass Unicode passphrase (big-endian UTF-16, not NUL-terminated).
 * @param passlen Length of @p pass in bytes.
 * @param salt Salt for derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param id Purpose byte (PKCS12_KEY_ID, PKCS12_IV_ID, or PKCS12_MAC_ID).
 * @param iter Iteration count (values less than 1 are treated as 1).
 * @param n Number of bytes to derive.
 * @param out Buffer to receive derived key material.
 * @param md_type Message digest for the derivation.
 * @return 1 on success, 0 on error.
 */
int PKCS12_key_gen_uni(unsigned char *pass, int passlen, unsigned char *salt,
    int saltlen, int id, int iter, int n,
    unsigned char *out, const EVP_MD *md_type);
/**
 * @brief Derive key material using the PKCS#12 key-generation function (BMPString passphrase).
 * @param pass Unicode passphrase (big-endian UTF-16, not NUL-terminated).
 * @param passlen Length of @p pass in bytes.
 * @param salt Salt for derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param id Purpose byte (PKCS12_KEY_ID, PKCS12_IV_ID, or PKCS12_MAC_ID).
 * @param iter Iteration count (values less than 1 are treated as 1).
 * @param n Number of bytes to derive.
 * @param out Buffer to receive derived key material.
 * @param md_type Message digest for the derivation.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 on success, 0 on error.
 */
int PKCS12_key_gen_uni_ex(unsigned char *pass, int passlen, unsigned char *salt,
    int saltlen, int id, int iter, int n,
    unsigned char *out, const EVP_MD *md_type,
    OSSL_LIB_CTX *ctx, const char *propq);
/**
 * @brief Derive key material using the PKCS#12 key-generation function (UTF-8 passphrase).
 * @param pass UTF-8 passphrase.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param id Purpose byte (PKCS12_KEY_ID, PKCS12_IV_ID, or PKCS12_MAC_ID).
 * @param iter Iteration count (values less than 1 are treated as 1).
 * @param n Number of bytes to derive.
 * @param out Buffer to receive derived key material.
 * @param md_type Message digest for the derivation.
 * @return 1 on success, 0 on error.
 */
int PKCS12_key_gen_utf8(const char *pass, int passlen, unsigned char *salt,
    int saltlen, int id, int iter, int n,
    unsigned char *out, const EVP_MD *md_type);
/**
 * @brief Derive key material using the PKCS#12 key-generation function (UTF-8 passphrase).
 * @param pass UTF-8 passphrase.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for derivation.
 * @param saltlen Length of @p salt in bytes.
 * @param id Purpose byte (PKCS12_KEY_ID, PKCS12_IV_ID, or PKCS12_MAC_ID).
 * @param iter Iteration count (values less than 1 are treated as 1).
 * @param n Number of bytes to derive.
 * @param out Buffer to receive derived key material.
 * @param md_type Message digest for the derivation.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 on success, 0 on error.
 */
int PKCS12_key_gen_utf8_ex(const char *pass, int passlen, unsigned char *salt,
    int saltlen, int id, int iter, int n,
    unsigned char *out, const EVP_MD *md_type,
    OSSL_LIB_CTX *ctx, const char *propq);

/**
 * @brief Initialise a cipher context for PKCS#12 PBE encryption or decryption.
 * @param ctx Cipher context to initialise.
 * @param pass Passphrase (treated as a byte sequence).
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param param PBE algorithm parameters.
 * @param cipher Cipher for the operation.
 * @param md_type Message digest for key derivation.
 * @param en_de 1 to encrypt, 0 to decrypt.
 * @return 1 on success, 0 on error.
 */
int PKCS12_PBE_keyivgen(EVP_CIPHER_CTX *ctx, const char *pass, int passlen,
    ASN1_TYPE *param, const EVP_CIPHER *cipher,
    const EVP_MD *md_type, int en_de);
/**
 * @brief Initialise a cipher context for PKCS#12 PBE encryption or decryption.
 * @param ctx Cipher context to initialise.
 * @param pass Passphrase (treated as a byte sequence).
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param param PBE algorithm parameters.
 * @param cipher Cipher for the operation.
 * @param md_type Message digest for key derivation.
 * @param en_de 1 to encrypt, 0 to decrypt.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 on success, 0 on error.
 */
int PKCS12_PBE_keyivgen_ex(EVP_CIPHER_CTX *ctx, const char *pass, int passlen,
    ASN1_TYPE *param, const EVP_CIPHER *cipher,
    const EVP_MD *md_type, int en_de,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Generate the HMAC for a PKCS#12 object using configured MAC parameters.
 * @param p12 PKCS#12 structure with MAC parameters already set.
 * @param pass Passphrase for the HMAC.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param mac Buffer to receive the MAC value.
 * @param maclen Address to receive MAC length in bytes on input and output.
 * @return 1 on success, 0 on error.
 */
int PKCS12_gen_mac(PKCS12 *p12, const char *pass, int passlen,
    unsigned char *mac, unsigned int *maclen);
/**
 * @brief Verify the HMAC of a PKCS#12 object.
 * @param p12 PKCS#12 structure to verify.
 * @param pass Passphrase for the HMAC.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @return 1 if the MAC is valid, 0 otherwise.
 */
int PKCS12_verify_mac(PKCS12 *p12, const char *pass, int passlen);
/**
 * @brief Compute and store the MAC and MAC parameters in a PKCS#12 object.
 * @param p12 PKCS#12 structure to update.
 * @param pass Passphrase for the HMAC.
 * @param passlen Length of @p pass, or -1 to use strlen().
 * @param salt Salt for MAC key derivation, or NULL to generate one.
 * @param saltlen Length of @p salt in bytes.
 * @param iter Iteration count for MAC key derivation (1 omits the count from the structure).
 * @param md_type Message digest for the HMAC.
 * @return 1 on success, 0 on error.
 */
int PKCS12_set_mac(PKCS12 *p12, const char *pass, int passlen,
    unsigned char *salt, int saltlen, int iter,
    const EVP_MD *md_type);
/**
 * @brief Set MAC parameters in a PKCS#12 object without computing the MAC.
 * @param p12 PKCS#12 structure to update.
 * @param iter Iteration count for MAC key derivation (1 omits the count from the structure).
 * @param salt Salt for MAC key derivation, or NULL to generate one.
 * @param saltlen Length of @p salt in bytes.
 * @param md_type Message digest for the HMAC.
 * @return 1 on success, 0 on error.
 */
int PKCS12_setup_mac(PKCS12 *p12, int iter, unsigned char *salt,
    int saltlen, const EVP_MD *md_type);
/**
 * @brief Convert an ASCII/ISO-8859-1 string to PKCS#12 BMPString form (zero-extended UTF-16BE).
 * @param asc Input octets (typically ASCII or Latin-1).
 * @param asclen Length of @p asc in bytes, or -1 to use strlen().
 * @param uni Optional address of pointer updated to the allocated BMPString buffer.
 * @param unilen Optional address to receive BMPString length in bytes (including double NUL).
 * @return Pointer to the BMPString (same as *@p uni when @p uni is non-NULL), or NULL on error.
 */
unsigned char *OPENSSL_asc2uni(const char *asc, int asclen,
    unsigned char **uni, int *unilen);
/**
 * @brief Convert a PKCS#12 BMPString (big-endian UTF-16 with zero high bytes) to a C string.
 * @param uni BMPString octets (even length).
 * @param unilen Length of @p uni in bytes.
 * @return Newly allocated NUL-terminated string of the low bytes, or NULL on error. Caller frees with OPENSSL_free().
 */
char *OPENSSL_uni2asc(const unsigned char *uni, int unilen);
/**
 * @brief Convert a UTF-8 string to PKCS#12 BMPString form (big-endian UTF-16).
 * @param asc UTF-8 input string.
 * @param asclen Length of @p asc in bytes, or -1 to use strlen().
 * @param uni Address of pointer updated to the allocated BMPString buffer.
 * @param unilen Address to receive BMPString length in bytes.
 * @return Pointer to the BMPString (same as *@p uni), or NULL on error. Falls back to OPENSSL_asc2uni() if @p asc is not valid UTF-8.
 */
unsigned char *OPENSSL_utf82uni(const char *asc, int asclen,
    unsigned char **uni, int *unilen);
/**
 * @brief Convert a PKCS#12 BMPString (big-endian UTF-16) to a UTF-8 C string.
 * @param uni BMPString octets (even length).
 * @param unilen Length of @p uni in bytes.
 * @return Newly allocated UTF-8 string, or NULL on error. Falls back to OPENSSL_uni2asc() if decoding fails. Caller frees with OPENSSL_free().
 */
char *OPENSSL_uni2utf8(const unsigned char *uni, int unilen);

/**
 * @brief Allocate an empty PKCS12 structure.
 * @return New PKCS12, or NULL on allocation failure.
 */
PKCS12 *PKCS12_new(void);
/**
 * @brief Free a PKCS12 structure and its contents.
 * @param a Value to free, or NULL.
 */
void PKCS12_free(PKCS12 *a);
/**
 * @brief Decode a PKCS12 structure from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded PKCS12, or NULL on error.
 */
PKCS12 *d2i_PKCS12(PKCS12 **a, const unsigned char **in, long len);
/**
 * @brief Encode a PKCS12 structure to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_PKCS12(const PKCS12 *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for PKCS12.
 * @return Pointer to the static ASN1_ITEM for PKCS12.
 */
const ASN1_ITEM *PKCS12_it(void);
/**
 * @brief Allocate an empty PKCS12_MAC_DATA structure.
 * @return New PKCS12_MAC_DATA, or NULL on allocation failure.
 */
PKCS12_MAC_DATA *PKCS12_MAC_DATA_new(void);
/**
 * @brief Free a PKCS12_MAC_DATA structure and its contents.
 * @param a Value to free, or NULL.
 */
void PKCS12_MAC_DATA_free(PKCS12_MAC_DATA *a);
/**
 * @brief Decode a PKCS12_MAC_DATA structure from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded PKCS12_MAC_DATA, or NULL on error.
 */
PKCS12_MAC_DATA *d2i_PKCS12_MAC_DATA(PKCS12_MAC_DATA **a, const unsigned char **in, long len);
/**
 * @brief Encode a PKCS12_MAC_DATA structure to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_PKCS12_MAC_DATA(const PKCS12_MAC_DATA *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for PKCS12_MAC_DATA.
 * @return Pointer to the static ASN1_ITEM for PKCS12_MAC_DATA.
 */
const ASN1_ITEM *PKCS12_MAC_DATA_it(void);
/**
 * @brief Allocate an empty PKCS12_SAFEBAG structure.
 * @return New PKCS12_SAFEBAG, or NULL on allocation failure.
 */
PKCS12_SAFEBAG *PKCS12_SAFEBAG_new(void);
/**
 * @brief Free a PKCS12_SAFEBAG structure and its contents.
 * @param a Value to free, or NULL.
 */
void PKCS12_SAFEBAG_free(PKCS12_SAFEBAG *a);
/**
 * @brief Decode a PKCS12_SAFEBAG structure from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded PKCS12_SAFEBAG, or NULL on error.
 */
PKCS12_SAFEBAG *d2i_PKCS12_SAFEBAG(PKCS12_SAFEBAG **a, const unsigned char **in, long len);
/**
 * @brief Encode a PKCS12_SAFEBAG structure to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_PKCS12_SAFEBAG(const PKCS12_SAFEBAG *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for PKCS12_SAFEBAG.
 * @return Pointer to the static ASN1_ITEM for PKCS12_SAFEBAG.
 */
const ASN1_ITEM *PKCS12_SAFEBAG_it(void);
/**
 * @brief Allocate an empty PKCS12_BAGS structure.
 * @return New PKCS12_BAGS, or NULL on allocation failure.
 */
PKCS12_BAGS *PKCS12_BAGS_new(void);
/**
 * @brief Free a PKCS12_BAGS structure and its contents.
 * @param a Value to free, or NULL.
 */
void PKCS12_BAGS_free(PKCS12_BAGS *a);
/**
 * @brief Decode a PKCS12_BAGS structure from DER.
 * @param a Optional destination pointer updated to the result, or NULL.
 * @param in Address of a pointer to the DER input; advanced past the decoded value.
 * @param len Number of bytes available at *@p in.
 * @return Decoded PKCS12_BAGS, or NULL on error.
 */
PKCS12_BAGS *d2i_PKCS12_BAGS(PKCS12_BAGS **a, const unsigned char **in, long len);
/**
 * @brief Encode a PKCS12_BAGS structure to DER.
 * @param a Value to encode.
 * @param out Destination pointer updated like a standard i2d encoder, or NULL to measure length.
 * @return Number of bytes encoded, or a negative value on error.
 */
int i2d_PKCS12_BAGS(const PKCS12_BAGS *a, unsigned char **out);
/**
 * @brief Return the ASN.1 item descriptor for PKCS12_BAGS.
 * @return Pointer to the static ASN1_ITEM for PKCS12_BAGS.
 */
const ASN1_ITEM *PKCS12_BAGS_it(void);

/**
 * @brief Return the ASN.1 item descriptor for a SEQUENCE OF PKCS12_SAFEBAG.
 * @return Pointer to the static ASN1_ITEM for PKCS12_SAFEBAGS.
 */
const ASN1_ITEM *PKCS12_SAFEBAGS_it(void);
/**
 * @brief Return the ASN.1 item descriptor for a SEQUENCE OF PKCS7 (authSafes).
 * @return Pointer to the static ASN1_ITEM for PKCS12_AUTHSAFES.
 */
const ASN1_ITEM *PKCS12_AUTHSAFES_it(void);

/**
 * @brief Register PKCS#12 PBE algorithms (historical no-op; algorithms are built in).
 */
void PKCS12_PBE_add(void);
/**
 * @brief Parse a PKCS#12 structure and extract key, certificate, and CA certificates.
 * @param p12 PKCS#12 structure to parse.
 * @param pass Passphrase (UTF-8, or ISO8859-1 if not valid UTF-8).
 * @param pkey Address of pointer to receive the private key, or NULL to discard.
 * @param cert Address of pointer to receive the entity certificate, or NULL to discard.
 * @param ca Address of stack pointer to receive additional certificates, or NULL to discard.
 * @return 1 on success, 0 on error.
 */
int PKCS12_parse(PKCS12 *p12, const char *pass, EVP_PKEY **pkey, X509 **cert,
    STACK_OF(X509) **ca);
/**
 * @brief Callback invoked for each safeBag while building a PKCS#12 structure.
 * @param bag SafeBag just added by PKCS12_create_ex2().
 * @param cbarg Opaque argument supplied to PKCS12_create_ex2().
 * @return 1 to keep @p bag, 0 to remove it, or -1 for a fatal error.
 */
typedef int PKCS12_create_cb(PKCS12_SAFEBAG *bag, void *cbarg);
/**
 * @brief Create a PKCS#12 structure from a key, certificate, and optional CA stack (default library context).
 * @param pass Passphrase for encryption and MAC.
 * @param name Friendly name for the key and certificate.
 * @param pkey Private key to include, or NULL.
 * @param cert Entity certificate to include, or NULL.
 * @param ca Optional additional certificates, or NULL.
 * @param nid_key PBE NID for key encryption, or 0/-1 for defaults/no encryption.
 * @param nid_cert PBE NID for certificate encryption, or 0/-1 for defaults/no encryption.
 * @param iter Encryption iteration count, or 0 for default.
 * @param mac_iter MAC iteration count, or 0/-1 for default/omit MAC.
 * @param keytype MS key-usage flag (KEY_SIG or KEY_EX), or 0 to omit.
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_create(const char *pass, const char *name, EVP_PKEY *pkey,
    X509 *cert, STACK_OF(X509) *ca, int nid_key, int nid_cert,
    int iter, int mac_iter, int keytype);
/**
 * @brief Create a PKCS#12 structure from a key, certificate, and optional CA stack.
 * @param pass Passphrase for encryption and MAC.
 * @param name Friendly name for the key and certificate.
 * @param pkey Private key to include, or NULL.
 * @param cert Entity certificate to include, or NULL.
 * @param ca Optional additional certificates, or NULL.
 * @param nid_key PBE NID for key encryption, or 0/-1 for defaults/no encryption.
 * @param nid_cert PBE NID for certificate encryption, or 0/-1 for defaults/no encryption.
 * @param iter Encryption iteration count, or 0 for default.
 * @param mac_iter MAC iteration count, or 0/-1 for default/omit MAC.
 * @param keytype MS key-usage flag (KEY_SIG or KEY_EX), or 0 to omit.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_create_ex(const char *pass, const char *name, EVP_PKEY *pkey,
    X509 *cert, STACK_OF(X509) *ca, int nid_key, int nid_cert,
    int iter, int mac_iter, int keytype,
    OSSL_LIB_CTX *ctx, const char *propq);
/**
 * @brief Create a PKCS#12 structure with an optional per-safeBag callback.
 * @param pass Passphrase for encryption and MAC.
 * @param name Friendly name for the key and certificate.
 * @param pkey Private key to include, or NULL.
 * @param cert Entity certificate to include, or NULL.
 * @param ca Optional additional certificates, or NULL.
 * @param nid_key PBE NID for key encryption, or 0/-1 for defaults/no encryption.
 * @param nid_cert PBE NID for certificate encryption, or 0/-1 for defaults/no encryption.
 * @param iter Encryption iteration count, or 0 for default.
 * @param mac_iter MAC iteration count, or 0/-1 for default/omit MAC.
 * @param keytype MS key-usage flag (KEY_SIG or KEY_EX), or 0 to omit.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @param cb Optional callback invoked for each safeBag added (return 1 to keep, 0 to omit, -1 for fatal error).
 * @param cbarg Opaque argument passed to @p cb.
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_create_ex2(const char *pass, const char *name, EVP_PKEY *pkey,
    X509 *cert, STACK_OF(X509) *ca, int nid_key, int nid_cert,
    int iter, int mac_iter, int keytype,
    OSSL_LIB_CTX *ctx, const char *propq,
    PKCS12_create_cb *cb, void *cbarg);

/**
 * @brief Create a certBag safeBag and append it to a stack of safeBags.
 * @param pbags Address of safeBag stack pointer (created if *@p pbags is NULL).
 * @param cert Certificate to add.
 * @return The new safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_add_cert(STACK_OF(PKCS12_SAFEBAG) **pbags, X509 *cert);
/**
 * @brief Create a key safeBag and append it to a stack of safeBags.
 * @param pbags Address of safeBag stack pointer (created if *@p pbags is NULL).
 * @param key Private key to add.
 * @param key_usage MS key-usage flag (KEY_SIG or KEY_EX), or 0 to omit.
 * @param iter Iteration count for key encryption, or 0 for default.
 * @param key_nid PBE NID for key encryption, or -1 for an unencrypted keyBag.
 * @param pass Passphrase when @p key_nid selects encryption, or NULL otherwise.
 * @return The new safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_add_key(STACK_OF(PKCS12_SAFEBAG) **pbags,
    EVP_PKEY *key, int key_usage, int iter,
    int key_nid, const char *pass);
/**
 * @brief Create a key safeBag and append it to a stack of safeBags.
 * @param pbags Address of safeBag stack pointer (created if *@p pbags is NULL).
 * @param key Private key to add.
 * @param key_usage MS key-usage flag (KEY_SIG or KEY_EX), or 0 to omit.
 * @param iter Iteration count for key encryption, or 0 for default.
 * @param key_nid PBE NID for key encryption, or -1 for an unencrypted keyBag.
 * @param pass Passphrase when @p key_nid selects encryption, or NULL otherwise.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return The new safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_add_key_ex(STACK_OF(PKCS12_SAFEBAG) **pbags,
    EVP_PKEY *key, int key_usage, int iter,
    int key_nid, const char *pass,
    OSSL_LIB_CTX *ctx, const char *propq);

/**
 * @brief Create a secretBag safeBag and append it to a stack of safeBags.
 * @param pbags Address of safeBag stack pointer (created if *@p pbags is NULL).
 * @param nid_type NID tagging the secret contents.
 * @param value Octets of the secret value.
 * @param len Length of @p value in bytes.
 * @return The new safeBag, or NULL on error.
 */
PKCS12_SAFEBAG *PKCS12_add_secret(STACK_OF(PKCS12_SAFEBAG) **pbags,
    int nid_type, const unsigned char *value, int len);
/**
 * @brief Pack safeBags into a PKCS#7 contentInfo and append it to a stack of safes.
 * @param psafes Address of PKCS#7 stack pointer (created if *@p psafes is NULL).
 * @param bags Stack of safeBags to pack.
 * @param safe_nid -1 for plain data, 0 for default encrypted, or a PBE NID for encrypted.
 * @param iter Iteration count for encryption, or 0 for default (2048).
 * @param pass Passphrase when @p safe_nid selects encryption, or NULL for plain data.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_safe(STACK_OF(PKCS7) **psafes, STACK_OF(PKCS12_SAFEBAG) *bags,
    int safe_nid, int iter, const char *pass);
/**
 * @brief Pack safeBags into a PKCS#7 contentInfo and append it to a stack of safes.
 * @param psafes Address of PKCS#7 stack pointer (created if *@p psafes is NULL).
 * @param bags Stack of safeBags to pack.
 * @param safe_nid -1 for plain data, 0 for default encrypted, or a PBE NID for encrypted.
 * @param iter Iteration count for encryption, or 0 for default (2048).
 * @param pass Passphrase when @p safe_nid selects encryption, or NULL for plain data.
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 on success, 0 on failure.
 */
int PKCS12_add_safe_ex(STACK_OF(PKCS7) **psafes, STACK_OF(PKCS12_SAFEBAG) *bags,
    int safe_nid, int iter, const char *pass,
    OSSL_LIB_CTX *ctx, const char *propq);

/**
 * @brief Create a PKCS#12 structure from a stack of PKCS#7 authSafes contentInfos.
 * @param safes Stack of PKCS#7 content infos to embed.
 * @param p7_nid NID of the outer PKCS#7 content type (currently NID_pkcs7_data only).
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_add_safes(STACK_OF(PKCS7) *safes, int p7_nid);
/**
 * @brief Create a PKCS#12 structure from a stack of PKCS#7 authSafes contentInfos.
 * @param safes Stack of PKCS#7 content infos to embed.
 * @param p7_nid NID of the outer PKCS#7 content type (currently NID_pkcs7_data only).
 * @param ctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return New PKCS#12 structure, or NULL on error.
 */
PKCS12 *PKCS12_add_safes_ex(STACK_OF(PKCS7) *safes, int p7_nid,
    OSSL_LIB_CTX *ctx, const char *propq);

/**
 * @brief Encode a PKCS12 structure to DER and write it to a BIO.
 * @param bp Destination BIO.
 * @param p12 PKCS#12 structure to encode.
 * @return Number of bytes written, or a negative value on error.
 */
int i2d_PKCS12_bio(BIO *bp, const PKCS12 *p12);
#ifndef OPENSSL_NO_STDIO
/**
 * @brief Encode a PKCS12 structure to DER and write it to a FILE.
 * @param fp Output file.
 * @param p12 PKCS#12 structure to encode.
 * @return Number of bytes written, or a negative value on error.
 */
int i2d_PKCS12_fp(FILE *fp, const PKCS12 *p12);
#endif
/**
 * @brief Read and decode a PKCS12 structure from a BIO.
 * @param bp Input BIO supplying DER-encoded PKCS#12 data.
 * @param p12 Optional pointer updated to the decoded structure, or NULL.
 * @return Decoded PKCS12, or NULL on error.
 */
PKCS12 *d2i_PKCS12_bio(BIO *bp, PKCS12 **p12);
#ifndef OPENSSL_NO_STDIO
/**
 * @brief Read and decode a PKCS12 structure from a FILE.
 * @param fp Input file.
 * @param p12 Optional pointer updated to the decoded structure, or NULL.
 * @return Decoded PKCS12, or NULL on error.
 */
PKCS12 *d2i_PKCS12_fp(FILE *fp, PKCS12 **p12);
#endif
/**
 * @brief Change the password protecting a PKCS#12 structure.
 * @param p12 PKCS#12 structure to re-encrypt.
 * @param oldpass Current passphrase (UTF-8, or ISO8859-1 if not valid UTF-8; use "" if none).
 * @param newpass New passphrase (UTF-8, or ISO8859-1 if not valid UTF-8).
 * @return 1 on success, 0 on error.
 */
int PKCS12_newpass(PKCS12 *p12, const char *oldpass, const char *newpass);

#ifdef __cplusplus
}
#endif
#endif
