/*
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_RAND_H
#define OPENSSL_RAND_H
#pragma once

#include <openssl/macros.h>
#ifndef OPENSSL_NO_DEPRECATED_3_0
#define HEADER_RAND_H
#endif

#include <stdlib.h>
#include <openssl/types.h>
#include <openssl/e_os2.h>
#include <openssl/randerr.h>
#include <openssl/evp.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Default security strength (in the sense of [NIST SP 800-90Ar1])
 *
 * NIST SP 800-90Ar1 supports the strength of the DRBG being smaller than that
 * of the cipher by collecting less entropy. The current DRBG implementation
 * does not take RAND_DRBG_STRENGTH into account and sets the strength of the
 * DRBG to that of the cipher.
 */
#define RAND_DRBG_STRENGTH 256

#ifndef OPENSSL_NO_DEPRECATED_3_0
struct rand_meth_st {
    /** Mix seed bytes into the generator state (legacy RAND_METHOD hook). */
    int (*seed)(const void *buf, int num);
    /** Fill a buffer with cryptographically strong random bytes. */
    int (*bytes)(unsigned char *buf, int num);
    /** Release any resources held by this RAND_METHOD implementation. */
    void (*cleanup)(void);
    /** Mix additional bytes into the state with an estimated entropy amount. */
    int (*add)(const void *buf, int num, double randomness);
    /** Fill a buffer with pseudo-random bytes (may be weaker than @c bytes). */
    int (*pseudorand)(unsigned char *buf, int num);
    /** Return whether the generator is sufficiently seeded. */
    int (*status)(void);
};

/**
 * @brief Install the legacy RAND_METHOD used by RAND_bytes and related APIs (deprecated).
 * @param meth Method table to make current, or NULL to clear.
 * @return 1 on success, or 0 on failure.
 */
OSSL_DEPRECATEDIN_3_0 int RAND_set_rand_method(const RAND_METHOD *meth);
/**
 * @brief Return the currently selected legacy RAND_METHOD used for PRNG operations.
 * @return Pointer to the active RAND_METHOD (not to be freed).
 *
 * Deprecated in OpenSSL 3.0; prefer RAND_set_DRBG_type() and EVP_RAND.
 */
OSSL_DEPRECATEDIN_3_0 const RAND_METHOD *RAND_get_rand_method(void);
#ifndef OPENSSL_NO_ENGINE
/**
 * @brief Select an ENGINE as the source of the legacy RAND_METHOD (deprecated).
 * @param engine ENGINE providing a RAND implementation, or NULL to clear.
 * @return 1 on success, or 0 on failure.
 *
 * Deprecated in OpenSSL 3.0; prefer EVP_RAND / provider-based DRBGs.
 */
OSSL_DEPRECATEDIN_3_0 int RAND_set_rand_engine(ENGINE *engine);
#endif

/**
 * @brief Return the built-in OpenSSL legacy RAND_METHOD (deprecated).
 * @return Pointer to the default OpenSSL RAND_METHOD.
 */
OSSL_DEPRECATEDIN_3_0 RAND_METHOD *RAND_OpenSSL(void);
#endif /* OPENSSL_NO_DEPRECATED_3_0 */

#ifndef OPENSSL_NO_DEPRECATED_1_1_0
#define RAND_cleanup() \
    while (0)          \
    continue
#endif
/**
 * @brief Fill a buffer with cryptographically strong random bytes from the public CSPRNG.
 * @param buf Buffer that receives @p num random bytes.
 * @param num Number of bytes to generate.
 * @return 1 on success, -1 if not supported by the current RAND method, or 0 on other failure.
 */
int RAND_bytes(unsigned char *buf, int num);
/**
 * @brief Generate private random bytes using a separate DRBG instance from RAND_bytes().
 * @param buf Buffer that receives @p num random bytes.
 * @param num Number of bytes to generate.
 * @return 1 on success, -1 if not supported by the current RAND method, or 0 on other failure.
 */
int RAND_priv_bytes(unsigned char *buf, int num);

/**
 * @brief Like RAND_priv_bytes(), with an explicit library context and security strength.
 * @param ctx Library context whose private DRBG is used, or NULL for the default.
 * @param buf Buffer that receives @p num random bytes.
 * @param num Number of bytes to generate.
 * @param strength Requested security strength in bits for the generated bytes.
 * @return 1 on success, -1 if not supported by the current RAND method, or 0 on other failure.
 */
int RAND_priv_bytes_ex(OSSL_LIB_CTX *ctx, unsigned char *buf, size_t num,
    unsigned int strength);

/*
 * Equivalent of RAND_bytes() but additionally taking an OSSL_LIB_CTX and
 * a strength.
 */
/**
 * @brief Fill a buffer with public CSPRNG bytes using a library context and strength.
 * @param ctx Library context whose public DRBG is used, or NULL for the default.
 * @param buf Buffer that receives @p num random bytes.
 * @param num Number of bytes to generate.
 * @param strength Requested security strength in bits for the generated bytes.
 * @return 1 on success, -1 if not supported by the current RAND method, or 0 on other failure.
 */
int RAND_bytes_ex(OSSL_LIB_CTX *ctx, unsigned char *buf, size_t num,
    unsigned int strength);

#ifndef OPENSSL_NO_DEPRECATED_1_1_0
/**
 * @brief Fill a buffer with bytes that need not be cryptographically strong (deprecated).
 * @param buf Destination buffer to fill.
 * @param num Number of bytes to write.
 * @return 1 if the bytes are cryptographically strong, 0 if only pseudo-random, or -1 on error.
 *
 * Prefer RAND_bytes() for all new code.
 */
OSSL_DEPRECATEDIN_1_1_0 int RAND_pseudo_bytes(unsigned char *buf, int num);
#endif

/**
 * @brief Return the shared primary DRBG for a library context (used to reseed public/private DRBGs).
 * @param ctx Library context, or NULL for the default.
 * @return Internal EVP_RAND_CTX pointer (do not free); not safe for concurrent direct use.
 */
EVP_RAND_CTX *RAND_get0_primary(OSSL_LIB_CTX *ctx);
/**
 * @brief Return the thread-local public DRBG used by RAND_bytes() for a library context.
 * @param ctx Library context, or NULL for the default.
 * @return Internal EVP_RAND_CTX pointer (do not free).
 */
EVP_RAND_CTX *RAND_get0_public(OSSL_LIB_CTX *ctx);
/**
 * @brief Return the thread-local private DRBG used by RAND_priv_bytes() for a library context.
 * @param ctx Library context, or NULL for the default.
 * @return Internal EVP_RAND_CTX pointer (do not free).
 */
EVP_RAND_CTX *RAND_get0_private(OSSL_LIB_CTX *ctx);
/**
 * @brief Install @p rand as the public DRBG for a library context, transferring ownership.
 * @param ctx Library context whose public RNG is replaced, or NULL for the default.
 * @param rand RAND context that becomes the public generator; @p ctx takes ownership.
 * @return 1 on success, or 0 on failure.
 */
int RAND_set0_public(OSSL_LIB_CTX *ctx, EVP_RAND_CTX *rand);
/**
 * @brief Install @p rand as the private DRBG for a library context, transferring ownership.
 * @param ctx Library context whose private RNG is replaced, or NULL for the default.
 * @param rand RAND context that becomes the private generator used by RAND_priv_bytes(); @p ctx takes ownership.
 * @return 1 on success, or 0 on failure.
 */
int RAND_set0_private(OSSL_LIB_CTX *ctx, EVP_RAND_CTX *rand);

/**
 * @brief Configure the primary DRBG algorithm type for a library context.
 * @param ctx Library context whose RNG is configured, or NULL for the default.
 * @param drbg DRBG algorithm name (for example "HASH-DRBG" or "CTR-DRBG"), or NULL for the default.
 * @param propq Property query for fetching the DRBG, or NULL.
 * @param cipher Cipher name required by CTR-DRBG, or NULL when unused.
 * @param digest Digest name required by HASH-DRBG/HMAC-DRBG, or NULL when unused.
 * @return 1 on success, or 0 on error.
 *
 * Must be called before the DRBGs are first instantiated for @p ctx.
 */
int RAND_set_DRBG_type(OSSL_LIB_CTX *ctx, const char *drbg, const char *propq,
    const char *cipher, const char *digest);
/**
 * @brief Select the seed source used by the primary RNG in a library context.
 * @param ctx Library context whose seed source is configured, or NULL for the default.
 * @param seed Seed-source algorithm name (for example "SEED-SRC"), or NULL for the default.
 * @param propq Property query for fetching the seed source, or NULL.
 * @return 1 on success, or 0 on error.
 *
 * Must be called before the DRBGs are first instantiated for @p ctx.
 */
int RAND_set_seed_source_type(OSSL_LIB_CTX *ctx, const char *seed,
    const char *propq);

/**
 * @brief Mix @p num bytes from @p buf into the PRNG (equivalent to RAND_add with full entropy).
 * @param buf Bytes to mix into the generator state.
 * @param num Number of bytes at @p buf; treated as @p num bytes of randomness.
 */
void RAND_seed(const void *buf, int num);
/**
 * @brief Keep OS random devices open across forks when @p keep is nonzero.
 * @param keep Nonzero to retain open /dev/urandom-style descriptors; zero to allow close-on-fork.
 */
void RAND_keep_random_devices_open(int keep);

#if defined(__ANDROID__) && defined(__NDK_FPABI__)
__NDK_FPABI__ /* __attribute__((pcs("aapcs"))) on ARM */
#endif
    /**
     * @brief Mix additional bytes into the PRNG state with an estimated entropy amount.
     * @param buf Bytes mixed into the generator; contents cannot be recovered from later output.
     * @param num Number of bytes at @p buf.
     * @param randomness Estimated randomness in @p buf, in bytes, between 0 and @p num.
     */
    void RAND_add(const void *buf, int num, double randomness);
/**
 * @brief Mix up to @p max_bytes of file @p file into the PRNG seed pool.
 * @param file Path of the seed file to read.
 * @param max_bytes Maximum bytes to read, or -1 to read the whole file.
 * @return Number of bytes read, or a negative value on error.
 */
int RAND_load_file(const char *file, long max_bytes);
/**
 * @brief Write a seed file containing entropy from the CSPRNG for later RAND_load_file() use.
 * @param file Path of the seed file to create or overwrite.
 * @return Number of bytes written, or -1 on failure.
 */
int RAND_write_file(const char *file);
/**
 * @brief Build the default path for the PRNG seed file into a caller-provided buffer.
 * @param file Output buffer that receives the path (for example from RANDFILE or $HOME/.rnd).
 * @param num Size of @p file in bytes.
 * @return Pointer to @p file on success, or NULL on error.
 */
const char *RAND_file_name(char *file, size_t num);
/**
 * @brief Report whether the PRNG has been sufficiently seeded for RAND_bytes().
 * @return 1 if seeded enough to generate random data, or 0 otherwise.
 */
int RAND_status(void);

#ifndef OPENSSL_NO_EGD
int RAND_query_egd_bytes(const char *path, unsigned char *buf, int bytes);
int RAND_egd(const char *path);
int RAND_egd_bytes(const char *path, int bytes);
#endif

/**
 * @brief Reseed the PRNG by polling trusted system entropy sources.
 * @return 1 on success, or 0 if seeding from system sources failed.
 */
int RAND_poll(void);

#if defined(_WIN32) && (defined(BASETYPES) || defined(_WINDEF_H))
/* application has to include <windows.h> in order to use these */
#ifndef OPENSSL_NO_DEPRECATED_1_1_0
OSSL_DEPRECATEDIN_1_1_0 void RAND_screen(void);
OSSL_DEPRECATEDIN_1_1_0 int RAND_event(UINT, WPARAM, LPARAM);
#endif
#endif

#ifdef __cplusplus
}
#endif

#endif
