/*
 * WARNING: do not edit!
 * Generated by Makefile from include/openssl/srp.h.in
 *
 * Copyright 2004-2021 The OpenSSL Project Authors. All Rights Reserved.
 * Copyright (c) 2004, EdelKey Project. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 *
 * Originally written by Christophe Renou and Peter Sylvester,
 * for the EdelKey project.
 */

/* clang-format off */

/* clang-format on */

#ifndef OPENSSL_SRP_H
#define OPENSSL_SRP_H
#pragma once

#include <openssl/macros.h>
#ifndef OPENSSL_NO_DEPRECATED_3_0
#define HEADER_SRP_H
#endif

#include <openssl/opensslconf.h>

#ifndef OPENSSL_NO_SRP
#include <stdio.h>
#include <string.h>
#include <openssl/safestack.h>
#include <openssl/bn.h>
#include <openssl/crypto.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef OPENSSL_NO_DEPRECATED_3_0

/**
 * @brief Cache entry mapping a base64-encoded SRP group parameter to a BIGNUM.
 */
typedef struct SRP_gN_cache_st {
    /** Base64 text of the cached parameter (used as the lookup key). */
    char *b64_bn;
    /** Parsed big-number value for @c b64_bn. */
    BIGNUM *bn;
} SRP_gN_cache;
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(SRP_gN_cache, SRP_gN_cache, SRP_gN_cache)
#define sk_SRP_gN_cache_num(sk) OPENSSL_sk_num(ossl_check_const_SRP_gN_cache_sk_type(sk))
#define sk_SRP_gN_cache_value(sk, idx) ((SRP_gN_cache *)OPENSSL_sk_value(ossl_check_const_SRP_gN_cache_sk_type(sk), (idx)))
#define sk_SRP_gN_cache_new(cmp) ((STACK_OF(SRP_gN_cache) *)OPENSSL_sk_new(ossl_check_SRP_gN_cache_compfunc_type(cmp)))
#define sk_SRP_gN_cache_new_null() ((STACK_OF(SRP_gN_cache) *)OPENSSL_sk_new_null())
#define sk_SRP_gN_cache_new_reserve(cmp, n) ((STACK_OF(SRP_gN_cache) *)OPENSSL_sk_new_reserve(ossl_check_SRP_gN_cache_compfunc_type(cmp), (n)))
#define sk_SRP_gN_cache_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_SRP_gN_cache_sk_type(sk), (n))
#define sk_SRP_gN_cache_free(sk) OPENSSL_sk_free(ossl_check_SRP_gN_cache_sk_type(sk))
#define sk_SRP_gN_cache_zero(sk) OPENSSL_sk_zero(ossl_check_SRP_gN_cache_sk_type(sk))
#define sk_SRP_gN_cache_delete(sk, i) ((SRP_gN_cache *)OPENSSL_sk_delete(ossl_check_SRP_gN_cache_sk_type(sk), (i)))
#define sk_SRP_gN_cache_delete_ptr(sk, ptr) ((SRP_gN_cache *)OPENSSL_sk_delete_ptr(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr)))
#define sk_SRP_gN_cache_push(sk, ptr) OPENSSL_sk_push(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr))
#define sk_SRP_gN_cache_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr))
#define sk_SRP_gN_cache_pop(sk) ((SRP_gN_cache *)OPENSSL_sk_pop(ossl_check_SRP_gN_cache_sk_type(sk)))
#define sk_SRP_gN_cache_shift(sk) ((SRP_gN_cache *)OPENSSL_sk_shift(ossl_check_SRP_gN_cache_sk_type(sk)))
#define sk_SRP_gN_cache_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_SRP_gN_cache_sk_type(sk),ossl_check_SRP_gN_cache_freefunc_type(freefunc))
#define sk_SRP_gN_cache_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr), (idx))
#define sk_SRP_gN_cache_set(sk, idx, ptr) ((SRP_gN_cache *)OPENSSL_sk_set(ossl_check_SRP_gN_cache_sk_type(sk), (idx), ossl_check_SRP_gN_cache_type(ptr)))
#define sk_SRP_gN_cache_find(sk, ptr) OPENSSL_sk_find(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr))
#define sk_SRP_gN_cache_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr))
#define sk_SRP_gN_cache_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_type(ptr), pnum)
#define sk_SRP_gN_cache_sort(sk) OPENSSL_sk_sort(ossl_check_SRP_gN_cache_sk_type(sk))
#define sk_SRP_gN_cache_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_SRP_gN_cache_sk_type(sk))
#define sk_SRP_gN_cache_dup(sk) ((STACK_OF(SRP_gN_cache) *)OPENSSL_sk_dup(ossl_check_const_SRP_gN_cache_sk_type(sk)))
#define sk_SRP_gN_cache_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(SRP_gN_cache) *)OPENSSL_sk_deep_copy(ossl_check_const_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_copyfunc_type(copyfunc), ossl_check_SRP_gN_cache_freefunc_type(freefunc)))
#define sk_SRP_gN_cache_set_cmp_func(sk, cmp) ((sk_SRP_gN_cache_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_SRP_gN_cache_sk_type(sk), ossl_check_SRP_gN_cache_compfunc_type(cmp)))

/* clang-format on */

/**
 * @brief SRP verifier database entry for one user (salt, verifier, and group parameters).
 */
typedef struct SRP_user_pwd_st {
    /** User identifier string (owned by this structure). */
    char *id;
    /** Salt value @c s used when computing the verifier (owned by this structure). */
    BIGNUM *s;
    /** Password verifier @c v = g^x mod N (owned by this structure). */
    BIGNUM *v;
    /** Generator @c g for the SRP group (not owned; typically points at shared constants). */
    const BIGNUM *g;
    /** Safe prime modulus @c N for the SRP group (not owned; typically points at shared constants). */
    const BIGNUM *N;
    /** Optional informational string stored with the user entry (owned by this structure). */
    char *info;
} SRP_user_pwd;
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(SRP_user_pwd, SRP_user_pwd, SRP_user_pwd)
#define sk_SRP_user_pwd_num(sk) OPENSSL_sk_num(ossl_check_const_SRP_user_pwd_sk_type(sk))
#define sk_SRP_user_pwd_value(sk, idx) ((SRP_user_pwd *)OPENSSL_sk_value(ossl_check_const_SRP_user_pwd_sk_type(sk), (idx)))
#define sk_SRP_user_pwd_new(cmp) ((STACK_OF(SRP_user_pwd) *)OPENSSL_sk_new(ossl_check_SRP_user_pwd_compfunc_type(cmp)))
#define sk_SRP_user_pwd_new_null() ((STACK_OF(SRP_user_pwd) *)OPENSSL_sk_new_null())
#define sk_SRP_user_pwd_new_reserve(cmp, n) ((STACK_OF(SRP_user_pwd) *)OPENSSL_sk_new_reserve(ossl_check_SRP_user_pwd_compfunc_type(cmp), (n)))
#define sk_SRP_user_pwd_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_SRP_user_pwd_sk_type(sk), (n))
#define sk_SRP_user_pwd_free(sk) OPENSSL_sk_free(ossl_check_SRP_user_pwd_sk_type(sk))
#define sk_SRP_user_pwd_zero(sk) OPENSSL_sk_zero(ossl_check_SRP_user_pwd_sk_type(sk))
#define sk_SRP_user_pwd_delete(sk, i) ((SRP_user_pwd *)OPENSSL_sk_delete(ossl_check_SRP_user_pwd_sk_type(sk), (i)))
#define sk_SRP_user_pwd_delete_ptr(sk, ptr) ((SRP_user_pwd *)OPENSSL_sk_delete_ptr(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr)))
#define sk_SRP_user_pwd_push(sk, ptr) OPENSSL_sk_push(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr))
#define sk_SRP_user_pwd_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr))
#define sk_SRP_user_pwd_pop(sk) ((SRP_user_pwd *)OPENSSL_sk_pop(ossl_check_SRP_user_pwd_sk_type(sk)))
#define sk_SRP_user_pwd_shift(sk) ((SRP_user_pwd *)OPENSSL_sk_shift(ossl_check_SRP_user_pwd_sk_type(sk)))
#define sk_SRP_user_pwd_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_SRP_user_pwd_sk_type(sk),ossl_check_SRP_user_pwd_freefunc_type(freefunc))
#define sk_SRP_user_pwd_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr), (idx))
#define sk_SRP_user_pwd_set(sk, idx, ptr) ((SRP_user_pwd *)OPENSSL_sk_set(ossl_check_SRP_user_pwd_sk_type(sk), (idx), ossl_check_SRP_user_pwd_type(ptr)))
#define sk_SRP_user_pwd_find(sk, ptr) OPENSSL_sk_find(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr))
#define sk_SRP_user_pwd_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr))
#define sk_SRP_user_pwd_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_type(ptr), pnum)
#define sk_SRP_user_pwd_sort(sk) OPENSSL_sk_sort(ossl_check_SRP_user_pwd_sk_type(sk))
#define sk_SRP_user_pwd_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_SRP_user_pwd_sk_type(sk))
#define sk_SRP_user_pwd_dup(sk) ((STACK_OF(SRP_user_pwd) *)OPENSSL_sk_dup(ossl_check_const_SRP_user_pwd_sk_type(sk)))
#define sk_SRP_user_pwd_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(SRP_user_pwd) *)OPENSSL_sk_deep_copy(ossl_check_const_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_copyfunc_type(copyfunc), ossl_check_SRP_user_pwd_freefunc_type(freefunc)))
#define sk_SRP_user_pwd_set_cmp_func(sk, cmp) ((sk_SRP_user_pwd_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_SRP_user_pwd_sk_type(sk), ossl_check_SRP_user_pwd_compfunc_type(cmp)))

/* clang-format on */

/**
 * @brief Allocate an empty SRP_user_pwd structure.
 * @return New user entry, or NULL on allocation failure.
 */
OSSL_DEPRECATEDIN_3_0
SRP_user_pwd *SRP_user_pwd_new(void);
/**
 * @brief Free an SRP_user_pwd structure and owned fields.
 * @param user_pwd Entry to free, or NULL.
 */
OSSL_DEPRECATEDIN_3_0
void SRP_user_pwd_free(SRP_user_pwd *user_pwd);

/**
 * @brief Set the SRP group parameters on a user verifier entry (caller retains ownership of @p g/@p N; deprecated).
 * @param user_pwd Entry to update.
 * @param g Generator for the SRP group (not freed by SRP_user_pwd_free()).
 * @param N Safe prime modulus for the SRP group (not freed by SRP_user_pwd_free()).
 */
OSSL_DEPRECATEDIN_3_0
void SRP_user_pwd_set_gN(SRP_user_pwd *user_pwd, const BIGNUM *g,
    const BIGNUM *N);
/**
 * @brief Set the user identifier and optional info string on an SRP_user_pwd.
 * @param user_pwd Entry to update.
 * @param id User name to copy, or NULL to clear.
 * @param info Optional info string to copy, or NULL to clear.
 * @return 1 on success, 0 on allocation failure.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_user_pwd_set1_ids(SRP_user_pwd *user_pwd, const char *id,
    const char *info);
/**
 * @brief Assign salt and verifier BIGNUMs to an SRP_user_pwd (ownership transfers on success).
 * @param user_pwd Entry to update.
 * @param s Salt value, or NULL to clear.
 * @param v Verifier value, or NULL to clear.
 * @return 1 on success, 0 on failure.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_user_pwd_set0_sv(SRP_user_pwd *user_pwd, BIGNUM *s, BIGNUM *v);

/**
 * @brief In-memory SRP verifier database loaded from a verifier file.
 */
typedef struct SRP_VBASE_st {
    /** Stack of registered user verifier entries. */
    STACK_OF(SRP_user_pwd) *users_pwd;
    /** Cache of parsed SRP group parameters keyed by base64 text. */
    STACK_OF(SRP_gN_cache) *gN_cache;
    /* to simulate a user */
    /** Seed string used to synthesize dummy verifiers for unknown usernames (RFC 5054). */
    char *seed_key;
    /** Default generator used when synthesizing unknown-user entries. */
    const BIGNUM *default_g;
    /** Default safe prime used when synthesizing unknown-user entries. */
    const BIGNUM *default_N;
} SRP_VBASE;

/*
 * Internal structure storing N and g pair
 */
/**
 * @brief Named SRP group parameters (generator @c g and safe prime @c N).
 */
typedef struct SRP_gN_st {
    /** Text identifier for the group (for example "2048" or "8192"). */
    char *id;
    /** Generator @c g for the named SRP group. */
    const BIGNUM *g;
    /** Safe prime modulus @c N for the group. */
    const BIGNUM *N;
} SRP_gN;
/* clang-format off */
SKM_DEFINE_STACK_OF_INTERNAL(SRP_gN, SRP_gN, SRP_gN)
#define sk_SRP_gN_num(sk) OPENSSL_sk_num(ossl_check_const_SRP_gN_sk_type(sk))
#define sk_SRP_gN_value(sk, idx) ((SRP_gN *)OPENSSL_sk_value(ossl_check_const_SRP_gN_sk_type(sk), (idx)))
#define sk_SRP_gN_new(cmp) ((STACK_OF(SRP_gN) *)OPENSSL_sk_new(ossl_check_SRP_gN_compfunc_type(cmp)))
#define sk_SRP_gN_new_null() ((STACK_OF(SRP_gN) *)OPENSSL_sk_new_null())
#define sk_SRP_gN_new_reserve(cmp, n) ((STACK_OF(SRP_gN) *)OPENSSL_sk_new_reserve(ossl_check_SRP_gN_compfunc_type(cmp), (n)))
#define sk_SRP_gN_reserve(sk, n) OPENSSL_sk_reserve(ossl_check_SRP_gN_sk_type(sk), (n))
#define sk_SRP_gN_free(sk) OPENSSL_sk_free(ossl_check_SRP_gN_sk_type(sk))
#define sk_SRP_gN_zero(sk) OPENSSL_sk_zero(ossl_check_SRP_gN_sk_type(sk))
#define sk_SRP_gN_delete(sk, i) ((SRP_gN *)OPENSSL_sk_delete(ossl_check_SRP_gN_sk_type(sk), (i)))
#define sk_SRP_gN_delete_ptr(sk, ptr) ((SRP_gN *)OPENSSL_sk_delete_ptr(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr)))
#define sk_SRP_gN_push(sk, ptr) OPENSSL_sk_push(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr))
#define sk_SRP_gN_unshift(sk, ptr) OPENSSL_sk_unshift(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr))
#define sk_SRP_gN_pop(sk) ((SRP_gN *)OPENSSL_sk_pop(ossl_check_SRP_gN_sk_type(sk)))
#define sk_SRP_gN_shift(sk) ((SRP_gN *)OPENSSL_sk_shift(ossl_check_SRP_gN_sk_type(sk)))
#define sk_SRP_gN_pop_free(sk, freefunc) OPENSSL_sk_pop_free(ossl_check_SRP_gN_sk_type(sk),ossl_check_SRP_gN_freefunc_type(freefunc))
#define sk_SRP_gN_insert(sk, ptr, idx) OPENSSL_sk_insert(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr), (idx))
#define sk_SRP_gN_set(sk, idx, ptr) ((SRP_gN *)OPENSSL_sk_set(ossl_check_SRP_gN_sk_type(sk), (idx), ossl_check_SRP_gN_type(ptr)))
#define sk_SRP_gN_find(sk, ptr) OPENSSL_sk_find(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr))
#define sk_SRP_gN_find_ex(sk, ptr) OPENSSL_sk_find_ex(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr))
#define sk_SRP_gN_find_all(sk, ptr, pnum) OPENSSL_sk_find_all(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_type(ptr), pnum)
#define sk_SRP_gN_sort(sk) OPENSSL_sk_sort(ossl_check_SRP_gN_sk_type(sk))
#define sk_SRP_gN_is_sorted(sk) OPENSSL_sk_is_sorted(ossl_check_const_SRP_gN_sk_type(sk))
#define sk_SRP_gN_dup(sk) ((STACK_OF(SRP_gN) *)OPENSSL_sk_dup(ossl_check_const_SRP_gN_sk_type(sk)))
#define sk_SRP_gN_deep_copy(sk, copyfunc, freefunc) ((STACK_OF(SRP_gN) *)OPENSSL_sk_deep_copy(ossl_check_const_SRP_gN_sk_type(sk), ossl_check_SRP_gN_copyfunc_type(copyfunc), ossl_check_SRP_gN_freefunc_type(freefunc)))
#define sk_SRP_gN_set_cmp_func(sk, cmp) ((sk_SRP_gN_compfunc)OPENSSL_sk_set_cmp_func(ossl_check_SRP_gN_sk_type(sk), ossl_check_SRP_gN_compfunc_type(cmp)))

/* clang-format on */

/**
 * @brief Allocate an SRP verifier database, optionally copying @p seed_key for unknown-user simulation (deprecated).
 * @param seed_key Random NUL-terminated seed copied into the database, or NULL to disable dummy users.
 * @return New SRP_VBASE, or NULL on allocation failure.
 */
OSSL_DEPRECATEDIN_3_0
SRP_VBASE *SRP_VBASE_new(char *seed_key);
/**
 * @brief Free an SRP verifier database and its contents.
 * @param vb Database to free, or NULL.
 */
OSSL_DEPRECATEDIN_3_0
void SRP_VBASE_free(SRP_VBASE *vb);
/**
 * @brief Load SRP verifier entries from a text verifier file into a database.
 * @param vb Database to populate.
 * @param verifier_file Path to the verifier file (see SRP_VBASE format in srp.c).
 * @return SRP_NO_ERROR on success, or an SRP_ERR_* code on failure.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_VBASE_init(SRP_VBASE *vb, char *verifier_file);

/**
 * @brief Append a user entry to an SRP verifier database (ownership transfers on success).
 * @param vb Database to update.
 * @param user_pwd User entry to store.
 * @return 1 on success, 0 on failure.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_VBASE_add0_user(SRP_VBASE *vb, SRP_user_pwd *user_pwd);

/* NOTE: unlike in SRP_VBASE_get_by_user, caller owns the returned pointer.*/
/**
 * @brief Look up an SRP user entry, synthesizing one from @c seed_key when absent.
 * @param vb Verifier database to search.
 * @param username User name to look up.
 * @return Newly allocated SRP_user_pwd on success (caller must free), or NULL on error.
 */
OSSL_DEPRECATEDIN_3_0
SRP_user_pwd *SRP_VBASE_get1_by_user(SRP_VBASE *vb, char *username);

/**
 * @brief Create base64-encoded SRP salt and verifier strings for a user/password.
 * @param user User name.
 * @param pass Password.
 * @param salt Address of salt pointer: receives a newly allocated base64 salt when *@p salt is NULL, or uses the supplied value.
 * @param verifier Receives a newly allocated base64 verifier string.
 * @param N Base64-encoded safe prime, or NULL to select a default group via @p g.
 * @param g Base64-encoded generator when @p N is set, or a default group id such as "2048" when @p N is NULL.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return "*" if @p N was supplied, the selected group id otherwise; do not free. NULL on error.
 */
OSSL_DEPRECATEDIN_3_0
char *SRP_create_verifier_ex(const char *user, const char *pass, char **salt,
    char **verifier, const char *N, const char *g,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Create base64-encoded SRP salt and verifier strings (default library context; deprecated).
 * @param user User name.
 * @param pass Password.
 * @param salt Address of salt pointer: receives a newly allocated base64 salt when *@p salt is NULL, or uses the supplied value.
 * @param verifier Receives a newly allocated base64 verifier string.
 * @param N Base64-encoded safe prime, or NULL to select a default group via @p g.
 * @param g Base64-encoded generator when @p N is set, or a default group id such as "2048" when @p N is NULL.
 * @return "*" if @p N was supplied, the selected group id otherwise; do not free. NULL on error.
 */
OSSL_DEPRECATEDIN_3_0
char *SRP_create_verifier(const char *user, const char *pass, char **salt,
    char **verifier, const char *N, const char *g);
/**
 * @brief Create SRP salt and verifier BIGNUMs for a user/password.
 * @param user User name.
 * @param pass Password.
 * @param salt Address of salt pointer: receives a newly allocated salt when *@p salt is NULL, or uses the supplied value.
 * @param verifier Receives a newly allocated verifier BIGNUM.
 * @param N Safe prime modulus for the SRP group.
 * @param g Generator for the SRP group.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return 1 on success, 0 on error.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_create_verifier_BN_ex(const char *user, const char *pass, BIGNUM **salt,
    BIGNUM **verifier, const BIGNUM *N,
    const BIGNUM *g, OSSL_LIB_CTX *libctx,
    const char *propq);
/**
 * @brief Create SRP salt and verifier BIGNUMs for a user/password.
 * @param user User name.
 * @param pass Password.
 * @param salt Address of salt pointer: receives a newly allocated salt when *@p salt is NULL, or uses the supplied value.
 * @param verifier Receives a newly allocated verifier BIGNUM.
 * @param N Safe prime modulus for the SRP group.
 * @param g Generator for the SRP group.
 * @return 1 on success, 0 on error.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_create_verifier_BN(const char *user, const char *pass, BIGNUM **salt,
    BIGNUM **verifier, const BIGNUM *N,
    const BIGNUM *g);

#define SRP_NO_ERROR 0
#define SRP_ERR_VBASE_INCOMPLETE_FILE 1
#define SRP_ERR_VBASE_BN_LIB 2
#define SRP_ERR_OPEN_FILE 3
#define SRP_ERR_MEMORY 4

#define DB_srptype 0
#define DB_srpverifier 1
#define DB_srpsalt 2
#define DB_srpid 3
#define DB_srpgN 4
#define DB_srpinfo 5
#undef DB_NUMBER
#define DB_NUMBER 6

#define DB_SRP_INDEX 'I'
#define DB_SRP_VALID 'V'
#define DB_SRP_REVOKED 'R'
#define DB_SRP_MODIF 'v'

/* see srp.c */
/**
 * @brief Test whether @p g and @p N match a built-in RFC 5054 SRP group.
 * @param g Generator to test.
 * @param N Safe prime modulus to test.
 * @return Text group id (for example "2048") when recognized; do not free. NULL if unknown or on error.
 */
OSSL_DEPRECATEDIN_3_0
char *SRP_check_known_gN_param(const BIGNUM *g, const BIGNUM *N);
/**
 * @brief Return built-in RFC 5054 SRP group parameters for a textual group id (deprecated).
 * @param id Group size id such as "1024", "2048", or "8192", or NULL for the 8192-bit default.
 * @return Pointer to a static SRP_gN (do not free), or NULL if @p id is unknown.
 */
OSSL_DEPRECATEDIN_3_0
SRP_gN *SRP_get_default_gN(const char *id);

/* server side .... */
/**
 * @brief Compute the SRP server shared secret S = (A*v^u)^b mod N (deprecated).
 * @param A Client public value.
 * @param v User password verifier.
 * @param u Scrambling parameter from SRP_Calc_u().
 * @param b Server secret exponent.
 * @param N Safe prime modulus.
 * @return Newly allocated shared secret, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_server_key(const BIGNUM *A, const BIGNUM *v, const BIGNUM *u,
    const BIGNUM *b, const BIGNUM *N);
/**
 * @brief Compute the server public value B = g^b + k*v (mod N) for TLS-SRP.
 * @param b Server secret exponent.
 * @param N Safe prime modulus.
 * @param g Generator.
 * @param v User password verifier.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Newly allocated B value, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_B_ex(const BIGNUM *b, const BIGNUM *N, const BIGNUM *g,
    const BIGNUM *v, OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Compute the server public value B = g^b + k*v (mod N) for TLS-SRP (default library context; deprecated).
 * @param b Server secret exponent.
 * @param N Safe prime modulus.
 * @param g Generator.
 * @param v User password verifier.
 * @return Newly allocated B value, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_B(const BIGNUM *b, const BIGNUM *N, const BIGNUM *g,
    const BIGNUM *v);

/**
 * @brief Verify that the client public value A is non-zero modulo N.
 * @param A Client public value.
 * @param N Safe prime modulus.
 * @return 1 if A mod N is non-zero, 0 otherwise.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_Verify_A_mod_N(const BIGNUM *A, const BIGNUM *N);
/**
 * @brief Compute the SRP scrambling parameter u = H(PAD(A) || PAD(B)).
 * @param A Client public value.
 * @param B Server public value.
 * @param N Safe prime modulus used for padding width.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Newly allocated u value, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_u_ex(const BIGNUM *A, const BIGNUM *B, const BIGNUM *N,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Compute the SRP scrambling parameter u = H(A, B) using the default library context (deprecated).
 * @param A Client public value.
 * @param B Server public value.
 * @param N Safe prime modulus (used when hashing A and B as padded fields).
 * @return Newly allocated u value, or NULL on error; free with BN_free().
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_u(const BIGNUM *A, const BIGNUM *B, const BIGNUM *N);

/* client side .... */

/**
 * @brief Compute the private exponent x = H(s, H(user:pass)) for TLS-SRP.
 * @param s Salt value.
 * @param user User name.
 * @param pass Password.
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Newly allocated x value, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_x_ex(const BIGNUM *s, const char *user, const char *pass,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Compute x = H(s, H(user:pass)) using the default library context (deprecated).
 * @param s Salt value.
 * @param user User name.
 * @param pass Password.
 * @return Newly allocated private exponent x, or NULL on error; free with BN_free().
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_x(const BIGNUM *s, const char *user, const char *pass);
/**
 * @brief Compute the client public value A = g^a mod N.
 * @param a Client secret exponent.
 * @param N Safe prime modulus.
 * @param g Generator.
 * @return Newly allocated A value, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_A(const BIGNUM *a, const BIGNUM *N, const BIGNUM *g);
/**
 * @brief Compute the client session key K for TLS-SRP.
 * @param N Safe prime modulus.
 * @param B Server public value.
 * @param g Generator.
 * @param x Private exponent from SRP_Calc_x().
 * @param a Client secret exponent.
 * @param u Scrambling parameter from SRP_Calc_u().
 * @param libctx Library context for algorithm fetching, or NULL for default.
 * @param propq Property query for algorithm fetching, or NULL.
 * @return Newly allocated session key, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_client_key_ex(const BIGNUM *N, const BIGNUM *B, const BIGNUM *g,
    const BIGNUM *x, const BIGNUM *a, const BIGNUM *u,
    OSSL_LIB_CTX *libctx, const char *propq);
/**
 * @brief Compute the client session key K for TLS-SRP (deprecated).
 * @param N SRP group modulus.
 * @param B Server public value.
 * @param g SRP generator.
 * @param x Private exponent from SRP_Calc_x().
 * @param a Client ephemeral private exponent.
 * @param u Scrambling parameter from SRP_Calc_u().
 * @return Newly allocated session key, or NULL on error. Caller must free.
 */
OSSL_DEPRECATEDIN_3_0
BIGNUM *SRP_Calc_client_key(const BIGNUM *N, const BIGNUM *B, const BIGNUM *g,
    const BIGNUM *x, const BIGNUM *a, const BIGNUM *u);
/**
 * @brief Verify that the server public value B is non-zero modulo N.
 * @param B Server public value.
 * @param N Safe prime modulus.
 * @return 1 if B mod N is non-zero, 0 otherwise.
 */
OSSL_DEPRECATEDIN_3_0
int SRP_Verify_B_mod_N(const BIGNUM *B, const BIGNUM *N);

#define SRP_MINIMAL_N 1024

#endif /* OPENSSL_NO_DEPRECATED_3_0 */

/* This method ignores the configured seed and fails for an unknown user. */
#ifndef OPENSSL_NO_DEPRECATED_1_1_0
/**
 * @brief Look up an SRP user entry without transferring ownership (deprecated).
 * @param vb Verifier database to search.
 * @param username User name to look up.
 * @return Internal SRP_user_pwd pointer, or NULL if not found; do not free.
 */
OSSL_DEPRECATEDIN_1_1_0
SRP_user_pwd *SRP_VBASE_get_by_user(SRP_VBASE *vb, char *username);
#endif

#ifdef __cplusplus
}
#endif
#endif

#endif
